### ISSUE TITLE
"global-status --prune" command fails for docker provider

### ISSUE THREAD

**Issue by mkuzmin** [mitchellh/vagrant#4645]
`vagrant global-status --prune` command fails with this error message:
```
C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:531:in `machine': undefined method
`join' for nil:NilClass (NoMethodError)
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/docker/provider.rb:88:in `block in host_vm'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/docker/provider.rb:80:in `host_vm'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/docker/provider.rb:149:in `state'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:446:in `state'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine_index.rb:447:in `valid?'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/global-status/command.rb:45:in `block in execute'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine_index.rb:102:in `block in each'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine_index.rb:101:in `each'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine_index.rb:101:in `each'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/global-status/command.rb:42:in `execute'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:42:in `execute'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:292:in `cli'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.6.5/bin/vagrant:174:in `<main>'
```

**Comment by mitchellh** [comment]
I still can't repro this. :( If we can ever get a solid repro case I'd love to fix this but I haven't heard of it happening otherwise so I think its okay.
