### ISSUE TITLE
SSH private keys on smartcards do not work correctly (provisioning issue)

### ISSUE THREAD

**Issue by tykeal** [mitchellh/vagrant#4680]
Perhaps I'm a little odd in that I don't have any of my private keys on disk partly due to corporate requirements and partly because I prefer to not leave keys just laying around on disk, even if they have strong passwords. They're all stored on a smartcard (YubiKey NEO in the PGPCard applet to be specific).

Normally when something requires you to specify the identity file to use just pointing to a copy of the public key file will be enough for the ssh-agent to send the correct key during an SSH connection and this works correctly when using vagrant ssh. It fails however, during provisioning. The reason being that the pubkey is being handed to net.ssh.authentication.key_manager and fails to load it as it isn't a proper PKey.

Here's the various debugging (FYI this is using the Rackspace provider and I can't tell from the debug if it's actually a failing of that provider or the base Vagrant)

Vagrant is version 1.6.5 on a Fedora 19 system

During box setup at the provisioning phase

```
--[cut]--
 INFO environment: Running hook: provisioner_run
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Method: Vagrant::Action::Builtin::Provision#run_provisioner>
 INFO warden: Calling IN action: #<Proc:0x0000000261bf78@/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO machine: Calling action: read_ssh_info on provider RackSpace Cloud
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000000028676d8>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x0000000287b520>
 INFO warden: Calling IN action: #<VagrantPlugins::Rackspace::Action::ConnectRackspace:0x00000002878078>
 INFO connect_rackspace: Connecting to Rackspace region...
 INFO warden: Calling IN action: #<VagrantPlugins::Rackspace::Action::ReadSSHInfo:0x000000028ad318>
 INFO warden: Calling OUT action: #<VagrantPlugins::Rackspace::Action::ReadSSHInfo:0x000000028ad318>
 INFO warden: Calling OUT action: #<VagrantPlugins::Rackspace::Action::ConnectRackspace:0x00000002878078>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x0000000287b520>
 INFO machine: Calling action: read_ssh_info on provider RackSpace Cloud
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000001bc45c0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000001bd10b8>
 INFO warden: Calling IN action: #<VagrantPlugins::Rackspace::Action::ConnectRackspace:0x00000001bd1068>
 INFO connect_rackspace: Connecting to Rackspace region...
 INFO warden: Calling IN action: #<VagrantPlugins::Rackspace::Action::ReadSSHInfo:0x00000001c4c6c8>
 INFO warden: Calling OUT action: #<VagrantPlugins::Rackspace::Action::ReadSSHInfo:0x00000001c4c6c8>
 INFO warden: Calling OUT action: #<VagrantPlugins::Rackspace::Action::ConnectRackspace:0x00000001bd1068>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000001bd10b8>
DEBUG ssh: Checking key permissions: /home/tykeal/.ssh/yubikey.pub
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 23.253.237.148
 INFO ssh:   - Port: 22
 INFO ssh:   - Username: root
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/home/tykeal/.ssh/yubikey.pub"]
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2014-10-21T10:53:27.474948 #15745] DEBUG -- net.ssh.transport.session[963df4]: establishing connection to 23.253.237.148:22
D, [2014-10-21T10:53:27.551651 #15745] DEBUG -- net.ssh.transport.session[963df4]: connection established
I, [2014-10-21T10:53:27.551959 #15745]  INFO -- net.ssh.transport.server_version[9fba28]: negotiating protocol version
D, [2014-10-21T10:53:27.642381 #15745] DEBUG -- net.ssh.transport.server_version[9fba28]: remote is `SSH-2.0-OpenSSH_6.4'
D, [2014-10-21T10:53:27.642573 #15745] DEBUG -- net.ssh.transport.server_version[9fba28]: local is `SSH-2.0-Ruby/Net::SSH_2.9.1 x86_64-linux'
D, [2014-10-21T10:53:27.725046 #15745] DEBUG -- tcpsocket[967bd4]: read 1536 bytes
D, [2014-10-21T10:53:27.725230 #15745] DEBUG -- tcpsocket[967bd4]: received packet nr 0 type 20 len 1532
I, [2014-10-21T10:53:27.725346 #15745]  INFO -- net.ssh.transport.algorithms[aea858]: got KEXINIT from server
I, [2014-10-21T10:53:27.725593 #15745]  INFO -- net.ssh.transport.algorithms[aea858]: sending KEXINIT
D, [2014-10-21T10:53:27.725836 #15745] DEBUG -- tcpsocket[967bd4]: queueing packet nr 0 type 20 len 2020
D, [2014-10-21T10:53:27.725944 #15745] DEBUG -- tcpsocket[967bd4]: sent 2024 bytes
I, [2014-10-21T10:53:27.725998 #15745]  INFO -- net.ssh.transport.algorithms[aea858]: negotiating algorithms
D, [2014-10-21T10:53:27.726171 #15745] DEBUG -- net.ssh.transport.algorithms[aea858]: negotiated:
* kex: diffie-hellman-group-exchange-sha1
* host_key: ssh-rsa
* encryption_server: aes128-cbc
* encryption_client: aes128-cbc
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2014-10-21T10:53:27.726222 #15745] DEBUG -- net.ssh.transport.algorithms[aea858]: exchanging keys
D, [2014-10-21T10:53:27.726479 #15745] DEBUG -- tcpsocket[967bd4]: queueing packet nr 1 type 34 len 20
D, [2014-10-21T10:53:27.726560 #15745] DEBUG -- tcpsocket[967bd4]: sent 24 bytes
D, [2014-10-21T10:53:27.885424 #15745] DEBUG -- tcpsocket[967bd4]: read 152 bytes
D, [2014-10-21T10:53:27.885655 #15745] DEBUG -- tcpsocket[967bd4]: received packet nr 1 type 31 len 148
D, [2014-10-21T10:53:27.888099 #15745] DEBUG -- tcpsocket[967bd4]: queueing packet nr 2 type 32 len 140
D, [2014-10-21T10:53:27.888190 #15745] DEBUG -- tcpsocket[967bd4]: sent 144 bytes
D, [2014-10-21T10:53:27.964361 #15745] DEBUG -- tcpsocket[967bd4]: read 720 bytes
D, [2014-10-21T10:53:27.964581 #15745] DEBUG -- tcpsocket[967bd4]: received packet nr 2 type 33 len 700
D, [2014-10-21T10:53:27.967161 #15745] DEBUG -- tcpsocket[967bd4]: queueing packet nr 3 type 21 len 20
D, [2014-10-21T10:53:27.967259 #15745] DEBUG -- tcpsocket[967bd4]: sent 24 bytes
D, [2014-10-21T10:53:27.967365 #15745] DEBUG -- tcpsocket[967bd4]: received packet nr 3 type 21 len 12
D, [2014-10-21T10:53:27.967778 #15745] DEBUG -- net.ssh.authentication.session[1404ac4]: beginning authentication of `root'
D, [2014-10-21T10:53:27.967934 #15745] DEBUG -- tcpsocket[967bd4]: queueing packet nr 4 type 5 len 28
D, [2014-10-21T10:53:27.968001 #15745] DEBUG -- tcpsocket[967bd4]: sent 52 bytes
D, [2014-10-21T10:53:28.151245 #15745] DEBUG -- tcpsocket[967bd4]: read 52 bytes
D, [2014-10-21T10:53:28.151547 #15745] DEBUG -- tcpsocket[967bd4]: received packet nr 4 type 6 len 28
D, [2014-10-21T10:53:28.151774 #15745] DEBUG -- net.ssh.authentication.session[1404ac4]: trying none
D, [2014-10-21T10:53:28.152072 #15745] DEBUG -- tcpsocket[967bd4]: queueing packet nr 5 type 50 len 44
D, [2014-10-21T10:53:28.152211 #15745] DEBUG -- tcpsocket[967bd4]: sent 68 bytes
D, [2014-10-21T10:53:28.362568 #15745] DEBUG -- tcpsocket[967bd4]: read 84 bytes
D, [2014-10-21T10:53:28.362840 #15745] DEBUG -- tcpsocket[967bd4]: received packet nr 5 type 51 len 60
D, [2014-10-21T10:53:28.363035 #15745] DEBUG -- net.ssh.authentication.session[1404ac4]: allowed methods: publickey,gssapi-keyex,gssapi-with-mic,password
D, [2014-10-21T10:53:28.363174 #15745] DEBUG -- net.ssh.authentication.methods.none[1409010]: none failed
D, [2014-10-21T10:53:28.363319 #15745] DEBUG -- net.ssh.authentication.session[1404ac4]: trying publickey
E, [2014-10-21T10:53:28.364072 #15745] ERROR -- net.ssh.authentication.key_manager[1409448]: could not load private key file `/home/tykeal/.ssh/yubikey.pub': ArgumentError (Could not parse PKey: no start line)
D, [2014-10-21T10:53:28.364210 #15745] DEBUG -- net.ssh.authentication.agent[140c51c]: connecting to ssh-agent
D, [2014-10-21T10:53:28.364442 #15745] DEBUG -- net.ssh.authentication.agent[140c51c]: sending agent request 1 len 44
D, [2014-10-21T10:53:28.364627 #15745] DEBUG -- net.ssh.authentication.agent[140c51c]: received agent packet 5 len 1
D, [2014-10-21T10:53:28.364733 #15745] DEBUG -- net.ssh.authentication.agent[140c51c]: sending agent request 11 len 0
D, [2014-10-21T10:53:28.365927 #15745] DEBUG -- net.ssh.authentication.agent[140c51c]: received agent packet 12 len 954
D, [2014-10-21T10:53:28.366341 #15745] DEBUG -- net.ssh.authentication.session[1404ac4]: trying password
E, [2014-10-21T10:53:28.366487 #15745] ERROR -- net.ssh.authentication.session[1404ac4]: all authorization methods failed (tried none, publickey, password)

DEBUG ssh: == Net-SSH connection debug-level log END ==
ERROR warden: Error occurred: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000001466738>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-0bfa607b21ef9424b05c1304ee876db6
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002833540>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::SSHAuthenticationFailed: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.>
ERROR vagrant: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/communicators/ssh/communicator.rb:373:in `rescue in connect'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/communicators/ssh/communicator.rb:315:in `connect'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/communicators/ssh/communicator.rb:182:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/communicators/ssh/communicator.rb:219:in `sudo'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/shell/provisioner.rb:54:in `block (2 levels) in provision_ssh'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/shell/provisioner.rb:51:in `tap'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/shell/provisioner.rb:51:in `block in provision_ssh'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/shell/provisioner.rb:178:in `with_script_file'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/shell/provisioner.rb:49:in `provision_ssh'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/provisioners/shell/provisioner.rb:21:in `provision'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/provision.rb:127:in `run_provisioner'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:386:in `hook'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/provision.rb:115:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/provision.rb:115:in `block in call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/provision.rb:103:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/provision.rb:103:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:196:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:173:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/provision/command.rb:30:in `block in execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:220:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/provision/command.rb:29:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:42:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:292:in `cli'
/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:174:in `<main>'
 INFO interface: error: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.
SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.
 INFO interface: Machine: error-exit ["Vagrant::Errors::SSHAuthenticationFailed", "SSH authentication failed! This is typically caused by the public/private\nkeypair for the SSH user not being properly set on the guest VM. Please\nverify that the guest VM is setup with the proper public key, and that\nthe private key path for Vagrant is setup properly as well."]
--[/cut]--
```

Debug for a standard vagrant ssh (same system I just cancelled out when the provisioning failed)

```
--[cut]--
DEBUG command: Invoking `ssh` action on machine
 INFO machine: Calling action: ssh on provider RackSpace Cloud
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/tykeal/repos/personal/vagrant/add-lf-config>]
DEBUG host: Trying: redhat
 INFO host: Detected: redhat!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000003df6b48>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x000000029f8100>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x000000029f8038>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x0000000315a768>
 INFO warden: Calling IN action: #<VagrantPlugins::Rackspace::Action::IsCreated:0x00000003168318>
 INFO machine: Calling action: read_state on provider RackSpace Cloud
DEBUG environment: Attempting to acquire process-lock: machine-action-0bfa607b21ef9424b05c1304ee876db6
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-0bfa607b21ef9424b05c1304ee876db6
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000000031d5b48>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x000000031f7e28>
 INFO warden: Calling IN action: #<VagrantPlugins::Rackspace::Action::ConnectRackspace:0x000000031f7e00>
 INFO connect_rackspace: Connecting to Rackspace region...
 INFO warden: Calling IN action: #<VagrantPlugins::Rackspace::Action::ReadState:0x0000000322ae18>
 INFO warden: Calling OUT action: #<VagrantPlugins::Rackspace::Action::ReadState:0x0000000322ae18>
 INFO warden: Calling OUT action: #<VagrantPlugins::Rackspace::Action::ConnectRackspace:0x000000031f7e00>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x000000031f7e28>
 INFO environment: Released process lock: machine-action-0bfa607b21ef9424b05c1304ee876db6
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO warden: Calling OUT action: #<VagrantPlugins::Rackspace::Action::IsCreated:0x00000003168318>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Warden:0x000000039e1a58>
 INFO warden: Calling IN action: #<Proc:0x00000003a7cd50@/opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SSHExec:0x000000039e17b0>
 INFO machine: Calling action: read_ssh_info on provider RackSpace Cloud
DEBUG environment: Attempting to acquire process-lock: machine-action-0bfa607b21ef9424b05c1304ee876db6
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-0bfa607b21ef9424b05c1304ee876db6
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000003b2ce30>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000003b44bc0>
 INFO warden: Calling IN action: #<VagrantPlugins::Rackspace::Action::ConnectRackspace:0x00000003b44b70>
 INFO connect_rackspace: Connecting to Rackspace region...
 INFO warden: Calling IN action: #<VagrantPlugins::Rackspace::Action::ReadSSHInfo:0x00000003bc6698>
 INFO warden: Calling OUT action: #<VagrantPlugins::Rackspace::Action::ReadSSHInfo:0x00000003bc6698>
 INFO warden: Calling OUT action: #<VagrantPlugins::Rackspace::Action::ConnectRackspace:0x00000003b44b70>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000003b44bc0>
 INFO environment: Released process lock: machine-action-0bfa607b21ef9424b05c1304ee876db6
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
DEBUG ssh: Checking key permissions: /home/tykeal/.ssh/yubikey.pub
 INFO ssh: Invoking SSH: ["root@23.253.237.148", "-p", "22", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "LogLevel=FATAL", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-o", "IdentitiesOnly=yes", "-i", "/home/tykeal/.ssh/yubikey.pub"]
--[/cut]--
```

**Comment by cehoffman** [comment]
Well just over a year later and I'm in the same situation as tykeal. I'm been using a smart card of some form for about a year and half now, but just started using vagrant in any serious fashion. I look forward to this feature.

**Comment by Daemoen** [comment]
...  Well, at least this explains why I have such a huge headache when dealing with Vagrant in our environment.  We are also a yubikey shop, and the identities only drastically reduces our ability to use it efficiently.  Feature request requested here as well.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
