### ISSUE TITLE
Chef Client node/client delete not working

### ISSUE THREAD

**Issue by Nalum** [mitchellh/vagrant#4954]
Adding the config for deleting Node and Clients is giving the following error:

```
    api: Are you sure you want to destroy the 'api' VM? [y/N] y
==> api: Forcing shutdown of VM...
==> api: Destroying VM and associated drives...
==> api: Running cleanup tasks for 'chef_client' provisioner...
==> api: Deleting client "lm-api-development" from Chef server...
==> api: Cleaning up the 'client' for Chef failed. The stdout and
==> api: stderr are shown below. Vagrant will continue destroying the machine,
==> api: so please clean up these resources manually.
==> api: 
==> api: stdout: 
==> api: 
==> api: stderr: /usr/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'chef' (>= 0) among 47 total gem(s) (Gem::LoadError)
==> api: 	from /usr/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
==> api: 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
==> api: 	from /usr/local/bin/knife:22:in `<main>'
==> api: Deleting node "lm-api-development" from Chef server...
==> api: Cleaning up the 'node' for Chef failed. The stdout and
==> api: stderr are shown below. Vagrant will continue destroying the machine,
==> api: so please clean up these resources manually.
==> api: 
==> api: stdout: 
==> api: 
==> api: stderr: /usr/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'chef' (>= 0) among 47 total gem(s) (Gem::LoadError)
==> api: 	from /usr/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
==> api: 	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
==> api: 	from /usr/local/bin/knife:22:in `<main>'
```
My config is as follows:
```
VAGRANTFILE_API_VERSION = "2"
node_prefix = "lm-"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "trusty64"

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
    end

    config.vm.define :api do |api|
        api.vm.network "private_network", ip: "192.168.33.10"

        api.vm.provision "chef_client" do |chef|
            chef.chef_server_url = "https://chef.server.com"
            chef.validation_key_path = "~/.chef/chef-validator.pem"
            chef.validation_client_name = "chef-validator"
            chef.environment = "development"
            chef.node_name = node_prefix + "api-development"
            chef.add_role "api"
            chef.delete_node = true
            chef.delete_client = true
        end
    end
end
```

**Comment by sethvargo** [comment]
@Nalum I just merged some changes into core that will better clear out the environment that should fix this issue.

**Comment by Nalum** [comment]
Thanks for the update. Will check it out when it's released.
