### ISSUE TITLE
Rsync-auto crash when "file has vanished"

### ISSUE THREAD

**Issue by szoper** [mitchellh/vagrant#4991]
It happens from time to time and it is extremely annoying, to find that the only reason my code does not work as expected is "vagrant rsync-auto" crashed again. Files mentioned in the output seem to be related to Mercurial SCM integration with PhpStorm. Vagrant seems to get stupid around them.

Here's the output @Vagrant 1.6.3, Kubuntu 14.04, VirtualBox 4.3.20, rsync 3.1.0:
```
==> default: Watching: /home/szoper/work/supersam/supersam
==> default: Rsyncing folder: /home/szoper/work/supersam/supersam/ => /vagrant
==> default:   - Exclude: [".vagrant/", ".hg/", ".git/", ".idea/", "Log/"]
...
[Listen warning]: Change block raised an exception: There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /home/szoper/work/supersam/supersam/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/home/szoper/.vagrant.d/insecure_private_key' --exclude .vagrant/ --exclude .hg/ --exclude .git/ --exclude .idea/ --exclude Log/ /home/szoper/work/supersam/supersam/ vagrant@127.0.0.1:/vagrant
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
file has vanished: "/home/szoper/work/supersam/supersam/hg-checklink-kcopfm"
file has vanished: "/home/szoper/work/supersam/supersam/hg-checklink-BclWLV"
FATAL I/O ERROR: dying to avoid a --delete-during issue with a pre-3.0.7 receiver.
rsync error: requested action not supported (code 4) at flist.c(1882) [sender=3.1.0]
Backtrace:
        /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/synced_folders/rsync/helper.rb:132:in `rsync_single'
        /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/synced_folders/rsync/command/rsync_auto.rb:161:in `block (2 levels) in callback'                                      
        /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/synced_folders/rsync/command/rsync_auto.rb:158:in `each'                                                              
        /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/synced_folders/rsync/command/rsync_auto.rb:158:in `block in callback'                                                 
        /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/synced_folders/rsync/command/rsync_auto.rb:157:in `each'                                                              
        /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/synced_folders/rsync/command/rsync_auto.rb:157:in `callback'                                                          
        /opt/vagrant/embedded/gems/gems/listen-2.7.5/lib/listen/listener.rb:159:in `call'                                                                                           
        /opt/vagrant/embedded/gems/gems/listen-2.7.5/lib/listen/listener.rb:159:in `block in _wait_for_changes'                                                                     
        /opt/vagrant/embedded/gems/gems/listen-2.7.5/lib/listen/listener.rb:148:in `loop'                                                                                           
        /opt/vagrant/embedded/gems/gems/listen-2.7.5/lib/listen/listener.rb:148:in `_wait_for_changes'                                                                              
        /opt/vagrant/embedded/gems/gems/listen-2.7.5/lib/listen/listener.rb:41:in `block in start'
```

**Comment by mitchellh** [comment]
Fixed
