### ISSUE TITLE
Incompatible character encodings

### ISSUE THREAD

**Issue by Jericho** [mitchellh/vagrant#5158]
I just finished installing Vagrant on my Windows machine and after rebooting I am attempting to setup for the first time but I'm getting the following error:

```
C:\MyVagrantBoxes>vagrant init hashicorp/precise64
C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:224:in `join': incompatible character enco
dings: IBM437 and Windows-1252 (Encoding::CompatibilityError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:224:in `setup_environment'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:15:in `setup'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler.rb:129:in `setup'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:71:in `<main>'
```

What does it mean?

**Comment by mitchellh** [comment]
We have a lot of encoding issues that are tracked by a very old meta issue. We're not very sure how to fix this, but would love to over time.
