### ISSUE TITLE
Cannot start vagrant

### ISSUE THREAD

**Issue by semerak-michal** [mitchellh/vagrant#5208]
I Cannot start vagrant machine. Exception:
```
C:/Apps/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/safe_puts.rb:22:in `write': Invalid argument - <STDOUT> (Errno::EINVAL)
        from C:/Apps/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/safe_puts.rb:22:in `puts'
        from C:/Apps/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/safe_puts.rb:22:in `safe_puts'
        from C:/Apps/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/ui.rb:217:in `block (2 levels) in say'
        from C:/Apps/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/ui.rb:216:in `synchronize'
        from C:/Apps/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/ui.rb:216:in `block in say'
```

Vagrantfile:

```
if !Vagrant.has_plugin?('vagrant-hostsupdater') &&  ENV['SKIP'] != 'true'
    puts "The vagrant-hostsupdater plugin is required. Please install it with \"vagrant plugin install vagrant-hostsupdater\""
    exit
end

if !Vagrant.has_plugin?('vagrant-puppet-install') &&  ENV['SKIP'] != 'true'
    puts "The vagrant-puppet-install plugin is required. Please install it with \"vagrant plugin install vagrant-puppet-install\""
    exit
end

Vagrant.configure("2") do |config|
  
  ### Ubuntu 14.04 pro Parallels Mac OS - je potreba verze min. 10, aby podporovala forwarded porty
  # config.vm.box = "parallels/ubuntu-14.04"

  ### 64bit Ubuntu 14.04 pro Virtualbox
  #config.vm.box = "ubuntu/trusty64"

  ### 32bit Ubuntu 14.04 pro Virtualbox
  config.vm.box = "ubuntu/trusty32"

  ### Nastaveni site
  config.vm.network :forwarded_port, host: 5000, guest: 80
  config.vm.network :forwarded_port, host: 33060, guest: 3306
  config.vm.network :private_network, ip: "192.168.3.10"
  config.vm.hostname = "es.local.cz"
  config.hostsupdater.aliases = ["admin.es.local.cz", "ws.es.local.cz"]

  ### Vychozi sdilene slozky - vboxsf filesystem - pekelne pomale - nevadi protoze nesdilime zdrojaky
  config.vm.synced_folder "./", "/vagrant", owner: "vagrant", group: "www-data", mount_options: ["dmode=775,fmode=664"]

  ### NFS docela rychle, ale funguje jen na linux+mac, nemam overene ze funguji prava
  #config.vm.synced_folder "./", "/vagrant", type: "nfs", mount_options: ["async,rw"]

  ### RSYNC nejrychlejsi ale trva nekolik sekund nez se syncnou zmeny - momentalne se nepouziva, protoze nejde na windows a jinde neni potreba   
  ### !!! po spusteni virtualu je nutne spustit nejaky watcher, napr. vagrant rsync-auto nebo
  #config.vm.synced_folder "./", "/vagrant", owner: "vagrant", group: "www-data", type: "rsync"

  ### Automaticka instalace Puppetu do boxu, ktere ho nepodporuji
  config.puppet_install.puppet_version = :latest

  ### Instalace vseho potrebneho pomoci puppet provisioneru
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.module_path = 'puppet/modules'
    puppet.manifest_file = 'init.pp'
    #puppet.options = '--verbose --debug'
  end

  ### Nazev VM jiny nez 'default'
  config.vm.define "es" do |es|
  end

end
```

Thanks for help.

**Comment by panickervinod** [comment]
Facing a similar issue.  How was this resolved?

**Comment by panickervinod** [comment]
np, Thanks .
