### ISSUE TITLE
Vagrant-Login Gem cannot be found, OSX 10.9

### ISSUE THREAD

**Issue by smarek** [mitchellh/vagrant#5270]
I've just found out, my vagrant env started producing this message.
I've upgraded to 1.7.2 (latest osx), and it still happens.

I've also deleted plugins.json, and ran command `vagrant plugin install`, which produces the same error.

```
> vagrant help
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:368:in `resolve': Could not find gem 'vagrant-login (>= 0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:166:in `start'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:129:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:193:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:132:in `specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:177:in `specs_for'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant.rb:76:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:105:in `<main>'
```
Fixture error
```
> vagrant plugin install
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:368:in `resolve': Could not find gem 'vagrant-login (>= 0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:166:in `start'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:129:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:193:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:132:in `specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:177:in `specs_for'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant.rb:76:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:105:in `<main>'
```

**Comment by smarek** [comment]
I workarounded the issue for now like that, which is obviously very wrong.
```
sudo cp -R /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.3 /opt/vagrant/embedded/gems/gems/vagrant-login
sudo cp /opt/vagrant/embedded/gems/specifications/vagrant-share-1.1.3.gemspec /opt/vagrant/embedded/gems/specifications/vagrant-login-0.0.1.gemspec
```

Where I changed the start of `vagrant-login-0.0.1.gemspec` to 
```
Gem::Specification.new do |s|
  s.name = "vagrant-login"
  s.version = "0.0.1"
```

Now `vagrant plugin list` gives out expected results
```
> vagrant plugin list
vagrant-login (0.0.1)
vagrant-vbguest (0.10.0)
```

Running
```
> vagrant plugin uninstall vagrant-vbguest
Uninstalling the 'vagrant-vbguest' plugin...
> vagrant plugin uninstall vagrant-login
Uninstalling the 'vagrant-login' plugin...
> vagrant plugin list
No plugins installed.
```

Files (in `gems/gems` and `gems/specifications`) however remained, and cannot be updated:
```
> vagrant plugin update
Updating installed plugins...
All plugins are up to date.
```

**Comment by reinh** [comment]
Also experiencing this.

**Comment by phinze** [comment]
Sorry about this folks - looking into it now!

**Comment by phinze** [comment]
Ok so `vagrant-login` was [rolled into core](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#170-december-9-2014) as of `1.7.0` on December 9th.

Best guess is that you have some left over state from a previous version in `~/.vagrant.d/gems` - if you move that out of the way, does everything become sane once again?

**Comment by smarek** [comment]
@phinze what exactly should be moved away? whole `gems` directory? In my case it contains just `net-ssh-2.9.2` gem and empty info files in `gems/buils_info`

**Comment by phinze** [comment]
@smarek yeah I'd recommend the entirety of `~/.vagrant.d/gems` and if that doesn't work try moving all of `~/.vagrant.d`. My current theory is that something old is left around and it has to be somewhere in there.

**Comment by reinh** [comment]
@phinze Removing `~/.vagrant.d/gems` worked for me, except that I got new errors for missing plugins (including when trying to reinstall those plugins). I had to remove `~/.vagrant.d` entirely and start over, but 1.7.2 works now!

**Comment by phinze** [comment]
@reinh hmm so definitely an upgrade metadata problem. glad to hear you got it sorted!

So for others here, recommended solution is the same one presented in `bin/vagrant` when plugins get funky:

```
# note installed plugins
rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems
# verify everything works again
# reinstall desired plugins
```

Going to close for now - feel free to make noise if this still causes you pain and we can try to dig in further.
