### ISSUE TITLE
local-exec push not working on Windows

### ISSUE THREAD

**Issue by tsauter** [mitchellh/vagrant#5307]
The local-exec push method is not working on Windows. 
The ruby fork statement isn't supported on this platform. It doesn't matter if an inline or external script is used.

Full error message is:

```
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/safe_exec.rb:22:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/safe_exec.rb:22:in `exec'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/local-exec/push.rb:41:in `execute!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/local-exec/push.rb:36:in `execute_script!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/local-exec/push.rb:14:in `push'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:567:in `push'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/push/command.rb:28:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

**Comment by molnara** [comment]
I get the same error in Windows 7.

**Comment by sethvargo** [comment]
@mitchellh weird... how do the other shell things work?

**Comment by neuron303** [comment]
Actually it is working with script files. Use files that windows is able to start (i.e. use .bat, .exe, ... files)

Since the inline script is written to a .sh temporary file this is broken.

The error message is triggered by the fallback mechanism to fork when Kernel.exec does not work.
If the fallback is disabled Kernel.exec returns following:
```
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/safe_exec.rb:23:in `exec': Exec format error - C:/Users/user/my-script.sh (Errno::ENOEXEC)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/safe_exec.rb:23:in `exec'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/local-exec/push.rb:41:in `execute!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/local-exec/push.rb:36:in `execute_script!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/local-exec/push.rb:14:in `push'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:567:in `push'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/push/command.rb:28:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

**Comment by chambm** [comment]
+1

**Comment by robertnealan** [comment]
Not sure as to the actual root cause of the issue (other than Windows not supporting fork() by default), but using git-bash from https://git-for-windows.github.io/ works as a workaround as it automatically includes Cygwin (which adds support for fork()).

Has an option to add everything to your default path (so it'd fix the issue in other terminals), but haven't tested it personally.

**Comment by dpalomar** [comment]
Same issue, tested on win10 with git bash and cygwin.

**Comment by KptnKMan** [comment]
Same issue, win10 using OpenSSH and vagrant 1.8.5
