### ISSUE TITLE
Trace on startup

### ISSUE THREAD

**Issue by acidprime** [mitchellh/vagrant#5366]
```shell
 sw_vers
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F34
```

vagrant 1.7.2  new installation

```
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/state_file.rb:16:in `rescue in initialize': uninitialized constant Vagrant::Errors (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/state_file.rb:13:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/manager.rb:32:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/manager.rb:32:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/manager.rb:27:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/manager.rb:27:in `instance'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/lib/vagrant/pre-rubygems.rb:22:in `<main>'
```

**Comment by acidprime** [comment]
Seems to be the same issue on 1.6.5

```
/Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/state_file.rb:16:in `rescue in initialize': uninitialized constant Vagrant::Errors (NameError)
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/state_file.rb:13:in `initialize'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/manager.rb:32:in `new'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/manager.rb:32:in `initialize'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/manager.rb:27:in `new'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/manager.rb:27:in `instance'
	from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/lib/vagrant/pre-rubygems.rb:22:in `<main>'
```

**Comment by acidprime** [comment]
remove my .vagrant.d directory and this worked, I had migrated it from a previous laptop so thats like the issue.

**Comment by mitchellh** [comment]
Yeah I think you got some weirdness with your existing install. Glad you have it figured out!
