### ISSUE TITLE
syntax error in bundler.rb

### ISSUE THREAD

**Issue by ror6ax** [mitchellh/vagrant#5387]
Hi guys, I'm writing my first Vagrant plugin.
When I issue  `bundle exec vagrant` in develpomnt directory I get following output.
```
Vagrant appears to be running in a Bundler environment. Your 
existing Gemfile will be used. Vagrant will not auto-load any plugins
installed with `vagrant plugin`. Vagrant will autoload any plugins in
the 'plugins' group in your Gemfile. You can force Vagrant to take over
with VAGRANT_FORCE_BUNDLER.

/usr/local/lib/ruby/gems/1.9.1/bundler/gems/vagrant-ecf7bceb2665/lib/vagrant/pre-rubygems.rb:19:in `require_relative': /usr/local/lib/ruby/gems/1.9.1/bundler/gems/vagrant-ecf7bceb2665/lib/vagrant/bundler.rb:217: syntax error, unexpected tPOW (SyntaxError)
    def internal_install(plugins, update, **extra)
                                            ^
/usr/local/lib/ruby/gems/1.9.1/bundler/gems/vagrant-ecf7bceb2665/lib/vagrant/bundler.rb:298: class definition in method body
/usr/local/lib/ruby/gems/1.9.1/bundler/gems/vagrant-ecf7bceb2665/lib/vagrant/bundler.rb:315: class definition in method body
/usr/local/lib/ruby/gems/1.9.1/bundler/gems/vagrant-ecf7bceb2665/lib/vagrant/bundler.rb:368: syntax error, unexpected keyword_end, expecting $end
	from /usr/local/lib/ruby/gems/1.9.1/bundler/gems/vagrant-ecf7bceb2665/lib/vagrant/pre-rubygems.rb:19:in `<main>'

```

Just in case, I'm using the stub of plugin from the Plugin Develpoment part of documentation.
Please advice.

**Comment by sethvargo** [comment]
You are using an old version of Ruby. You need to use Ruby 2.1+ :smile:
