### ISSUE TITLE
No host IP was given to the Vagrant core NFS helper

### ISSUE THREAD

**Issue by alesabater** [mitchellh/vagrant#5401]
I am trying to create and EC2 instance with ubuntu 14.04, it is a really simple machine just for the purpose of development, the problem I am having is that sometimes the script creates the machine without any errors and sometimes I get the following error:

No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.

This happens without making any change to the Vagrantfile.

Here is my Vagrantfile:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "aws-test"
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = { access_key }
    aws.secret_access_key = { secret_access_key }
    aws.keypair_name = "Development"
    override.ssh.private_key_path = "~/Documents/certificates/Development.pem"
    aws.instance_type = "t2.micro"
    aws.region = "us-west-2"
    aws.security_groups = "vagrant"
    aws.ami = "ami-65755555"
    override.ssh.username = "ubuntu"
```

Here is the output in DEBUG mode:

```text
ERROR warden: Error occurred: No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000002ce03b8>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-ee75c50f80e9b1feb783c8ebf77030ac
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x00000002e88828>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::NFSNoHostIP: No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.>
ERROR vagrant: No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/synced_folders/nfs/synced_folder.rb:43:in `enable'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:90:in `block in call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:87:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/home/asabater/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/action/update_all.rb:30:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/home/asabater/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
```

**Comment by Y4Rvik** [comment]
Looks like that issue related to vagrant-aws plugin. By default it doesn't work with NFS and used rsync instead.  Related issue https://github.com/mitchellh/vagrant-aws/issues/340

**Comment by therealprologic** [comment]
I get this issue too with ``vagrant-aws 0.6.0``

**Comment by lonniev** [comment]
And I get it with vagrant softlayer. Trying to avoid the choice of rsync to not create nested paths for destination copies of the chef-solo directories. Darn vagrant/softlayer/windows wants to torch the admin at every step of the way! ;-)

**Comment by lonniev** [comment]
Aha, my instance may be due to trying to run "vagrant provision" after changing the sync folder types to NFS from rsync but without first running "vagrant up". Apparently, it is "vagrant up" that writes the entries into /etc/exports.

The error message could say something indicative like "no entry for Host found in /etc/exports. Try restarting the vagrant with 'vagrant up' to correct this."

**Comment by kororo** [comment]
Hi guys,

This fix will do the jobs as well.

```
config.vm.provider :aws do |aws, override|
    override.nfs.functional = false
```

Hope helps.

**Comment by mitchellh** [comment]
This is a bug with the AWS provider.

**Comment by gapotts** [comment]
I also ran into this problem with vagrant-vshpere when running it out of a remotely automounted home directory. The solution to fix it is similar to that of the aws provider:

```ruby
     node.vm.provider :vsphere do |vsphere, override|
          override.nfs.functional = false
```

**Comment by kenorb** [comment]
Duplicate of #1437

**Comment by dsnyder0li** [comment]
FWIW, I'm seeing the same issue with the Linode provider:

`$ vagrant version
Installed Version: 1.9.6
Latest Version: 1.9.6

$ vagrant plugin list
vagrant-hosts-provisioner (2.0)
vagrant-linode (0.2.8)
vagrant-share (1.1.9, system)
vagrant-vbguest (0.14.2)`

The workaround of setting `override.nfs.functional = false` seems to have worked for me. Perhaps rsync should be the default? I'm not sure how NFS would ever be useful for this provider.

**Comment by rudycmi** [comment]
Just FYI this is still happening on 2.0.1 and the fix is still the same as https://github.com/hashicorp/vagrant/issues/5401#issuecomment-115240904

**Comment by jmangt** [comment]
Same issue in

```
➜  ~ vagrant version
Installed Version: 2.0.1
Latest Version: 2.0.1

You're running an up-to-date version of Vagrant!
➜  ~ vagrant plugin list
vagrant-aws (0.7.2)
vagrant-share (1.1.9, system)
vagrant-vbguest (0.15.0)
```
