### ISSUE TITLE
Ansible failed to complete successfully. Exit status: 2

### ISSUE THREAD

**Issue by agaviria** [mitchellh/vagrant#5442]
Hi, I seem to have an error but I'm not sure if it's a bug or a misconfiguration.  I'm including the debug below.
        
        TASK: [golang-1.5 | Check out Go 1.4] *****************************************
        DEBUG subprocess: stdout: <172.17.0.105>
         INFO interface: info: <172.17.0.105>

        <172.17.0.105>
        DEBUG subprocess: stdout: <172.17.0.105> repo=https://go.googlesource.com/go dest=/home/vagrant/opt/go version=release-branch.go1.4.2
         INFO interface: info: <172.17.0.105> repo=https://go.googlesource.com/go dest=/home/vagrant/opt/go version=release-branch.go1.4.2

        <172.17.0.105> repo=https://go.googlesource.com/go dest=/home/vagrant/opt/go version=release-branch.go1.4.2
        DEBUG subprocess: stdout: <172.17.0.105> IdentityFile=/Users/Alex/tmp/devbox-golang/keys/vagrantssh.key ControlPersist=60s Compression=yes KbdInteractiveAuthentication=no ProxyCommand=ssh PasswordAuthentication=no UserKnownHostsFile=/dev/null User=root ForwardAgent=yes ControlPath=/Users/Alex/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=22 ConnectTimeout=10
         INFO interface: info: <172.17.0.105> IdentityFile=/Users/Alex/tmp/devbox-golang/keys/vagrantssh.key ControlPersist=60s Compression=yes KbdInteractiveAuthentication=no ProxyCommand=ssh PasswordAuthentication=no UserKnownHostsFile=/dev/null User=root ForwardAgent=yes ControlPath=/Users/Alex/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=22 ConnectTimeout=10

        <172.17.0.105> IdentityFile=/Users/Alex/tmp/devbox-golang/keys/vagrantssh.key ControlPersist=60s Compression=yes KbdInteractiveAuthentication=no ProxyCommand=ssh PasswordAuthentication=no UserKnownHostsFile=/dev/null User=root ForwardAgent=yes ControlPath=/Users/Alex/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=22 ConnectTimeout=10
        DEBUG subprocess: stdout: <172.17.0.105>
         INFO interface: info: <172.17.0.105>

        <172.17.0.105>
        DEBUG subprocess: stdout: <172.17.0.105> IdentityFile=/Users/Alex/tmp/devbox-golang/keys/vagrantssh.key ControlPersist=60s Compression=yes KbdInteractiveAuthentication=no ProxyCommand=ssh PasswordAuthentication=no 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1425849841.84-48781188755057/git; rm -rf /root/.ansible/tmp/ansible-tmp-1425849841.84-48781188755057/ >/dev/null 2>&1' UserKnownHostsFile=/dev/null User=root ForwardAgent=yes ControlPath=/Users/Alex/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=22 ConnectTimeout=10
         INFO interface: info: <172.17.0.105> IdentityFile=/Users/Alex/tmp/devbox-golang/keys/vagrantssh.key ControlPersist=60s Compression=yes KbdInteractiveAuthentication=no ProxyCommand=ssh PasswordAuthentication=no 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1425849841.84-48781188755057/git; rm -rf /root/.ansible/tmp/ansible-tmp-1425849841.84-48781188755057/ >/dev/null 2>&1' UserKnownHostsFile=/dev/null User=root ForwardAgent=yes ControlPath=/Users/Alex/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=22 ConnectTimeout=10

        <172.17.0.105> IdentityFile=/Users/Alex/tmp/devbox-golang/keys/vagrantssh.key ControlPersist=60s Compression=yes KbdInteractiveAuthentication=no ProxyCommand=ssh PasswordAuthentication=no 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1425849841.84-48781188755057/git; rm -rf /root/.ansible/tmp/ansible-tmp-1425849841.84-48781188755057/ >/dev/null 2>&1' UserKnownHostsFile=/dev/null User=root ForwardAgent=yes ControlPath=/Users/Alex/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=22 ConnectTimeout=10
        DEBUG subprocess: stdout: failed: [docker] => {"failed": true}
        msg: Failed to checkout release-branch.go1.4.2
         INFO interface: info: failed: [docker] => {"failed": true}
        msg: Failed to checkout release-branch.go1.4.2

        failed: [docker] => {"failed": true}
        msg: Failed to checkout release-branch.go1.4.2
        DEBUG subprocess: stdout:
        FATAL: all hosts have already failed -- aborting

        PLAY RECAP ********************************************************************
         INFO interface: info:
        FATAL: all hosts have already failed -- aborting

        PLAY RECAP ********************************************************************

        FATAL: all hosts have already failed -- aborting

        PLAY RECAP ********************************************************************
        DEBUG subprocess: stdout:            to retry, use: --limit @/Users/Alex/playbook.retry

        docker                     : ok=15   changed=14   unreachable=0    failed=1

         INFO interface: info:            to retry, use: --limit @/Users/Alex/playbook.retry

        docker                     : ok=15   changed=14   unreachable=0    failed=1

                   to retry, use: --limit @/Users/Alex/playbook.retry

        docker                     : ok=15   changed=14   unreachable=0    failed=1

        DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31828
        DEBUG subprocess: Exit status: 2
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000100d04de0>
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000100cdd9c0>
         INFO warden: Beginning recovery process...
         INFO warden: Calling recover: #<Vagrant::Action::Builtin::HandleForwardedPortCollisions:0x00000101092958>
         INFO warden: Recovery complete.
         INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000001022b86f0>
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000001022b8790>
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000001028417e8>
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000102841900>
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000102841a40>
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000102841ab8>
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
        ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO warden: Beginning recovery process...
         INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000001023b0fd0>
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO warden: Recovery complete.
         INFO warden: Beginning recovery process...
         INFO warden: Recovery complete.
         INFO environment: Released process lock: machine-action-eab3c563209d7f071fb0acb32a87858f
         INFO environment: Running hook: environment_unload
         INFO runner: Preparing hooks for middleware sequence...
         INFO runner: 1 hooks defined.
         INFO runner: Running action: #<Vagrant::Action::Builder:0x0000010231bb88>
        ERROR vagrant: Vagrant experienced an error! Details:
        ERROR vagrant: #<Vagrant::Errors::AnsibleFailed: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.>
        ERROR vagrant: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
        ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/ansible/provisioner.rb:85:in `provision'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:133:in `run_provisioner'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:428:in `hook'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:121:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:121:in `block in call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:103:in `each'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:103:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:96:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/env_set.rb:19:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/docker/action/stop.rb:16:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/reload/command.rb:39:in `block in execute'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:220:in `each'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/reload/command.rb:37:in `execute'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
         INFO interface: error: Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
        Ansible failed to complete successfully. Any error output should be
        visible above. Please fix these errors and try again.
         INFO interface: Machine: error-exit ["Vagrant::Errors::AnsibleFailed", "Ansible failed to complete successfully. Any error output should be\nvisible above. Please fix these errors and try again."]

**Comment by agaviria** [comment]
Here is the Vagrantfile:

        # -*- mode: ruby -*-
        # vi: set ft=ruby :

        Vagrant.require_version ">= 1.7.0"
        VAGRANTFILE_API_VERSION = "2"

        Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

          # --------------------------------------------------------------------
          # Definitions for the VirtualBox machine
          # --------------------------------------------------------------------
          config.vm.define "virtualbox", autostart: false do |vbox|
            vbox.vm.provider "virtualbox" do |v|
              v.memory = 2048
              v.cpus = 2
            end
            vbox.vm.box = "ubuntu/trusty64"
            vbox.vm.network "forwarded_port", guest: 80, host: 8080
            vbox.vm.boot_timeout = 600
            vbox.vm.provision :ansible do |ansible|
              ansible.playbook = "playbook.yml"
            end
            # Tell the user what to do next
          vbox.vm.provision "shell", inline: "echo 'Finished! Now try logging in with: vagrant ssh docker'"
          end

          # --------------------------------------------------------------------
          # Definitions for the Docker container
          # --------------------------------------------------------------------
          config.vm.define "docker", autostart: false do |dkr|
            system("bash genkeys.sh")
            dkr.vm.provider "docker" do |d|
              d.has_ssh = true
              d.remains_running = true
              d.build_dir = "."
            end

            # dkr.ssh.insert_key = false
            dkr.ssh.forward_agent = true   
            dkr.ssh.private_key_path = "keys/vagrantssh.key"
            dkr.ssh.username = "vagrant"

            dkr.vm.provision :ansible do |ansible|
              ansible.playbook = "playbook.yml"
              ansible.extra_vars = { ansible_ssh_user: 'root' }
              ansible.verbose = "vvvv"
            end
            dkr.vm.synced_folder ".", "/vagrant"
            # Tell the user what to do next
          dkr.vm.provision "shell", inline: "echo 'Finished! Now try logging in with: vagrant ssh docker'"
          end
        end

**Comment by agaviria** [comment]
Looks like this ended up being a misconfiguration in the directory structure for the golang task.  I was able to get a complete install without errors after this minor fix.
