### ISSUE TITLE
Vagrant inexplicably crashing almost every time.

### ISSUE THREAD

**Issue by ZeroMax-dev** [mitchellh/vagrant#5443]
Running on a Windows 8.1 (64-bit, all current updates installed), Vagrant 1.7.2 almost always crashes because it can not identify the VirtualBox version. The weird thing is that sometimes the first step goes through but it throws the same error at a later step in the process instead (if i run the command again).

```
C:\Vagrant\rails-dev-box>vagrant up
C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/config.rb:83:in `block in mis
sing_interpolation_argument_handler': missing interpolation argument :vboxmanage
 in "Vagrant detected that VirtualBox appears installed on your system,\nbut cal
ls to detect the version are returning empty. This is often\nindicative of insta
llation issues with VirtualBox. Please verify\nthat VirtualBox is properly insta
lled. As a final verification,\nplease run the following command manually and ve
rify a version is\noutputted:\n\n%{vboxmanage} --version" ({:_key=>:virtualbox_v
ersion_empty, :_namespace=>"vagrant.errors"} given) (I18n::MissingInterpolationA
rgument)
        from C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby
.rb:29:in `call'
        from C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby
.rb:29:in `block in interpolate_hash'
        from C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby
.rb:21:in `gsub'
        from C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby
.rb:21:in `interpolate_hash'
        from C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby
.rb:17:in `interpolate'
        from C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/backend/base.rb:
153:in `interpolate'
        from C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/backend/base.rb:
41:in `translate'
        from C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:157:in `block
 in translate'
        from C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:153:in `catch
'
        from C:/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:153:in `trans
late'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/errors.rb:1
03:in `translate_error'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/errors.rb:7
2:in `initialize'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtu
albox/driver/meta.rb:155:in `exception'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtu
albox/driver/meta.rb:155:in `raise'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtu
albox/driver/meta.rb:155:in `block in read_version'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/retrya
ble.rb:17:in `retryable'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtu
albox/driver/meta.rb:140:in `read_version'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtu
albox/driver/meta.rb:38:in `initialize'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtu
albox/provider.rb:11:in `new'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtu
albox/provider.rb:11:in `usable?'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile
.rb:134:in `machine_config'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile
.rb:45:in `machine'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment
.rb:614:in `machine'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/c
ommand.rb:168:in `block in with_target_vms'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/c
ommand.rb:192:in `call'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/c
ommand.rb:192:in `block in with_target_vms'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/c
ommand.rb:174:in `each'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/c
ommand.rb:174:in `with_target_vms'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/com
mand.rb:74:in `block in execute'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment
.rb:277:in `block (2 levels) in batch'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment
.rb:275:in `tap'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment
.rb:275:in `block in batch'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment
.rb:274:in `synchronize'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment
.rb:274:in `batch'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/com
mand.rb:58:in `execute'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:i
n `execute'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment
.rb:301:in `cli'
        from C:/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<ma
in>'
```

VirtualBox version is 4.3.24, but I also tried several other versions down to 4.3.8 and 4.2.10. The environment variable `VBOX_INSTALL_PATH` or `VBOX_MSI_INSTALL_PATH` respectively are set correctly. I can execute the `vboxmanage --version` command without any problems (the directory is also added to the `PATH`-variable).

I also tried previous versions of vagrant. Anything below v1.7.0 gave me different errors. I'm going crazy. The problem is that the occurrence of the error is inconsistent. If I try again for 3 times for example the error sometimes occurs later in the process...

**Comment by sethvargo** [comment]
Hi @ZeroMax-dev 

I am sorry you are having problems. Could you please run the vboxmanage command a few times and see if you're able to get VirtualBox to give you an error? Are the permissions on the installation correct or do you need to run as an administrative user? Lastly, have you tried restarting your computer. Sometimes VirtualBox just needs a good kick in the pants :smile:.

**Comment by sethvargo** [comment]
Closing due to inactivity. If you would like to re-visit this issue, please comment and we can reopen it.
