### ISSUE TITLE
Weird special characters that cant be converted to UTF-8 (Windows 8.1 Pro)

### ISSUE THREAD

**Issue by LihO** [mitchellh/vagrant#5447]
While trying to run vagrant up I was having hard time with encoding due to different characters that can not be converted to UTF-8. I went through those cases and try to modify those ruby files to enforce UTF-8 with hope that it might help. 

(Please note that this was first time in my life that I've tried to write some Ruby code...) For example in gem childprocess-0.5.5 in file process_builder.rb I've added .force_encoding("UTF-8") at the end of line 59

After some other changes I was able to track down the issue to:

C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/subproces
s.rb:28:in `encode': "\xB2" on UTF-8 (Encoding::InvalidByteSequenceError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/u
til/subprocess.rb:28:in `block in initialize' ...

Have anyone experienced anything similar?

Any help would be appreciated.

**Comment by LihO** [comment]
I've found out that the problem was in character in my user account. I don't know why vagrant stores stuff in C:\Users\...
