### ISSUE TITLE
AuthFailure => AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by michal-jobseeker** [mitchellh/vagrant#5448]
Env: MacOsX 10.10.2
Ruby: 2.1.5
Vagrant: 1.7.2
vagrant-aws: 0.6.0

vagrant up --provider=aws
```
An unexpected error occurred when executing the action on the
<my machine> machine. Please report this as a bug:

AuthFailure => AWS was not able to validate the provided access credentials

/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/expects.rb:6:in `response_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:372:in `response'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:236:in `request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:256:in `rescue in request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:204:in `request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:256:in `rescue in request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:204:in `request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/middlewares/base.rb:10:in `error_call'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:256:in `rescue in request'
/Users/myuser/.vagrant.d/gems/gems/excon-0.44.4/lib/excon/connection.rb:204:in `request'
/Users/myuser/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/sax_parser_connection.rb:37:in `request'
/Users/myuser/.vagrant.d/gems/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:7:in `request'
/Users/myuser/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/compute.rb:528:in `_request'
/Users/myuser/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/compute.rb:523:in `request'
/Users/myuser/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/requests/compute/describe_security_groups.rb:38:in `describe_security_groups'
/Users/myuser/.vagrant.d/gems/gems/fog-aws-0.1.1/lib/fog/aws/models/compute/security_groups.rb:64:in `all'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:192:in `block in allows_ssh_port?'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:191:in `map'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:191:in `allows_ssh_port?'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:98:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/elb_register_instance.rb:16:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/Users/myuser/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by derek-adair** [comment]
You should file this bug in the [vagrant-aws](https://github.com/mitchellh/vagrant-aws) provider project.

**Comment by michal-jobseeker** [comment]
Opened: https://github.com/mitchellh/vagrant-aws/issues/372
