### ISSUE TITLE
"vagrant up" with VMware plugin synced folder mounting fails with "undefined method"

### ISSUE THREAD

**Issue by atombender** [mitchellh/vagrant#5487]
Vagrant 1.7.2. Unfortunately the plugin code is obfuscated (and encrypted?), so I can't debug this locally.

```
vagrant | ==> t11e-vm1-vmware: Enabling and configuring shared folders...
vagrant |    t11e-vm1-vmware: -- /Users/someuser/tmp/vagrant: /vagrant
/Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/synced_folder.rb:72:in `block in enable': undefined method `[]' for nil:NilClass (NoMethodError)
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/synced_folder.rb:52:in `each'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/synced_folder.rb:52:in `enable'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:90:in `block in call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:87:in `each'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/action_farm.rb:1021:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/action_farm.rb:71:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/action_farm.rb:1051:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/action_farm.rb:1265:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/action_farm.rb:273:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/action_farm.rb:143:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/action_farm.rb:1265:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/action_farm.rb:99:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/action_farm.rb:273:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /Users/someuser/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.4/lib/vagrant-vmware-fusion/action_farm.rb:160:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by phinze** [comment]
Hey @atombender  - sorry for the trouble here! Hopefully we can get it sorted quickly. :zap: 

Do you have an example `Vagrantfile` that causes this crash?

**Comment by atombender** [comment]
Our `Vagrantfile` is a little obfuscated as it has stuff that's configured from our deployment environment, but here goes.

```ruby
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

require_relative '../lib/monkey/vagrant/settings'

Settings = Monkey::Vagrant::Settings

Vagrant.require_version '>= 1.7.2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.forward_agent = true

  if Settings.using_vmware?
    config.ssh.private_key_path = File.expand_path('../keys/ssh-vagrant.key', __FILE__)
  end

  config.vm.define Settings::NAME do |node|
    node.vm.box = Settings::BOX_NAME
    Settings::PORT_MAPPINGS.each do |(guest, host)|
      if guest != 22
        node.vm.network 'forwarded_port', guest: guest, host: host
      end
    end
    node.vm.network 'private_network', ip: Settings::IP
    node.vm.hostname = Settings::FQDN

    if Settings.using_vmware?
      node.vm.provider 'vmware_fusion' do |vmware|
        vmware.memory = 4096
        vmware.gui = false
        vmware.name = Settings::NAME
      end
    else
      node.vm.provider 'virtualbox' do |virtualbox|
        virtualbox.memory = 4096
        virtualbox.gui = false
        virtualbox.name = Settings::NAME
      end
    end

    ::Monkey::Vagrant.mount_manifest['apps'].each do |name, path|
      if File.exist?(path)
        if Settings.using_vmware?
          config.vm.synced_folder path, "/srv/#{name}/dev",
            owner: name
            # FIXME: Disabled due to Vagrant bug (https://github.com/mitchellh/vagrant/issues/5472)
            #, group: 'app'
        else
          config.vm.synced_folder path, "/srv/#{name}/dev", owner: name, group: 'app'
        end
      else
        puts "\e[31m==> Warning: Not mounting app #{name} as #{path} does not exist.\e[0m"
      end
    end
  end
end
```

**Comment by phinze** [comment]
@atombender great, thanks for this.

The issue seems to be in fetching a proper host-accessible IP address from the underlying VMware Fusion tooling. This is a task we've had many issues with - and there are several different workarounds in our plugin's code with attempts to handle the various anomalous behaviors we've seen from our IP lookup strategies.

Two more questions for you:

 * Does this happen consistently or sporadically for you?
 * Can you [gist](https://gist.github.com) the [debug](http://docs.vagrantup.com/v2/other/debugging.html) output from a run where you hit the error?

**Comment by atombender** [comment]
It happens only sporadically. I'll enable debug logging and hope it happens again.

**Comment by mitchellh** [comment]
Fixed
