### ISSUE TITLE
Running vagrant 16.5 without arguments generates "vagrant-share can't be installed without vagrant-login" error

### ISSUE THREAD

**Issue by Clueless76** [mitchellh/vagrant#5535]
I'm coming up with a problem which was exactly described in this  [entry #4923](https://github.com/mitchellh/vagrant/issues/4923) but the solution seems not to work on my machine.

I have installed Ubuntu 14.04 for a x86_64 machine, got the vagrant version 1.6.5 but if I type `vagrant` or `vagrant help` I got following error message:

```text
/home/pkotz/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:8:in `rescue in <encoded>': vagrant-share can't be installed without vagrant login (RuntimeError)
	from /home/pkotz/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:5:in `<encoded>'
	from /home/pkotz/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:16:in `RGLoader_load'
	from /home/pkotz/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:16:in `<top (required)>'
	from /home/pkotz/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share.rb:23:in `require'
	from /home/pkotz/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share.rb:23:in `block in <class:Plugin>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:75:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:75:in `block (2 levels) in help'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/registry.rb:48:in `block in each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/registry.rb:47:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/registry.rb:47:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:69:in `block in help'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/optparse.rb:885:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:57:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:57:in `help'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:32:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:292:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:174:in `<main>'
```

After reinstalling the vagrant-share plugin the problem wasn't solved.

Further I found out that I have two places where the vagrant share plugin was installed:

```text
pkotz@schlappi:~/projects/ota/OTA-Cucumber/vagrant$ ls -1 /opt/vagrant/embedded/gems/gems/
akami-1.2.2
builder-3.2.2
bundler-1.6.6
celluloid-0.15.2
childprocess-0.5.3
erubis-2.7.0
ffi-1.9.3
gssapi-1.0.3
gyoku-1.1.1
hashicorp-checkpoint-0.1.4
httpclient-2.4.0
httpi-0.9.7
i18n-0.6.11
listen-2.7.9
little-plugger-1.1.3
log4r-1.1.10
logging-1.8.2
mime-types-1.25.1
mini_portile-0.6.0
multi_json-1.10.1
net-scp-1.1.2
net-ssh-2.9.1
nokogiri-1.6.3.1
nori-1.1.5
rack-1.5.2
rb-fsevent-0.9.4
rb-inotify-0.9.5
rb-kqueue-0.2.3
rest-client-1.6.8
rubyntlm-0.1.1
savon-0.9.5
timers-1.1.0
uuidtools-2.1.5
vagrant-1.6.5
vagrant-login-1.0.1
vagrant-share-1.1.1
wasabi-1.0.0
wdm-0.1.0
winrm-1.1.3
```

Here I could see that the vagrant share version was not the 1.1.3.

Lookin in this file, vagrant-share 1.1.3 could be found:

```text
pkotz@schlappi:~$ ls /home/pkotz/.vagrant.d/gems/gems
childprocess-0.5.5  ffi-1.9.8  json-1.8.2  multi_json-1.11.0  net-ssh-2.9.2  rdoc-4.2.0  vagrant-proxyconf-1.5.0  vagrant-share-1.1.3
```

So I tried to (un) install the two plugins but it looks that they are stored on different places:

```text
pkotz@schlappi:~$ vagrant plugin install vagrant-login
Installing the 'vagrant-login' plugin. This can take a few minutes...
Installed the plugin 'vagrant-login (1.0.1)'!
pkotz@schlappi:~$ vagrant plugin install vagrant-share
Installing the 'vagrant-share' plugin. This can take a few minutes...
Installed the plugin 'vagrant-share (1.1.3)'!
```

Does anybody has an idea what's happening on my machine? Is this an Ubuntu issue?

**Comment by sethvargo** [comment]
Hi @Clueless76 

I am sorry you are having issues with Vagrant. Can we try the following debug steps:

1. Completely uninstall Vagrant:

        ```text
        rm -rf /opt/vagrant
        rm -rf ~/.vagrant.d
        ```

2. Download the latest version of the official Vagrant installer:

        http://www.vagrantup.com/downloads.html

3. See if the issue persists.

**Comment by leorochael** [comment]
Had the same issue running Vagrant 1:1.6.5 from http://www.vagrantup.com/downloads.html on Ubuntu on 14.04.

Upgraded to 1:1.7.2 and the issue was fixed. Erasing `~/.vagrant.d` wasn't needed in my case.

**Comment by Clueless76** [comment]
Ok, thanks, this solution was working for the time now. I want to mention that the version 1.6.5 was working when it was fresh installed but I missed the event when it was broken.
