### ISSUE TITLE
Missing CLI arguments generate stack trace

### ISSUE THREAD

**Issue by mbrodala** [mitchellh/vagrant#5550]
If you fail to provide a required CLI argument, a stack trace is shown:

```
$ vagrant provision --provision-with
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/command.rb:59:in `parse_options': missing argument: --provision-with (OptionParser::MissingArgument)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/provision/command.rb:24:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:301:in`cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/bin/vagrant:174:in `<main>'
```

I think this should be handled and a cleaner error be shown. Quoting [the docs](https://docs.vagrantup.com/v2/plugins/development-basics.html):

> Vagrant has always strongly believed that if a user sees a stack trace, it is a bug.

**Comment by sethvargo** [comment]
Thank you for reporting!

**Comment by mitchellh** [comment]
Fixed
