### ISSUE TITLE
Push local-exec dies with "Text file busy (Errno::ETXTBSY)"

### ISSUE THREAD

**Issue by jfly** [mitchellh/vagrant#5695]
I'm not doing anything special at all. Here's the relevant config from my Vagrantfile:

```ruby
  config.push.define "staging", strategy: "local-exec" do |push|
    push.inline = "echo hello world"
  end
```

```bash
~/gitting/worldcubeassociation.org @kaladin> vagrant push staging
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/safe_exec.rb:23:in `exec': Text file busy - /tmp/vagrant-local-exec-script20150507-14222-12qbdhw.sh (Errno::ETXTBSY)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/safe_exec.rb:23:in `exec'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/local-exec/push.rb:42:in `execute!'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/local-exec/push.rb:37:in `execute_script!'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/local-exec/push.rb:25:in `execute_inline!'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/pushes/local-exec/push.rb:12:in `push'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:567:in `push'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/push/command.rb:28:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
~/gitting/worldcubeassociation.org @kaladin> 
```

I dug into the code, and discovered that [plugins/pushes/local-exec/push.rb](https://github.com/mitchellh/vagrant/blob/master/plugins/pushes/local-exec/push.rb#L20) very clearly creates a Tempfile, but doesn't close it before trying to execute it. Things work fine with the following diff:

```diff
~/tmp/vagrant @kaladin> git diff
diff --git a/plugins/pushes/local-exec/push.rb b/plugins/pushes/local-exec/push.rb
index bad308f..718b1ab 100644
--- a/plugins/pushes/local-exec/push.rb
+++ b/plugins/pushes/local-exec/push.rb
@@ -20,6 +20,7 @@ module VagrantPlugins
         script = Tempfile.new(["vagrant-local-exec-script", ".sh"])
         script.write(inline)
         script.rewind
+        script.close
 
         execute_script!(script.path)
       ensure
~/tmp/vagrant @kaladin> 
```

Tada!

```bash
~/gitting/worldcubeassociation.org @kaladin> vagrant push staging
hello world
~/gitting/worldcubeassociation.org @kaladin> 
```

This seems like a straightforward fix to me. I haven't looked into behavior on Windows or Macs. I can submit a PR if desired.

**Comment by jgrowl** [comment]
I just ran into the same error on ubuntu using Vagrant 1.7.2 . Using inline seems broke, but calling an external script works fine.

**Comment by mitchellh** [comment]
Fixed!

**Comment by mitchellh** [comment]
Thanks for the debugging, it helped immensely to fix this.

**Comment by jfly** [comment]
You're welcome! :( about the 2 months to fix it, though.
