### ISSUE TITLE
Failure to install plugin: Failed to build gem native extension.

### ISSUE THREAD

**Issue by phinze** [mitchellh/vagrant#5746]
We've seen this once or twice in HashiCorp support, and @videlalvaro had a good idea to make and close an issue for Google-ability.

There's a bug in the current version of Bundler that's embedded in Vagrant that can cause Ruby's built-in gems to be fetched as dependencies during a gem install.

On machines where a gcc build toolchain is not available, this causes an error building the native extensions of the `json` gem.

Like this:

```
An error occurred while installing json (1.8.2), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.2'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
```

This can happen with either plugin install command:

```
vagrant plugin install vagrant-vmware-fusion
vagrant plugin install vagrant-vmware-workstation
```

You can tell it's a bug in Bundler, because the Vagrant VMware plugin gems have no dependencies.

Luckily there's a relatively simple workaround: download the gem to disk and install it from the local file.

The HashiCorp-published Vagrant plugins are available here: http://gems.hashicorp.com/ under http://gems.hashicorp.com/gems/

Once you've downloaded the appropriate gem, simply reference its path in the install command. For example:

```
vagrant plugin install ~/Downloads/vagrant-vmware-fusion-3.2.6.gem
```

The plugin should install successfully and you can go on with your life. :grinning: 

I'm going to close the issue right away, but feel free to respond on the thread if you have any further issues or questions. As always, you can also write in to HashiCorp Support for VMware plugin issues.

**Comment by bdp99** [comment]
Hi!
I think things remains the same.
I have the same error trying to install Landrush

```
homer@SIMPSON:~$ vagrant plugin install landrush
Installing the 'landrush' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing hitimes (1.2.3), and Bundler cannot continue.
Make sure that `gem install hitimes -v '1.2.3'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb
checking for clock_gettime() in -lrt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/ruby
	--with-rtlib
	--without-rtlib
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:519:in `try_link0'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:714:in `try_func'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:944:in `block in have_library'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:889:in `block in checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:888:in `checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:939:in `have_library'
	from extconf.rb:10:in `<main>'


Gem files will remain installed in /home/homer/.vagrant.d/gems/gems/hitimes-1.2.3 for inspection.
Results logged to /home/homer/.vagrant.d/gems/gems/hitimes-1.2.3/ext/hitimes/c/gem_make.out
```

And then, despite I try to do something like you suggested I reach the same error

```
homer@SIMPSON:~$ vagrant plugin install /home/homer/Downloads/landrush-0.18.0.gem
Installing the '/home/homer/Downloads/landrush-0.18.0.gem' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:337:in `initialize': Permission denied - /home/homer/.vagrant.d/gems/gems/hitimes-1.2.3/CONTRIBUTING.md (Errno::EACCES)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:337:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:337:in `block (2 levels) in extract_tar_gz'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package/tar_reader.rb:64:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:330:in `block in extract_tar_gz'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:409:in `block in open_tar_gz'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:406:in `wrap'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:406:in `open_tar_gz'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:329:in `extract_tar_gz'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:313:in `block (2 levels) in extract_files'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package/tar_reader.rb:64:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:310:in `block in extract_files'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:307:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/package.rb:307:in `extract_files'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:727:in `extract_files'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:225:in `install'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:379:in `block in install'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `each_with_index'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:124:in `block in install_local'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:284:in `block in with_isolated_gem'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/user_interaction.rb:40:in `use_ui'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:283:in `with_isolated_gem'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:121:in `install_local'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/manager.rb:47:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

```
homer@SIMPSON:~$ sudo vagrant plugin install /home/homer/Downloads/landrush-0.18.0.gem
[sudo] password for homer: 
Installing the '/home/homer/Downloads/landrush-0.18.0.gem' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/ext/builder.rb:62:in `run': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

    /opt/vagrant/embedded/bin/ruby extconf.rb
checking for clock_gettime() in -lrt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/ruby
	--with-rtlib
	--without-rtlib
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:519:in `try_link0'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:714:in `try_func'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:944:in `block in have_library'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:889:in `block in checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:888:in `checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:939:in `have_library'
	from extconf.rb:10:in `<main>'


Gem files will remain installed in /home/homer/.vagrant.d/gems/gems/hitimes-1.2.3 for inspection.
Results logged to /home/homer/.vagrant.d/gems/gems/hitimes-1.2.3/ext/hitimes/c/gem_make.out
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/ext/ext_conf_builder.rb:39:in `block in build'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/tempfile.rb:324:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/ext/ext_conf_builder.rb:19:in `build'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:689:in `block (3 levels) in build_extensions'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:688:in `chdir'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:688:in `block (2 levels) in build_extensions'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:687:in `synchronize'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:687:in `block in build_extensions'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:662:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:662:in `build_extensions'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/installer.rb:227:in `install'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:379:in `block in install'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `each_with_index'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:339:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:124:in `block in install_local'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:284:in `block in with_isolated_gem'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/user_interaction.rb:40:in `use_ui'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:283:in `with_isolated_gem'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:121:in `install_local'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/manager.rb:47:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

**Comment by sethvargo** [comment]
Hi @bdp99 

Please open a new issue. You are experiencing the same error message, but for different reasons :smile:

**Comment by vhosakot** [comment]
I saw the error `Failed to build gem native extension` too on CentOS 7.3 and vagrant 1.8.7.

I resolved it after installing ruby-devel and gcc (`yum -y install ruby-devel gcc`)

**Comment by danielBingham** [comment]
This bug has reared it's head again recently with Vagrant 2.1.1 and the links in the original post for manually downloading the gem are now dead.  Is there another way to work around this bug or are there updated links for manual gem download?

**Comment by jajouka79** [comment]
any fix  for this bug, it makes vagrant completely useless to me

**Comment by xet7** [comment]
On Ubuntu 18.04 server this works for me:
```
sudo su
apt-get install virt-manager build-essential ruby-full ruby-all-dev libvirt-dev
dpkg -i vagrant_2.2.6_x86_64.deb
vagrant plugin install vagrant-libvirt
```

**Comment by xet7** [comment]
So I think it just requires ruby and libvirt development packages.
