### ISSUE TITLE
Receive "A box must be specified." when vagrant up in multi-machine environment

### ISSUE THREAD

**Issue by papalagichen** [mitchellh/vagrant#5799]
vagrant up server    # OK
vagrant halt server  # OK
vagrant up server    # ERROR! A box must be specified.

Third command always fail with error message "A box must be specified."
The only workaround I know is to destroy that machine.
My vagrant version is 1.7.2 run on Mac OS 10.10.

My Vagranfile is:

```ruby
Vagrant.configure(2) do |config|
  config.vm.define "build" do |build|
    config.vm.box = "gitlab/ubuntu-12.04.4-x64-v1"
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 4 
      vb.memory = 2048
    end 
  end 

  config.vm.define "server" do |server|
    config.vm.box = "gitlab/ubuntu-12.04.4-x64-v1"
    config.vm.network "private_network", ip: "172.1.7.2"
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 4 
      vb.memory = 4096
    end 
  end 
end
```

vagrant up server --debug

```
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::ConfigInvalid: There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* A box must be specified.

>
ERROR vagrant: There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* A box must be specified.

ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:18:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

```

**Comment by sethvargo** [comment]
Hi @papalagichen 

I think you want to use `server` in your configuration block:

```ruby
Vagrant.configure(2) do |config|
  config.vm.define "build" do |build|
    build.vm.box = "gitlab/ubuntu-12.04.4-x64-v1"
    build.vm.provider "virtualbox" do |vb|
      vb.cpus = 4 
      vb.memory = 2048
    end 
  end 

  config.vm.define "server" do |server|
    server.vm.box = "gitlab/ubuntu-12.04.4-x64-v1"
    server.vm.network "private_network", ip: "172.1.7.2"
    server.vm.provider "virtualbox" do |vb|
      vb.cpus = 4 
      vb.memory = 4096
    end 
  end 
end
```

**Comment by papalagichen** [comment]
You are correct! Thank you for the answer!

**Comment by sethvargo** [comment]
Hi @papalagichen 

Awesome - I am going to close this issue then. Thanks!
