### ISSUE TITLE
Ansible provisioner fails for VirtualBox provider. Undefined method `end_with?' for nil:NilClass

### ISSUE THREAD

**Issue by LukaszKorzybski** [mitchellh/vagrant#5837]
On Vagrant 1.7.2 I get the following error when running Ansible provisioner for one of my machines:

```
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/ansible/provisioner.rb:137:in `block (2 levels) in setup_inventory_file': undefined method `end_with?' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/ansible/provisioner.rb:132:in `each_pair'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/ansible/provisioner.rb:132:in `block in setup_inventory_file'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/ansible/provisioner.rb:105:in `open'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/ansible/provisioner.rb:105:in `open'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/ansible/provisioner.rb:105:in `setup_inventory_file'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/ansible/provisioner.rb:34:in `provision'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:133:in `run_provisioner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:428:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:121:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:121:in `block in call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:103:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:103:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/lukaszk/.vagrant.d/gems/gems/vagrant-cachier-1.2.0/lib/vagrant-cachier/action/configure_bucket_root.rb:20:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/match_mac_address.rb:16:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/import.rb:32:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by naunga** [comment]
I'm curious: you said you see this on "one of your boxes" implying that this is not a constant error. If this is the case, have you identified a difference between boxes that work and boxes that don't?

**Comment by gildegoma** [comment]
From the reported stack trace, [it fails](https://github.com/mitchellh/vagrant/blob/v1.7.2/plugins/provisioners/ansible/provisioner.rb#L137) when parsing the `ansible.groups` hash.

@LukaszKorzybski Could you please provide a gist of your failing `Vagrantfile` ?

**Comment by LukaszKorzybski** [comment]
I realised that this was my fault as I didn't pass valid group. After I fixed my Vagrantfile the exception didn't occur anymore.

**Comment by gildegoma** [comment]
Thanks for your closing feed-back 👍.

**Comment by adnelson** [comment]
I'm encountering the same error, using vagrant 1.7.4:

```
$ vagrant provision
==> default: Running provisioner: ansible...
/nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/provisioners/ansible/provisioner.rb:154:in `block in setup_inventory_file': undefined method `end_with?' for :local:Symbol (NoMethodError)
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/provisioners/ansible/provisioner.rb:149:in `each_pair'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/provisioners/ansible/provisioner.rb:149:in `setup_inventory_file'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/provisioners/ansible/provisioner.rb:45:in `provision'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:133:in `run_provisioner'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:428:in `hook'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:121:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:121:in `block in call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:103:in `each'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:103:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/provision/command.rb:30:in `block in execute'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/provision/command.rb:29:in `execute'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /nix/store/ksxgi5dbndkjpfsly40qgrbc5b5w46xb-vagrant-1.7.4/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

I'm also trying to use the `ansible.groups = ...` option in the Vagrantfile. The thing is, even if this is an error on my part in how I'm specifying the groups, vagrant should report what that error is, rather than blowing up with a giant indecipherable stack trace.

**Comment by gildegoma** [comment]
Reopening with the idea to improve the config validation of the `groups` option (not urgent though).
