### ISSUE TITLE
Could not find gem 'vagrant-login (>= 0) ruby' error on ubunutu 14.04.2 with vagrant 1.7.2 deb

### ISSUE THREAD

**Issue by ianheggie** [mitchellh/vagrant#5878]
Nearly all commands fail with a bundler error, eg:

```
ianh@abe:~/Downloads$ vagrant
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:368:in `resolve': Could not find gem 'vagrant-login (>= 0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:166:in `start'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:129:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:193:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:132:in `specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:177:in `specs_for'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant.rb:76:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:105:in `<main>'
ianh@abe:~/Downloads$ vagrant --help
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:368:in `resolve': Could not find gem 'vagrant-login (>= 0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:166:in `start'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:129:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:193:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:132:in `specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:177:in `specs_for'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant.rb:76:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:105:in `<main>'
ianh@abe:~/Downloads$ vagrant -v
Vagrant 1.7.2
ianh@abe:~/Downloads$ cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

ianh@abe:~/Downloads$ uname -a
Linux abe.heggie.local 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
ianh@abe:~/Downloads$ $ dpkg -l vagrant
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-================================================================================================
ii  vagrant                                       1:1.7.2                     amd64                       no description given

```

**Comment by ianheggie** [comment]
Note - vagrant 1.6.5 works on my system, so I am using that as a workaround

**Comment by sethvargo** [comment]
Hi @ianheggie 

I am sorry you are having issues with Vagrant. Did you install Vagrant via apt or via the official package installer from vagrantup.com/downloads?

It looks like you may have a plugin conflict - could you please show the output of vagrant plugin list?

**Comment by ianheggie** [comment]
* Downloaded https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
* purged the old vagrant 
* confirmed /opt/vagrant had been removed
* sudo dpkg -i vagrant_1.7.2_x86_64.deb

I could not display a package list because `vagrant plugin list`  also crashed

**Comment by sethvargo** [comment]
@ianheggie can you try purging (or just renaming) `~/.vagrant.d` please?

**Comment by ianheggie** [comment]
with the older vagrant it will list the plugins:
```
ianh@abe:/opt/vagrant$ vagrant plugin list
deep_merge (1.0.1)
vagrant-aws (0.6.0)
vagrant-bindfs (0.3.2)
  - Version Constraint: 0.3.2
vagrant-digitalocean (0.7.4)
vagrant-login (1.0.1)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.3)
vagrant-vbguest (0.10.0)
ianh@abe:/opt/vagrant$ 
```
I will try moving .vagrant.d, deinistalling 1.6.5 and retrying 1.7.2

**Comment by ianheggie** [comment]
Thanks for your prompt help!

I am waiting for trusty64 to download - but so far it looks good (its got past where it previously failed) - I forgot that plugins don't live in /opt/vagrant

I will log an issue against the plugin if they haven't got a more recent fix
