### ISSUE TITLE
1.7.3 cannot provision from salt

### ISSUE THREAD

**Issue by cedricpim** [mitchellh/vagrant#5939]
Trying to provision from salt and following error is appearing:

Error Output: 
````
/opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/salt/provisioner.rb:154:in `%': can't convert Vagrant::Config::V2::DummyConfig to Array (Vagrant::Config::V2::DummyConfig#to_ary gives Vagrant::Config::V2::DummyConfig) (TypeError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/salt/provisioner.rb:154:in `bootstrap_options'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/salt/provisioner.rb:236:in `run_bootstrap_script'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/salt/provisioner.rb:9:in `provision'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/provision.rb:133:in `run_provisioner'
````
Just changed to 1.7.2 and everything went smooth.
Vagrant file:
````
  ## For masterless, mount your salt and pillar file root
  config.vm.synced_folder "saltstack/salt/", "/srv/salt/", nfs: true
  config.vm.synced_folder "saltstack/pillar/", "/srv/pillar/", nfs: true

  ## Use all the defaults:
  config.vm.provision :salt do |salt|
    salt.minion_config = "saltstack/etc/minion"
    salt.run_highstate = true
    salt.verbose = true
  end
````

**Comment by wingedkiwi** [comment]
Same issue for me!

**Comment by cedricpim** [comment]
Seems to be the issue mentioned (with provided solution) at #5936.
