### ISSUE TITLE
vagrant connect not working

### ISSUE THREAD

**Issue by nfloersch** [mitchellh/vagrant#5944]
I had this problem in Vagrant 1.7.2, and just updated to v1.7.3... same problem. Using "vagrant connect" on my Mac never gets to even try connecting...

I have OS X 10.10.4.

I have done various complete removals of Vagrant and use the uninstall as well as manual instructions from support. My VM provider is VMWare Fusion and this plugin has been re-installed, re-built from scratch numerous times, including just now after the v1.7.3 install.

I have tried using the standard ruby install (v2.0.0) and homebrew's latest version (v2.2.2). No difference in result.

I have deleted and forced it to re-download the connect-VM ... so it doesn't make sense it would be an error with the VM.

```
Genesis:~ zoontf$ vagrant connect gXXXXs-sXXXXXk-3XX0
==> connect: Loading share 'gXXXXs-sXXXXXk-3XX0'...
==> connect: Connecting to: gXXXXs-sXXXXXk-3XX0
==> connect: Checking for proxy VM updates...
    connect: Already up-to-date.
==> connect: Starting a VM for a static connect IP. This will take a few moments.
    connect: Cloning VMware VM: 'hashicorp/connect-vm'. This can take some time...
==> connect: Deleting the VM...
/Volumes/StompingGrounds/Users/ZoontF/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.9/lib/vagrant-vmware-fusion/action_farm.rb:1098:in `call': undefined method `basename' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Volumes/StompingGrounds/Users/ZoontF/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.9/lib/vagrant-vmware-fusion/action_farm.rb:482:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Volumes/StompingGrounds/Users/ZoontF/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.9/lib/vagrant-vmware-fusion/action_farm.rb:1249:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Volumes/StompingGrounds/Users/ZoontF/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.9/lib/vagrant-vmware-fusion/action_farm.rb:99:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Volumes/StompingGrounds/Users/ZoontF/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.9/lib/vagrant-vmware-fusion/action_farm.rb:273:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /Volumes/StompingGrounds/Users/ZoontF/.vagrant.d/gems/gems/vagrant-vmware-fusion-3.2.9/lib/vagrant-vmware-fusion/action_farm.rb:160:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:906:in `block in execute_connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:526:in `block in with_ui'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:522:in `synchronize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:522:in `with_ui'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:905:in `execute_connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:818:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/bin/vagrant:174:in `<main>'

**Comment by sethvargo** [comment]
Hi @nfloersch 

Thank you for opening an issue. Even though you opened the issue first, let's track #5945 for this. I saw that issue first and the author has included the full debug output which is helpful for us getting this fixed. Nonetheless, thank you for using Vagrant!
