### ISSUE TITLE
New puppet 'environments' functionality can't merge configs

### ISSUE THREAD

**Issue by kcormier** [mitchellh/vagrant#5958]
Sample Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

def build_box( config, name, ip )
  config.vm.hostname = name
  config.vm.network 'private_network', ip: "#{ip}"

  config.vm.provision 'puppet', type: 'puppet' do |puppet|
    puppet.facter = { 'class' => name }
  end
end

Vagrant.configure(2) do |config|
  config.vm.box = "base"

  config.vm.provision 'puppet', type: 'puppet' do |puppet|
    puppet.manifests_path    = 'puppet/manifests'
    puppet.module_path       = 'puppet/modules'
    puppet.manifest_file     = 'default.pp'
    puppet.hiera_config_path = 'config/hiera.yaml'
    puppet.working_directory = '/vagrant'
    puppet.synced_folder_type = 'rsync'
  end

  config.vm.define 'test' do | test |
    build_box( test, 'test', '192.168.33.10' )
  end
end
```

Broken in 1.7.3
```
Kevin:test kcormier$ vagrant status
/opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/puppet/config/puppet.rb:55:in `merge': no implicit conversion of Object into Hash (TypeError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/puppet/config/puppet.rb:55:in `block in merge'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/puppet/config/puppet.rb:53:in `tap'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/puppet/config/puppet.rb:53:in `merge'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/kernel_v2/config/vm.rb:145:in `block (2 levels) in merge'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/kernel_v2/config/vm.rb:140:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/kernel_v2/config/vm.rb:140:in `block in merge'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/kernel_v2/config/vm.rb:85:in `tap'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/kernel_v2/config/vm.rb:85:in `merge'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/config/v2/loader.rb:76:in `block in merge'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/config/v2/loader.rb:72:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/config/v2/loader.rb:72:in `merge'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/config/loader.rb:149:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/config/loader.rb:97:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/config/loader.rb:97:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/config/loader.rb:94:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/config/loader.rb:94:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/vagrantfile.rb:153:in `machine_config'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/vagrantfile.rb:45:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/environment.rb:612:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:201:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:200:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:200:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/commands/status/command.rb:20:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/bin/vagrant:174:in `<main>'
```

Testing and working in 1.7.2
```
Current machine states:

test                      not created (parallels)

The environment has not yet been created. Run `vagrant up` to
create the environment. If a machine is not created, only the
default provider will be shown. So if a provider is not listed,
then the machine is not created for that environment.
```

Tested on OSX 10.10.4

**Comment by kcormier** [comment]
Broken by merged PR #5601

**Comment by jhoblitt** [comment]
I've hit this upgrading from 1.7.2 -> 1.7.3 as well.  It's a major bummer as 1.7.3 is needed to get fedora working with beaker.

**Comment by mitchellh** [comment]
Fixed
