### ISSUE TITLE
chef-client cleanup fails with "" (empty) as node name

### ISSUE THREAD

**Issue by MartinSGill** [mitchellh/vagrant#6005]
When using the chef-client to provision a VM, teardown fails when specifying delete_node and delete_client.

Windows Client & Guest, Winrm connector, virtuabox VM.
Expecting node name to be the windows hostname; this is correctly used for registering the client.

Provision block:
```ruby
  config.vm.provision "chef_client" do |chef|
    chef.chef_server_url = "**REMOVED**"
    chef.validation_key_path = "chef-validator.pem"
    chef.encrypted_data_bag_secret_key_path = "customer_secret"
    chef.client_key_path = "client.pem"
    chef.run_list = [**REMOVED**]
    chef.json = JSON.parse(File.read('first_boot.json'))
    chef.file_cache_path = "C:/chef/cache"
    chef.environment = "development"

    chef.validation_client_name = "chef-validator"

    # Cleanup - Called on teardown
    chef.delete_node = true
    chef.delete_client = true
  end
```

Output

```
==> default: Deleting client "" from Chef server...
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/subprocess.rb:28:in `block in initialize': undefined method
`encode' for nil:NilClass (NoMethodError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/subprocess.rb:28:in `map'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/subprocess.rb:28:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/subprocess.rb:22:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/subprocess.rb:22:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/chef/provisioner/chef_client.rb:133:in `blo
ck in delete_from_chef_server'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/shared_helpers.rb:20:in `block in global_lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/shared_helpers.rb:19:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/shared_helpers.rb:19:in `global_lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/chef/provisioner/chef_client.rb:131:in `del
ete_from_chef_server'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/chef/provisioner/chef_client.rb:34:in `clea
nup'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/provisioner_cleanup.rb:37:in `block i
n do_cleanup'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/provisioner_cleanup.rb:33:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/provisioner_cleanup.rb:33:in `do_clea
nup'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/provisioner_cleanup.rb:26:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/providers/virtualbox/action/destroy_unused_network_inter
faces.rb:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:i
n `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/providers/virtualbox/action/destroy.rb:14:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/providers/virtualbox/action/forced_halt.rb:20:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/providers/virtualbox/action/discard_state.rb:15:in `call
'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/providers/virtualbox/action/check_accessible.rb:18:in `c
all'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `c
all'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/env_set.rb:19:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/providers/virtualbox/action/check_accessible.rb:18:in `c
all'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `c
all'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/machine.rb:178:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/commands/destroy/command.rb:31:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vm
s'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:220:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/commands/destroy/command.rb:30:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/bin/vagrant:174:in `<main>'
```

**Comment by MartinSGill** [comment]
Here's the debug ouput, although I don't think it really adds anything.
https://gist.github.com/MartinSGill/f8662c0ac29b9b4b1970
