### ISSUE TITLE
VMware Windows VM hangs on Setting hostname/Configuring network adapters

### ISSUE THREAD

**Issue by aem** [mitchellh/vagrant#6040]
I have a custom VMware box (Atlas-hosted, amarkon/windows-7-ult-n-x64) that I've been using with Kitchen and Chef to create an infrastructure VM with no problems for the better part of two weeks. Last Thursday, when I tried to bring up the box (after no configuration changes other than updates to my Chef cookbook), the process hung on "Configuring network adapters within the VM..." for about 10 minutes before erroring out:
```
$ kitchen converge -l=debug
-----> Starting Kitchen (v1.4.0)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.16s)
D      [Vagrant command] BEGIN (vagrant plugin list)
D      [Vagrant command] END (0m0.70s)
D      Berksfile found at /Users/amarkon/Documents/workspace/chef/site-cookbooks/infinio_win_installer/Berksfile, loading Berkshelf
D      Berkshelf 3.2.4 library loaded
D      Winrm Transport requested, loading WinRM::Transport gem (~> 1.0)
D      WinRM::Transport 1.0.0 library loaded
-----> Creating <default-amarkon-windows-7-ult-n-x64>...
D      <default-amarkon-windows-7-ult-n-x64> is synchronizing on Kitchen::Driver::Vagrant#create
D      <default-amarkon-windows-7-ult-n-x64> is messaging Kitchen::Driver::Vagrant#create
D      Creating Vagrantfile for <default-amarkon-windows-7-ult-n-x64> (/Users/amarkon/Documents/workspace/chef/site-cookbooks/infinio_win_installer/.kitchen/kitchen-vagrant/kitchen-infinio_win_installer-default-amarkon-windows-7-ult-n-x64/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
D        c.vm.box = "amarkon/windows-7-ult-n-x64"
D        c.vm.hostname = "default-amarkon-windows-7-ult-n-x64"
D        c.vm.communicator = "winrm"
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.provider :vmware_fusion do |p|
D        end
D      end
D      ------------
D      [Vagrant command] BEGIN (vagrant up --no-provision --provider vmware_fusion)
       Bringing machine 'default' up with 'vmware_fusion' provider...
       ==> default: Cloning VMware VM: 'amarkon/windows-7-ult-n-x64'. This can take some time...
       ==> default: Checking if box 'amarkon/windows-7-ult-n-x64' is up to date...
       ==> default: Verifying vmnet devices are healthy...
       ==> default: Preparing network adapters...
       ==> default: Starting the VMware VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
       ==> default: Machine booted and ready!
       ==> default: Forwarding ports...
           default: -- 5985 => 55985
           default: -- 22 => 2222
       ==> default: Setting hostname...
       ==> default: Configuring network adapters within the VM...
STDERR: Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
---- End output of vagrant up --no-provision --provider vmware_fusion ----
Ran vagrant up --no-provision --provider vmware_fusion returned 1
D      ------Backtrace-------
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/shell_out.rb:73:in `rescue in run_command'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/shell_out.rb:61:in `run_command'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.18.0/lib/kitchen/driver/vagrant.rb:318:in `run_command'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.18.0/lib/kitchen/driver/vagrant.rb:302:in `run'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.18.0/lib/kitchen/driver/vagrant.rb:348:in `run_vagrant_up'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-vagrant-0.18.0/lib/kitchen/driver/vagrant.rb:88:in `create'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:424:in `public_send'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:424:in `block in perform_action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:485:in `call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:485:in `block in synchronize_or_call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:483:in `synchronize'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:483:in `synchronize_or_call'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:453:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:452:in `action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:424:in `perform_action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:352:in `create_action'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `each'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:340:in `transition_to'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:138:in `converge'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `public_send'
D      /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D      ----------------------
```
Running `$ vagrant reload` yields a `==> default: VM not created. Moving on...` but a `$ vmrun list` shows that the virtual machine has been created and running. Neither a reboot nor removing and re-adding the box remedied the problem. I also tried rebuilding the box with no success.

**Comment by sethvargo** [comment]
Hi @aem 

Are you able to reproduce this issue without Test Kitchen? Do you have a Vagrantfile? Thanks!

**Comment by aem** [comment]
@sethvargo Here's the Vagrantfile that Test Kitchen generated:
```
Vagrant.configure("2") do |c|                                                                                                                                                                                                                                                                                             
    c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")                                                                                                                                                                                                                                                 
    c.vm.box = "amarkon/windows-7-ult-n-x64"                                                                                                                                                                                                                                                                                        
    c.vm.communicator = "winrm"                                                                                                                                                                                                                                                                                             
    c.vm.synced_folder ".", "/vagrant", disabled: true                                                                                                                                                                                                                                                                      
    c.vm.provider :vmware_fusion do |p|                                                                                                                                                                                                                                                                                     
    end                                                                                                                                                                                                                                                                                                                     
  end 
```
Running `$ vagrant up --no-provision --provider vmware_fusion` (the same command issued by Test Kitchen) yields the following:
```
$ vagrant up --no-provision --provider vmware_fusion
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'amarkon/windows-7-ult-n-x64'. This can take some time...
==> default: Checking if box 'amarkon/windows-7-ult-n-x64' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 5985 => 55985
    default: -- 22 => 2222
==> default: Configuring network adapters within the VM...
==> default: Configuring secondary network adapters through VMware 
==> default: on Windows is not yet supported. You will need to manually
==> default: configure the network adapter.
==> default: Machine not provisioning because `--no-provision` is specified.
```

**Comment by sethvargo** [comment]
@aem that looks like a problem with the box maybe - you can see the output here:

```
==> default: Configuring secondary network adapters through VMware 
==> default: on Windows is not yet supported. You will need to manually
==> default: configure the network adapter.
```

**Comment by aem** [comment]
@sethvargo yeah, I noticed that, but what configuration change would have caused that? It was working and then suddenly stopped working without the base box changing.

**Comment by aem** [comment]
@sethvargo I rebuilt the box from scratch (recreated the VM from the Windows ISO this time instead of just regenerating the .box file) and now it's working. Not sure what could have happened to the base box in between those too usages but it's working now

**Comment by aem** [comment]
@sethvargo I just ran into the issue again. I've discovered that the process works fine when I do a `vagrant add ~/Desktop/box.box --name=windows7` and then run `kitchen converge` but when the box gets added from the remote source during `kitchen converge` the `vagrant up` command will fail with 100% reproducibility. Is this something that we think is a Vagrant issue or should I move this over to Test Kitchen's issue tracker?

**Comment by aem** [comment]
This is a bug in test-kitchen, not Vagrant. Thanks for enduring my nonsense :)

**Comment by PowerKiKi** [comment]
@aem I seem to have similar symptoms but couldn't find any follow up in test-kitchen. Would you mind sharing more about how you solved your problems ? did you open a issue on another project ?

**Comment by aem** [comment]
@PowerKiKi I haven't touched this project in a while and unfortunately no longer have access to the repo I was working on, but the central issue was that while test-kitchen recognized the OS of the vagrant box as Windows, the shell was set as bourne rather than WinRM or Powershell. You can confirm the detected shell by running a `kitchen diagnose --all`. If I remember correctly, by setting a vm's `communicator` (Documentation available here: https://docs.chef.io/config_yml_kitchen.html) you should be able to set the shell to WinRM manually.

**Comment by PowerKiKi** [comment]
@aem thanks your reply. It seems I have a very different issue after all. My host is OSX and guest is Ubuntu. Anyway I worked around that by going back to VirtualBox which seems much more stable for me.
