### ISSUE TITLE
File name too long while using checksums

### ISSUE THREAD

**Issue by nik9000** [mitchellh/vagrant#6095]
I tried to create a box like so:
```Vagrantfile
Vagrant.configure(2) do |config|
  config.vm.define "fedora-22", autostart: false do |config|
    # Fedora hosts their own 'cloud' images that aren't in Vagrant's Atlas but
    # we can still fetch them. We have the power!
    config.vm.box = "https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box"
    config.vm.box_download_checksum = "2513342f70c00310e161a110e34973a133691fedd866859e65904fa056ae7a0c"
    config.vm.box_download_checksum_type = "sha256"
  end
end
```

But bringing it up fails:
```bash
$ vagrant up fedora-22
Bringing machine 'fedora-22' up with 'virtualbox' provider...
==> fedora-22: Box 'https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box' could not be found. Attempting to find and install...
    fedora-22: Box Provider: virtualbox
    fedora-22: Box Version: >= 0
==> fedora-22: Box file was not detected as metadata. Adding it directly...
==> fedora-22: Adding box 'https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box' (v0) for provider: virtualbox
    fedora-22: Downloading: https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box
    fedora-22: Calculating and comparing box checksum...
/opt/vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': File name too long - /Users/manybubbles/.vagrant.d/boxes/https:-VAGRANTSLASH--VAGRANTSLASH-download.fedoraproject.org-VAGRANTSLASH-pub-VAGRANTSLASH-fedora-VAGRANTSLASH-linux-VAGRANTSLASH-releases-VAGRANTSLASH-22-VAGRANTSLASH-Cloud-VAGRANTSLASH-x86_64-VAGRANTSLASH-Images-VAGRANTSLASH-Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box (Errno::ENAMETOOLONG)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:203:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/pathname.rb:559:in `mkpath'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:158:in `block (3 levels) in add'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:439:in `with_temp_dir'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:131:in `block (2 levels) in add'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:439:in `with_temp_dir'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:112:in `block in add'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:426:in `block in with_collection_lock'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:425:in `with_collection_lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/box_collection.rb:101:in `add'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_add.rb:340:in `box_add'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_add.rb:132:in `add_direct'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_add.rb:106:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:82:in `handle_box'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

My versions:
```bash
$ vagrant --version
Vagrant 1.7.4
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E46
```

**Comment by nik9000** [comment]
It looks like you can work around this by setting by replacing what I had for `config.vm.box` with:
```
    config.vm.box = "fedora/22"
    config.vm.box_url = "https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box"
```

**Comment by sethvargo** [comment]
Hi @nik9000 

Thank you for opening an issue. I looked into this, and, unfortunately, there is no safe way to detect if the user provided a URL vs a box name to the box parameter. You are correct that the proper behavior is to use `box_url`. I will update the docs to make this clearer. Thanks! 😄
