### ISSUE TITLE
vagrant share --ssh crashes with passwords < 4 characters

### ISSUE THREAD

**Issue by MSch** [mitchellh/vagrant#6197]
```
/opt/vagrant/embedded/gems/gems/vagrant-share-1.1.4/lib/vagrant-share/activate.rb:488:in `export': OpenSSL requires passwords to be at least four characters long (OpenSSL::OpenSSLError)
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.4/lib/vagrant-share/activate.rb:488:in `generate_keypair'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.4/lib/vagrant-share/activate.rb:1307:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.4/lib/vagrant-share/activate.rb:1178:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

**Comment by sethvargo** [comment]
Hi @MSch 

That error is coming directly from OpenSSL, not Vagrant. OpenSSL requires a password of more than 4 characters. What could Vagrant do to make this better?

**Comment by MSch** [comment]
I was thinking checking whether the password is > 3 characters, printing "password must be at least four characters long" and prompting me for the password again if not would be nicer.

**Comment by sethvargo** [comment]
Fixed upstream (needs a release though)
