### ISSUE TITLE
Vagrant core dump when invoked from removed directory

### ISSUE THREAD

**Issue by jperville** [mitchellh/vagrant#6275]
I made Vagrant (version 1.7.2) crash while trying to run 'vagrant global-status' from a directory that I had removed from another terminal.

```sh
jp440p:~ $ mkdir -p ~/xxx && ~/xxx 
jp440p:xxx $ vagrant global-status
id       name      provider   state   directory                                                                                                       
------------------------------------------------------------------------------------------------------------------------------------------------------
35ee822  admin     virtualbox saved   /home/julien/RubymineProjects/dev-vm                                                                            
3ac35ea  backends  virtualbox saved   /home/julien/RubymineProjects/dev-vm                                                                            
856af1a  compute-1 virtualbox saved   /home/julien/RubymineProjects/dev-vm                                                                            
f47c2f7  default   virtualbox running /home/julien/RubymineProjects/cookbooks/pm-docker/.kitchen/kitchen-vagrant/kitchen-pm-docker-docker-ubuntu-1404 
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
jp440p:xxx $ rm -rf ../xxx
jp440p:xxx $ vagrant global-status
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

malloc: ../.././builtins/../.././builtins/cd.def:626: assertion botched
free: start and end chunk sizes differ
Aborting.../usr/bin/vagrant: line 5: 22577 Aborted                 (core dumped) /opt/vagrant/bin/vagrant "$@"
jp440p:xxx $ 
```

**Comment by sethvargo** [comment]
Hi @jperville 

Thank you for opening an issue. Unfortunately I do not think we can fix this issue in Vagrant. This issue is 100% reproducible with Ruby alone:

```
(session a): mkdir -p ~/xxx && ~/xxx 
(session b): rm -rf ~/xxx
(session a): irb
/Users/sethvargo/.gem/ruby/2.1.6/gems/pry-0.10.1/lib/pry.rb:117:in `pwd': No such file or directory - getcwd (Errno::ENOENT)
	from /Users/sethvargo/.gem/ruby/2.1.6/gems/pry-0.10.1/lib/pry.rb:117:in `<class:Pry>'
	from /Users/sethvargo/.gem/ruby/2.1.6/gems/pry-0.10.1/lib/pry.rb:12:in `<top (required)>'
	from /Users/sethvargo/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sethvargo/.rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sethvargo/.gem/ruby/2.1.6/gems/pry-0.10.1/bin/pry:9:in `<top (required)>'
	from /Users/sethvargo/.gem/ruby/2.1.6/bin/pry:23:in `load'
	from /Users/sethvargo/.gem/ruby/2.1.6/bin/pry:23:in `<main> 
```

In my case, `pry` is throwing the issue, but it appears that any use of `__FILE__` and `__DIR__` will cause this error.

I don't know of a good way to fix this, since the error is happening far up the stack. I don't think that rescuing `Errno:ENOENT` is a valid option, since that could mean many different things.

/cc @mitchellh

**Comment by jperville** [comment]
Thanks @sethvargo . The issue does not show up anymore as of vagrant 1.7.4 (vagrant exits from raising Errno::ENOENT which is acceptable). At the time I reported the issue, I was still using vagrant 1.7.2 and the ruby interpreter crashed in a reproducible and nasty way (see the "malloc: assertion botched" and the core dump that follows the Errno::ENOENT).

**Comment by sethvargo** [comment]
Cool!
