### ISSUE TITLE
The box is not able to report an address for WinRM to connect to yet.

### ISSUE THREAD

**Issue by carlskii** [mitchellh/vagrant#6339]
Hi, I'm running the following:

Vmware Fusion version: 8.0.0 (2985594)
Vmware plugin version:  4.0.1
Vagrant version: 1.7.4

However even though the VM has booted Vagrant drops out with: 

```
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
```

HoweverIf try to provision as soon as I get this message it works OK. e.g.

```
$ vagrant provision
==> vagrant-windows-2012-r2: Running provisioner: shell...
    vagrant-windows-2012-r2: Running: inline PowerShell script
==> vagrant-windows-2012-r2: ================ Hello there ! ================
```

Here's the debug log. 

```
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::CommunicatorWinRM::Errors::WinRMNotReady: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.>
ERROR vagrant: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/helper.rb:36:in `winrm_address'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/helper.rb:21:in `winrm_info'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/communicator.rb:33:in `block in wait_for_ready'
/opt/vagrant/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/winrm/communicator.rb:29:in `wait_for_ready'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
/opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
 INFO interface: error: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO interface: Machine: error-exit ["VagrantPlugins::CommunicatorWinRM::Errors::WinRMNotReady", "The box is not able to report an address for WinRM to connect to yet.\nWinRM cannot access this Vagrant environment. Please wait for the\nVagrant environment to be running and try again."]
```

**Comment by sethvargo** [comment]
Hi @carlskii 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant and WinRM. Unfortunately there is not enough information here to reproduce and diagnose this issue. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks! :smile:
