### ISSUE TITLE
Multiple Machine issue due to 'default_provider' getting the wrong number of args

### ISSUE THREAD

**Issue by AdamWhittingham** [mitchellh/vagrant#6350]
Hi,

Long time user and fan of Vagrant, thanks for such a great tool!

I'm trying to provision two VM's in a single Vagrantfile and keep getting the following:
```
/Users/adam/.vagrant.d/gems/gems/vagrant-libvirt-0.0.22/lib/vagrant-libvirt.rb:34:in `default_provider': wrong number of arguments (1 for 0) (ArgumentError)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:165:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:192:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:174:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/up/command.rb:74:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:275:in `tap'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:275:in `block in batch'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:274:in `synchronize'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:274:in `batch'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/up/command.rb:58:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

I'm using Vagrant 1.7.4 against Virtualbox 5.
Even copying the basic first example from [the official multi-machine docs](https://docs.vagrantup.com/v2/multi-machine/) yeilds the same error.

Please let me know if there is anything I can do to help further debug this.

**Comment by sethvargo** [comment]
Hi @AdamWhittingham 

Thank you for opening an issue. Unfortunately that error is coming from the libvirt provider, not Vagrant itself. Could you please open an issue against the libvirt Vagrant plugin (which is maintained by a third party)? Thanks and sorry! :smile:
