### ISSUE TITLE
#HELP "vagrant-xenserer" plugin not working

### ISSUE THREAD

**Issue by babatundebusari** [mitchellh/vagrant#6458]
I am trying to use the "vagrant-xenserver" plugin located here `https://github.com/jonludlam/vagrant-xenserver` and it is just not working

```
xenserver 6.5
vagrant 1.7.4
vagrant-xenserver plugin 0.0.11
ruby 2.2.1p85
gem 2.4.5
CentOS 7.1.1503
```

Below are the errors when trying to run `vagrant up --provider=xenserver`
```
[vagrant@centos7xenserver ubuntu14vm1]$ vagrant up --provider=xenserver
/opt/vagrant/embedded/lib/ruby/2.0.0/xmlrpc/client.rb:486:in `do_rpc': HTTP-Error: 302 Found (RuntimeError)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/xmlrpc/client.rb:279:in `call2'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/xmlrpc/client.rb:260:in `call'
	from /home/vagrant/.vagrant.d/gems/gems/vagrant-xenserver-0.0.11/lib/vagrant-xenserver/action/connect_xs.rb:19:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /home/vagrant/.vagrant.d/gems/gems/vagrant-xenserver-0.0.11/lib/vagrant-xenserver/provider.rb:22:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:490:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:141:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:79:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:79:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:612:in `machine'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:192:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:174:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/up/command.rb:74:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:275:in `tap'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:275:in `block in batch'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:274:in `synchronize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:274:in `batch'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/up/command.rb:58:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

**Comment by sethvargo** [comment]
Hi @babatundebusari 

Thank you for opening an issue. Unfortunately we cannot provide help on third-party plugins. We do not maintain or support that plugin, so you will need to open an issue on that repo. That error is coming from the plugin, not Vagrant. Thanks!
