### ISSUE TITLE
How to use Ruby version >= 2.0 with Vagrant on Ubuntu 14.04 ?

### ISSUE THREAD

**Issue by valterhenrique** [mitchellh/vagrant#6492]
Hi everyone! First @mitchellh great work with **Vagrant**! Well done! 

I'm trying to install the **plugin** **vagrant-aws** in my **Ubuntu** server, which will deploy VM in AWS via Jenkins interface. 

The problem is that vagrant complains about the current **ruby version**, it needs to be **newer** than 2.0, right ? So, **I install a new version of ruby**, via Ubuntu, via rvm (you name it, I tried almost everything, almost >4 hours in this issue!), however **Vagrant keeps** trying to use **ruby1.9**.
If I try to remove only ruby1.9, vagrant is removed as well. 

Can anyone please help me with this ? I really am out of options here (I'm not a ruby expert/developer).

```
vagrant@jenkins:~$ sudo vagrant plugin install vagrant-aws
Installing the 'vagrant-aws' plugin. This can take a few minutes...
/usr/lib/ruby/1.9.1/rubygems/installer.rb:388:in `ensure_required_ruby_version_met': net-ssh requires Ruby version >= 2.0. (Gem::InstallError)
	from /usr/lib/ruby/1.9.1/rubygems/installer.rb:156:in `install'
	from /usr/lib/ruby/1.9.1/rubygems/dependency_installer.rb:297:in `block in install'
	from /usr/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each'
	from /usr/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each_with_index'
	from /usr/lib/ruby/1.9.1/rubygems/dependency_installer.rb:270:in `install'
	from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:65:in `block in call'
	from /usr/share/vagrant/plugins/commands/plugin/gem_helper.rb:42:in `block in with_environment'
	from /usr/lib/ruby/1.9.1/rubygems/user_interaction.rb:40:in `use_ui'
	from /usr/share/vagrant/plugins/commands/plugin/gem_helper.rb:41:in `with_environment'
	from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:52:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/commands/plugin/action/bundler_check.rb:20:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `run'
	from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:17:in `action'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:27:in `execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:38:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:484:in `cli'
	from /usr/bin/vagrant:127:in `<main>'
```

And my ruby -v
```
vagrant@jenkins:~$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux-gnu]
vagrant@jenkins:~$ sudo ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux-gnu]
```

vagrant user:
```
vagrant@jenkins:~$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5.1
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.2.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.2
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/vagrant/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.2.0
     - /home/vagrant/.gem/ruby/2.2.0
     - /usr/share/rubygems-integration/2.2.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
```

root user:
```
vagrant@jenkins:~$ sudo gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5.1
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.2.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.2
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/vagrant/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.2.0
     - /home/vagrant/.gem/ruby/2.2.0
     - /usr/share/rubygems-integration/2.2.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

**Comment by sethvargo** [comment]
Hi @valterhenrique 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. How did you install Vagrant? Vagrant comes packaged with its own Ruby environment that is isolated from the system ruby.

**Comment by valterhenrique** [comment]
Hi @sethvargo , thank you for the welcome message :)
I installed Vagrant with the ubuntu package manager `apt-get install -y vagrant'. But it seems that the version of vagrant that comes with it is very old. So, to fix this issue I installed the latest version of vagrant via the .deb file provided in the vagrant's download page.
