### ISSUE TITLE
EPERM: Operation not permitted with chef-solo provisioner on Mac OS X

### ISSUE THREAD

**Issue by gabel** [mitchellh/vagrant#6632]
I tried default and nfs mount confinguration but chef-solo provisionier always raises an "Operation not permitted" error. Even via ssh these files are not readable or chmod/chown cannot be applied even as sudo. 

On Windows or Ubuntu the configuration works.

Error
```
==> app-box: [2015-12-02T17:45:19+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> app-box: [2015-12-02T17:45:19+01:00] DEBUG: Errno::EPERM: Operation not permitted - /tmp/vagrant-chef/2718b3393e67f27ce3b9582577b028d6/cookbooks/chef_handler/metadata.json
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook/cookbook_version_loader.rb:162:in `read'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook/cookbook_version_loader.rb:162:in `apply_json_metadata'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook/cookbook_version_loader.rb:98:in `block in metadata'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook/cookbook_version_loader.rb:93:in `each'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook/cookbook_version_loader.rb:93:in `metadata'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook/cookbook_version_loader.rb:86:in `block in cookbook_version'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook/cookbook_version_loader.rb:74:in `tap'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook/cookbook_version_loader.rb:74:in `cookbook_version'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook_loader.rb:95:in `load_cookbook'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook_loader.rb:69:in `block (2 levels) in load_cookbooks'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook_loader.rb:68:in `each'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook_loader.rb:68:in `block in load_cookbooks'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook_loader.rb:67:in `each'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook_loader.rb:67:in `load_cookbooks'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:238:in `setup_run_context'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:492:in `do_run'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:199:in `block in run'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:193:in `fork'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:193:in `run'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application.rb:183:in `run_chef_client'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/solo.rb:239:in `block in run_application'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/solo.rb:231:in `loop'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/solo.rb:231:in `run_application'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application.rb:66:in `run'
==> app-box: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/bin/chef-solo:25:in `<top (required)>'
==> app-box: /usr/bin/chef-solo:23:in `load'
==> app-box: /usr/bin/chef-solo:23:in `<main>'
==> app-box: Chef Client failed. 0 resources updated
==> app-box: [2015-12-02T17:45:19+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1
```

Vagrantfile details
```
      app.vm.provision :chef_solo, run: "always" do |chef|
        chef.cookbooks_path = %w{./chef/cookbooks ./chef/site-cookbooks}
        chef.provisioning_path = "/tmp/vagrant-chef"
        chef.log_level = debug
        chef.verbose_logging = true
        chef.add_recipe "my-recipe"

        chef.json = {
          vagrant: true
        }
      end
```

**Comment by sethvargo** [comment]
Hi @gabel 

That error is coming from Chef, not Vagrant. It looks like your metadata does not have the proper permissions.

**Comment by gabel** [comment]
Chef complains about the permission, but the problem is in the underlying mount which is coming from chef-solo provisioner - so in my opinion the problem is based on the vagrant provisioner.

**Comment by sethvargo** [comment]
This is correct, but you will need to modify the folder permissions if you require a specific user: https://docs.vagrantup.com/v2/synced-folders/basic_usage.html. You may also need to specify `map_uid` and `map_gid`: https://docs.vagrantup.com/v2/synced-folders/nfs.html.

**Comment by gabel** [comment]
It was correct... file settings have to be set in the mounted directory. It was as cross OS problem of Linux/Windows and our file permissions.

**Comment by gabel** [comment]
:+1:  Thanks for caring!!
