### ISSUE TITLE
v1.8 dies immeidately

### ISSUE THREAD

**Issue by gwagner** [mitchellh/vagrant#6703]
```
VAGRANT_LOG=info vagrant --help                                                                                                                ~@IT1501.local
 INFO global: Vagrant version: 1.8.0
 INFO global: Ruby version: 2.2.3
 INFO global: RubyGems version: 2.4.5.1
 INFO global: VAGRANT_DEFAULT_PROVIDER="vmware_fusion"
 INFO global: VAGRANT_VMWARE_CLONE_DIRECTORY="/Users/user_name/.vagrant.d/vms"
 INFO global: VAGRANT_LOG="info"
 INFO global: VAGRANT_OLD_ENV_VAGRANT_VMWARE_CLONE_DIRECTORY="/Users/user_name/.vagrant.d/vms"
 INFO global: VAGRANT_OLD_ENV_LANG="en_US.UTF-8"
 INFO global: VAGRANT_OLD_ENV_XPC_SERVICE_NAME="0"
 INFO global: VAGRANT_OLD_ENV__system_arch="x86_64"
 INFO global: VAGRANT_OLD_ENV_SSH_AUTH_SOCK="/private/tmp/com.apple.launchd.UAtxDf0Jcg/Listeners"
 INFO global: VAGRANT_OLD_ENV_EC2_HOME="/Users/user_name/bin/ec2/ec2-api-tools-1.7.1.1/"
 INFO global: VAGRANT_OLD_ENV_rvm_stored_umask="022"
 INFO global: VAGRANT_OLD_ENV_ZSH="/Users/user_name/.oh-my-zsh"
 INFO global: VAGRANT_OLD_ENV_VAGRANT_DEFAULT_PROVIDER="vmware_fusion"
 INFO global: VAGRANT_OLD_ENV_rvm_version="1.26.9 (latest)"
 INFO global: VAGRANT_OLD_ENV_SHELL="/bin/zsh"
 INFO global: VAGRANT_OLD_ENV_LESS="-R"
 INFO global: VAGRANT_OLD_ENV_VAGRANT_LOG="info"
 INFO global: VAGRANT_OLD_ENV___CF_USER_TEXT_ENCODING="0x1F5:0x0:0x0"
 INFO global: VAGRANT_OLD_ENV_ANSIBLE_HOST_KEY_CHECKING="False"
 INFO global: VAGRANT_OLD_ENV_XPC_FLAGS="0x0"
 INFO global: VAGRANT_OLD_ENV_TERM="xterm"
 INFO global: VAGRANT_OLD_ENV_TERM_PROGRAM="iTerm.app"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_OLD_ENV__="/usr/local/bin/vagrant"
 INFO global: VAGRANT_OLD_ENV_Apple_PubSub_Socket_Render="/private/tmp/com.apple.launchd.MRH9jmWEFn/Render"
 INFO global: VAGRANT_OLD_ENV_rvm_bin_path="/Users/user_name/.rvm/bin"
 INFO global: VAGRANT_OLD_ENV_PAGER="less"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
 INFO global: VAGRANT_OLD_ENV_PWD="/Users/user_name"
 INFO global: VAGRANT_OLD_ENV_SHLVL="1"
 INFO global: VAGRANT_OLD_ENV_USER="user_name"
 INFO global: VAGRANT_OLD_ENV_ITERM_SESSION_ID="w0t1p0"
 INFO global: VAGRANT_OLD_ENV_PATH="/Users/user_name/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Library:/Applications/VMware OVF Tool/:/Users/user_name/bin/packer_0.7.2_darwin_amd64:/Users/user_name/bin/terraform-0.2.0:/Users/user_name/go/bin:/Users/user_name/bin/ec2/ec2-api-tools-1.7.1.1//bin:/Users/user_name/.composer/vendor/bin:/Applications/VMware Fusion.app/Contents/Library:/Applications/VMware OVF Tool/:/Users/user_name/go/bin:/Users/user_name/bin/ec2/ec2-api-tools-1.7.1.1//bin:/Library/Ruby/Gems/2.0.0/gems/knife-vsphere-1.2.5/lib/chef/knife:/Users/user_name/.rvm/bin:/Users/user_name/.rvm/bin"
 INFO global: VAGRANT_OLD_ENV_HOME="/Users/user_name"
 INFO global: VAGRANT_OLD_ENV_GOPATH="/Users/user_name/go"
 INFO global: VAGRANT_OLD_ENV_LC_CTYPE="en_US.UTF-8"
 INFO global: VAGRANT_OLD_ENV_rvm_path="/Users/user_name/.rvm"
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/gems/vagrant-1.8.0/bin/vagrant"
 INFO global: VAGRANT_OLD_ENV_OLDPWD="/Users/user_name"
 INFO global: VAGRANT_OLD_ENV_rvm_loaded_flag="1"
 INFO global: VAGRANT_OLD_ENV_ITERM_PROFILE="Default"
 INFO global: VAGRANT_OLD_ENV_GOROOT="/usr/local/go"
 INFO global: VAGRANT_OLD_ENV_LSCOLORS="Gxfxcxdxbxegedabagacad"
 INFO global: VAGRANT_OLD_ENV_rvm_prefix="/Users/user_name"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_OLD_ENV_TMPDIR="/var/folders/vl/q1hkm8lj3_g9pkd6rhkxz9b00000gn/T/"
 INFO global: VAGRANT_OLD_ENV_SSH_KEY_PATH="~/.ssh/id_rsa"
 INFO global: VAGRANT_OLD_ENV_JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home"
 INFO global: VAGRANT_OLD_ENV__system_type="Darwin"
 INFO global: VAGRANT_OLD_ENV_LOGNAME="user_name"
 INFO global: VAGRANT_OLD_ENV__system_name="OSX"
 INFO global: VAGRANT_OLD_ENV__system_version="10.11"
 INFO global: VAGRANT_OLD_ENV_rvm_user_install_flag="1"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: Plugins:
 INFO global:   - builder = 3.2.2
 INFO global:   - bundler = 1.10.6
 INFO global:   - i18n = 0.6.11
 INFO global:   - mime-types = 1.25.1
 INFO global:   - mini_portile = 0.6.0
 INFO global:   - nokogiri = 1.6.3.1
 INFO global:   - trollop = 2.1.2
 INFO global:   - rbvmomi = 1.8.2
 INFO global:   - rest-client = 1.6.9
 INFO global:   - vagrant-cachier = 1.2.1
 INFO global:   - vagrant-guestip = 0.2
 INFO global:   - vagrant-hosts = 2.5.0
 INFO global:   - vagrant-share = 1.1.5
 INFO global:   - vagrant-vmware-fusion = 4.0.1
 INFO global:   - vagrant-vsphere = 1.5.0
 INFO manager: Registered plugin: box command
 INFO manager: Registered plugin: cap command
 INFO manager: Registered plugin: destroy command
 INFO manager: Registered plugin: global-status command
 INFO manager: Registered plugin: halt command
 INFO manager: Registered plugin: help command
 INFO manager: Registered plugin: init command
 INFO manager: Registered plugin: list-commands command
 INFO manager: Registered plugin: vagrant-login
 INFO manager: Registered plugin: package command
 INFO manager: Registered plugin: plugin command
 INFO manager: Registered plugin: port command
 INFO manager: Registered plugin: powershell command
 INFO manager: Registered plugin: provider command
 INFO manager: Registered plugin: provision command
 INFO manager: Registered plugin: push command
 INFO manager: Registered plugin: rdp command
 INFO manager: Registered plugin: reload command
 INFO manager: Registered plugin: resume command
 INFO manager: Registered plugin: snapshot command
 INFO manager: Registered plugin: ssh command
 INFO manager: Registered plugin: ssh-config command
 INFO manager: Registered plugin: status command
 INFO manager: Registered plugin: suspend command
 INFO manager: Registered plugin: up command
 INFO manager: Registered plugin: version command
 INFO manager: Registered plugin: ssh communicator
 INFO manager: Registered plugin: winrm communicator
 INFO manager: Registered plugin: Arch guest
 INFO manager: Registered plugin: Atomic Host guest
 INFO manager: Registered plugin: CoreOS guest
 INFO manager: Registered plugin: Darwin guest
 INFO manager: Registered plugin: Debian guest
 INFO manager: Registered plugin: ESXi guest.
 INFO manager: Registered plugin: Fedora guest
 INFO manager: Registered plugin: FreeBSD guest
 INFO manager: Registered plugin: Funtoo guest
 INFO manager: Registered plugin: Gentoo guest
 INFO manager: Registered plugin: Linux guest.
 INFO manager: Registered plugin: Mint guest
 INFO manager: Registered plugin: NetBSD guest
 INFO manager: Registered plugin: NixOS guest
 INFO manager: Registered plugin: OmniOS guest.
 INFO manager: Registered plugin: OpenBSD guest
 INFO manager: Registered plugin: VMware Photon guest
 INFO manager: Registered plugin: PLD Linux guest
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
 INFO manager: Registered plugin: Slackware guest
 INFO manager: Registered plugin: SmartOS guest.
 INFO manager: Registered plugin: Solaris guest.
 INFO manager: Registered plugin: Solaris 11 guest.
 INFO manager: Registered plugin: SUSE guest
 INFO manager: Registered plugin: TinyCore Linux guest.
 INFO manager: Registered plugin: Ubuntu guest
 INFO manager: Registered plugin: Windows guest.
 INFO manager: Registered plugin: Arch host
 INFO manager: Registered plugin: BSD host
 INFO manager: Registered plugin: Mac OS X host
 INFO manager: Registered plugin: FreeBSD host
 INFO manager: Registered plugin: Gentoo host
 INFO manager: Registered plugin: Linux host
 INFO manager: Registered plugin: null host
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
 INFO manager: Registered plugin: Slackware host
 INFO manager: Registered plugin: SUSE host
 INFO manager: Registered plugin: Windows host
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: docker-provider
 INFO manager: Registered plugin: Hyper-V provider
 INFO manager: Registered plugin: VirtualBox provider
 INFO manager: Registered plugin: ansible
 INFO manager: Registered plugin: CFEngine Provisioner
 INFO manager: Registered plugin: chef
 INFO manager: Registered plugin: docker
 INFO manager: Registered plugin: file
 INFO manager: Registered plugin: puppet
 INFO manager: Registered plugin: salt
 INFO manager: Registered plugin: shell
 INFO manager: Registered plugin: atlas
 INFO manager: Registered plugin: ftp
 INFO manager: Registered plugin: heroku
 INFO manager: Registered plugin: local-exec
 INFO manager: Registered plugin: noop
 INFO manager: Registered plugin: NFS synced folders
 INFO manager: Registered plugin: RSync synced folders
 INFO manager: Registered plugin: SMB synced folders
 INFO global: Loading plugins!
 INFO manager: Registered plugin: vagrant-share
An unexpected error occurred while loading the Vagrant VMware
provider. Please contact support with the following
error code: '7'.
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::PluginLoadError: The plugins failed to load properly. The error message given is
shown below.

exit>
ERROR vagrant: The plugins failed to load properly. The error message given is
shown below.

exit
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant.rb:293:in `rescue in <top (required)>'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant.rb:289:in `<top (required)>'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.0/bin/vagrant:105:in `require'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.0/bin/vagrant:105:in `<main>'
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit
```

**Comment by mitchellh** [comment]
Please update the vagrant-vmware plugin. This will fix this.

**Comment by gwagner** [comment]
@mitchellh as an FYI, i was not able to run an update.  I needed to uninstall and re-install in order to fix the problem
