### ISSUE TITLE
Automatic install of virtualbox provider fails with "unitialized constant Vagrant::Util::FileChecksum (NameError)"

### ISSUE THREAD

**Issue by waded** [mitchellh/vagrant#6713]
Following the getting-started guide for Vagrant on Windows 10, but without installing VirtualBox first (since I saw it would be installed automatically), I did "vagrant init hashicorp/precise32" then "vagrant up."

The following was the output, and I could not proceed without installing VirtualBox manually.

```
==>  Provider 'virtualbox' not found. We'll automatically install it now...
     The installation process will start below. Human interaction may be
     required at some points. If you're uncomfortable with automatically
     installing this provider, you can safely Ctrl-C this process and install
     it manually.
==>  Downloading VirtualBox 5.0.10...
     This may not be the latest version of VirtualBox, but it is a version
     that is known to work well. Over time, we'll update the version that
     is installed.
     Progress: 100% (Rate: 9075k/s, Estimated time remaining: --:--:--)
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/hosts/windows/cap/provider_install_virtualbox.rb:36:in `provider_install_virtualbox': uninitialized constant Vagrant::Util::FileChecksum (NameError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/capability_host.rb:111:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/capability_host.rb:111:in `capability'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/environment.rb:405:in `install_provider'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/commands/up/command.rb:159:in `block in install_providers'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/set.rb:283:in `each_key'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/set.rb:283:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/commands/up/command.rb:141:in `install_providers'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/commands/up/command.rb:85:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/environment.rb:302:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.0/bin/vagrant:174:in `<main>'
```

**Comment by bharris47** [comment]
Same issue on Mac OS X 10.10.5

**Comment by ashaythool** [comment]
Try Installing Virtual Box installer separately. Then do "vagrant up". Simple.
https://www.virtualbox.org/wiki/Downloads

**Comment by mansu** [comment]
Same issue on Mac OS X 10.11.12. I installed vagrant using the installer. However on a vagrant up, I see this error:

```bash
☁  git:(vagrant) vagrant up                                                                                                                                 ~/code/teletraan
==>  Provider 'virtualbox' not found. We'll automatically install it now...
     The installation process will start below. Human interaction may be
     required at some points. If you're uncomfortable with automatically
     installing this provider, you can safely Ctrl-C this process and install
     it manually.
==>  Downloading VirtualBox 5.0.10...
     This may not be the latest version of VirtualBox, but it is a version
     that is known to work well. Over time, we'll update the version that
     is installed.
/opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/hosts/darwin/cap/provider_install_virtualbox.rb:35:in `provider_install_virtualbox': uninitialized constant Vagrant::Util::FileChecksum (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/capability_host.rb:111:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/capability_host.rb:111:in `capability'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/environment.rb:405:in `install_provider'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/commands/up/command.rb:159:in `block in install_providers'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/set.rb:283:in `each_key'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/set.rb:283:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/commands/up/command.rb:141:in `install_providers'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/commands/up/command.rb:85:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/environment.rb:302:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/bin/vagrant:174:in `<main>'
```

My vagrant file is pretty basic.

```bash
☁  git:(vagrant) ✗ cat Vagrantfile                                                                                                                          ~/code/teletraan
# Vagrant file for running teletran locally.

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# 1.5.0 is required to use vagrant cloud images.
# https://www.vagrantup.com/blog/vagrant-1-5-and-vagrant-cloud.html
Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "teletraan.local"
  config.vm.box = "ubuntu/wily64"
  config.vm.network :private_network, ip: "192.168.37.7"
end
```

**Comment by ashaythool** [comment]
Don't install Virtual box through Vagrant. Install newest version of Virtual Box separately and then try running vagrant again. It will work.

**Comment by stellis** [comment]
It would be helpful to have some transparency into HashiCorp's tests for each Vagrant release. If I'd known that no one had tested vagrant up on Windows 10 or OS X 10.11 with no VirtualBox installation, I would have tested it myself and changed my instructions to my company's contractors. It isn't a huge deal this time, but it could be a much bigger issue for a different kind of bug.

**Comment by mitchellh** [comment]
@stellis I verified the install on both OS X and Windows, so I'm not actually sure how this slipped through. My only thought is maybe there was a commit that changed something about the namespacing post-testing. :(

**Comment by mitchellh** [comment]
@stellis Found it, we added checksumming very near the release and didn't re-verify the code :( I apologize.

**Comment by mitchellh** [comment]
Fixed

**Comment by reedloden** [comment]
Sorry! :(

**Comment by Taariqq** [comment]
On Linux Mint, going from 8.2.1 to 9.0.0 I get this error. What to do?
