### ISSUE TITLE
rsync-auto does not work on 1.8 / 1.9 RPM

### ISSUE THREAD

**Issue by dkarlovi** [mitchellh/vagrant#6721]
```
[dkarlovi@machine example.com]$ vagrant rsync-auto
==> default: Doing an initial rsync...
==> default: Rsyncing folder: $HOME/example.com/ => /vagrant
==> default:   - Exclude: [".vagrant/", ".git/"]
==> default: Watching: $HOME/example.com
/opt/vagrant/embedded/gems/gems/ffi-1.9.10/lib/ffi.rb:6:in `require': libffi.so.5: cannot open shared object file: No such file or directory - /opt/vagrant/embedded/gems/extensions/x86_64-linux/2.2.0/ffi-1.9.10/ffi_c.so (LoadError)
    from /opt/vagrant/embedded/gems/gems/ffi-1.9.10/lib/ffi.rb:6:in `rescue in <top (required)>'
    from /opt/vagrant/embedded/gems/gems/ffi-1.9.10/lib/ffi.rb:3:in `<top (required)>'
    from /opt/vagrant/embedded/gems/gems/rb-inotify-0.9.5/lib/rb-inotify/native.rb:1:in `require'
    from /opt/vagrant/embedded/gems/gems/rb-inotify-0.9.5/lib/rb-inotify/native.rb:1:in `<top (required)>'
    from /opt/vagrant/embedded/gems/gems/rb-inotify-0.9.5/lib/rb-inotify.rb:1:in `require'
    from /opt/vagrant/embedded/gems/gems/rb-inotify-0.9.5/lib/rb-inotify.rb:1:in `<top (required)>'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/adapter/linux.rb:30:in `require'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/adapter/linux.rb:30:in `_configure'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/adapter/base.rb:45:in `block in configure'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/adapter/base.rb:40:in `each'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/adapter/base.rb:40:in `configure'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/adapter/base.rb:63:in `start'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/backend.rb:26:in `start'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/listener.rb:67:in `block in <class:Listener>'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/fsm.rb:120:in `instance_eval'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/fsm.rb:120:in `call'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/fsm.rb:57:in `transition'
    from /opt/vagrant/embedded/gems/gems/listen-3.0.5/lib/listen/listener.rb:90:in `start'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/synced_folders/rsync/command/rsync_auto.rb:142:in `block in execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/synced_folders/rsync/command/rsync_auto.rb:141:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/environment.rb:302:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/bin/vagrant:174:in `<main>'
```

**Comment by dkarlovi** [comment]
I've rebuilt the `ffi` gem and it works now (don't know how to work with `gem`: util correctly):

    cd /opt/vagrant/embedded/
    bin/gem install ffi -v
    cp lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/ffi-1.9.10/ffi_c.so  /opt/vagrant/embedded/gems/extensions/x86_64-linux/2.2.0/ffi-1.9.10/ffi_c.so

This is a hack until you get around to fix it.

**Comment by smerrill** [comment]
I can confirm this issue and that the workaround works on Fedora 23.

**Comment by rmebjesus** [comment]
I can also confirm the issue on RHEL 7.2 on 1.8.1 release.

@dkarlovi workaround works just fine, thanks!

**Comment by max-lobur** [comment]
Still reproduced, CentoS 7.2.1511, vagrant 1.8.5. 
Fix is:

```
cd /opt/vagrant/embedded/ && \
bin/gem install ffi -v 1.9.14 && \
yes | cp {lib/ruby/gems/2.2.0,gems}/extensions/x86_64-linux/2.2.0/ffi-1.9.14/ffi_c.so
```

**Comment by AronNovak** [comment]
Confirmed, Fedora 24, 64 bit, same issue, and the fix above by @max-lobur works perfectly.

**Comment by samjetski** [comment]
Confirmed, Fedora 24, 64 bit, same issue, same fix.
Vagrant 1.8.7

Note: due to SSL errors, I instead had to use:
```
bin/gem install ffi -v 1.9.14 --clear-sources --source http://rubygems.org/
```

**Comment by dkarlovi** [comment]
Still broken on 1.9, had to do this:

    # embedded rubygems certificate verification failed failed
    # see http://guides.rubygems.org/ssl-certificate-update/#manual-solution-to-ssl-issue
    cd /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/ssl_certs/
    wget https://raw.githubusercontent.com/rubygems/rubygems/master/lib/rubygems/ssl_certs/index.rubygems.org/GlobalSignRootCA.pem

    # rebuild ffi
    cd /opt/vagrant/embedded/
    bin/gem install ffi
     cp lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/ffi-1.9.14/ffi_c.so  /opt/vagrant/embedded/gems/extensions/x86_64-linux/2.2.0/ffi-1.9.14/ffi_c.so

**Comment by pembo13** [comment]
Could someone please clarify how this has been resolved for us CentOS users? Or when there will be updated RPMs that have this fix?

**Comment by dkarlovi** [comment]
@pembo13 I'm guessing the next release will include this fix? /cc @chrisroberts

**Comment by paperscissors** [comment]
This issue persists on Fedora 25 with Vagrant 1.9.1.
