### ISSUE TITLE
Vagrant 1.8.0 throwing traceback when reading "private_network" config stanza

### ISSUE THREAD

**Issue by heckj** [mitchellh/vagrant#6730]
I just upgraded to Vagrant 1.8.0 (MacOS X) and the Vagrantfile I had functioning ceased working correctly, with a traceback as follows when running `vagrant up`:

```
Bringing machine 'dev' up with 'virtualbox' provider...
/opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/kernel_v2/config/vm.rb:701:in `block in validate': undefined method `to_sym' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/kernel_v2/config/vm.rb:666:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/kernel_v2/config/vm.rb:666:in `validate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/config/v2/root.rb:68:in `block in validate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/config/v2/root.rb:64:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/config/v2/root.rb:64:in `validate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/machine.rb:224:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/machine.rb:199:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/environment.rb:561:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/machine.rb:185:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/machine.rb:185:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

Digging it out a bit, the stanza for `private_network` with a dedicated IP address setting is what's causing the failure. The stanza in question is:

    target.vm.network "private_network", ip: "172.31.128.1", virtualbox__intnet: "closed net"

and to make sure the virtualbox private pieces weren't related, I also tried (with the same results) the following line:

    target.vm.network "private_network", ip: "172.31.128.1"

When this line is removed, the Vagrant instance processes correctly and bring up the machine (minus the private network, of course). The source file is in an open source project: RackHD, available at https://github.com/RackHD/RackHD/blob/master/example/Vagrantfile

**Comment by mitchellh** [comment]
Thanks! Sorry about that, not sure how we never got it in other cases. Fixed now.

**Comment by heckj** [comment]
Awesome, thanks @mitchellh !
