### ISSUE TITLE
Problem with "vagrant up"

### ISSUE THREAD

**Issue by izzaldin2001** [mitchellh/vagrant#6736]
After I execute "vagrant up" command this is what happen:

```
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/win32/registry.rb:71:in `find': unknown encoding name - CP720 (ArgumentError)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/win32/registry.rb:71:in `<module:Win32>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/win32/registry.rb:3:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/win32/resolv.rb:6:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:169:in `<class:Hosts>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:166:in `<class:Resolv>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:36:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:6:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/spec_fetcher.rb:1:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:3:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/lockfile_parser.rb:87:in `<class:LockfileParser>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/lockfile_parser.rb:14:in `<module:Bundler>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/lockfile_parser.rb:13:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:1:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler.rb:155:in `definition'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler.rb:123:in `setup'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:71:in `<main>'
```

**Comment by thasmo** [comment]
Seems more like a [Ruby problem](http://stackoverflow.com/questions/22815542/rails4-unknown-encoding-name-cp720).

**Comment by izzaldin2001** [comment]
I don't have ruby in my pc?

**Comment by izzaldin2001** [comment]
Thanks <3

**Comment by iCyb3r** [comment]
Hello, can you please tell me how did you fix this issue?

**Comment by iCyb3r** [comment]
Thank I think I got it, just run this in the CMD window: "chcp 1252".

**Comment by izzaldin2001** [comment]
YES :D

**Comment by izzaldin2001** [comment]
The GIT bash has same problem :( how to slove?

**Comment by izzaldin2001** [comment]
Yes! I solved this problem by changing the window below:
![2015-12-30_15-38-41](https://cloud.githubusercontent.com/assets/12867258/12050822/80ca6ea4-af0b-11e5-8f4a-a3083160cba6.png)

**Comment by RamyFaiad** [comment]
"chcp 1252" didn't work for my case :( any help?

**Comment by iCyb3r** [comment]
@RamyFaiad I assume you are trying from the git bash CLI?

Try using it from windows command line or another ssh client who supports it like babun or cygwin, don't forget to run the command "vagrant up" from the same window.

Hope this helps.

**Comment by RamyFaiad** [comment]
@iCyb3r  It works :D, Thank you :)

**Comment by AShabana** [comment]
At git bash run this command 
$ chcp.com 1252
Active code page: 1252

**Comment by hamidyfine** [comment]
@thasmo THANKS... it works for me, too.

**Comment by HagarKassem** [comment]
The command "chcp 1252" works for me too, Thanks :)

**Comment by MajidHws** [comment]
"chcp 1252" - it works for me too thanks ..

**Comment by mosynaq** [comment]
"chcp 1252" - it works for me too. And it killed me to know it.
Please add it to the guide!
Thanks!

**Comment by devbhuwan** [comment]
"chcp 1252" - command works for me too.
Thanks!

**Comment by KISdesigners** [comment]
Thanks for the "chcp 1252" command it worked

**Comment by alihesari** [comment]
@AShabana Thanks for your solution. It's worked.

**Comment by AmirEdward** [comment]
the problem still exist and solution still working
$ chcp.com 1252 -- for git bash
Thanks

**Comment by charlessalameh** [comment]
chcp 1252 works for me but honestly did not know till now what was the issue

**Comment by MironVeryanskiy** [comment]
Found an explanation with more details here: https://stackoverflow.com/questions/22815542/rails4-unknown-encoding-name-cp720
