### ISSUE TITLE
chdir while rsync'ing fails

### ISSUE THREAD

**Issue by smolinari** [mitchellh/vagrant#6779]
Hi,

After a long bout of trying to get a remote VM running on Rackspace through Vagrant, I've now come to this dead end and can't find a solution.  I am using Windows7, Vagrant 1.7.4, [the Rackspace plugin](https://github.com/mitchellh/vagrant-rackspace), CygWin 2.4.0. 

Here is the debug output, at the point I believe things start to go sour.
```

DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: rsync_command
DEBUG guest: Checking in: debian
DEBUG guest: Checking in: linux
DEBUG guest: Found cap: rsync_command in linux
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: rsync_command
DEBUG guest: Checking in: debian
DEBUG guest: Checking in: linux
DEBUG guest: Found cap: rsync_command in linux
 INFO guest: Execute capability: rsync_command [#<Vagrant::Machine: default (VagrantPlugins::Rackspace::             Provider)>] (debian)
 INFO interface: info: Rsyncing folder: /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/ => /vagrant
 INFO interface: info: ==> default: Rsyncing folder: /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/ => /             vagrant
==> default: Rsyncing folder: /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/ => /vagrant
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: rsync_pre
DEBUG guest: Checking in: debian
DEBUG guest: Checking in: linux
DEBUG guest: Found cap: rsync_pre in linux
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: rsync_pre
DEBUG guest: Checking in: debian
DEBUG guest: Checking in: linux
DEBUG guest: Found cap: rsync_pre in linux
 INFO guest: Execute capability: rsync_pre [#<Vagrant::Machine: default (VagrantPlugins::Rackspace::Prov             ider)>, {:type=>:rsync, :guestpath=>"/vagrant", :hostpath=>"D:/webdev/VM Dev Boxes/Test Box DFW Rackspac             e", :disabled=>false, :owner=>"root", :group=>"root"}] (debian)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: mkdir -p '/vagrant' (sudo=true)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: Exit status: 0
 INFO subprocess: Starting process: ["D:\\Programme\\Cygwin\\bin/rsync.EXE", "--verbose", "--archive", "             --delete", "-z", "--copy-links", "--chmod=ugo=rwX", "--no-perms", "--no-owner", "--no-group", "--rsync-p             ath", "sudo rsync", "-e", "ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHost             sFile=/dev/null -i 'C:/Users/s.molinari/.ssh/id_rsa'", "--exclude", ".vagrant/", "/d/webdev/VM Dev Boxes             /Test Box DFW Rackspace/", "root@162.209.96.206:/vagrant"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: Warning: Permanently added '162.209.96.206' (ECDSA) to the list of known hosts             .
DEBUG subprocess: stdout: sending incremental file list

sent 39 bytes  received 11 bytes  33.33 bytes/sec
total size is 0  speedup is 0.00
DEBUG subprocess: stderr: rsync: change_dir "/d/webdev/VM Dev Boxes/Test Box DFW Rackspace" failed: No s             uch file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [send             er=3.1.1]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31997
DEBUG subprocess: Exit status: 23
ERROR warden: Error occurred: There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-g             roup --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnow             nHostsFile=/dev/null -i 'C:/Users/s.molinari/.ssh/id_rsa' --exclude .vagrant/ /d/webdev/VM Dev Boxes/Tes             t Box DFW Rackspace/ root@162.209.96.206:/vagrant
Error: Warning: Permanently added '162.209.96.206' (ECDSA) to the list of known hosts.
rsync: change_dir "/d/webdev/VM Dev Boxes/Test Box DFW Rackspace" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [send             er=3.1.1]

 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-g             roup --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnow             nHostsFile=/dev/null -i 'C:/Users/s.molinari/.ssh/id_rsa' --exclude .vagrant/ /d/webdev/VM Dev Boxes/Tes             t Box DFW Rackspace/ root@162.209.96.206:/vagrant
Error: Warning: Permanently added '162.209.96.206' (ECDSA) to the list of known hosts.
rsync: change_dir "/d/webdev/VM Dev Boxes/Test Box DFW Rackspace" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [send             er=3.1.1]

 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-g             roup --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnow             nHostsFile=/dev/null -i 'C:/Users/s.molinari/.ssh/id_rsa' --exclude .vagrant/ /d/webdev/VM Dev Boxes/Tes             t Box DFW Rackspace/ root@162.209.96.206:/vagrant
Error: Warning: Permanently added '162.209.96.206' (ECDSA) to the list of known hosts.
rsync: change_dir "/d/webdev/VM Dev Boxes/Test Box DFW Rackspace" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [send             er=3.1.1]

 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x3eb98a8>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-41433f39ad59287b47dd7ba16612e019
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x2759340>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::RSyncError: There was an error when attempting to rsync a synced folde             r.
Please inspect the error message below for more info.

Host path: /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-g             roup --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnow             nHostsFile=/dev/null -i 'C:/Users/s.molinari/.ssh/id_rsa' --exclude .vagrant/ /d/webdev/VM Dev Boxes/Tes             t Box DFW Rackspace/ root@162.209.96.206:/vagrant
Error: Warning: Permanently added '162.209.96.206' (ECDSA) to the list of known hosts.
rsync: change_dir "/d/webdev/VM Dev Boxes/Test Box DFW Rackspace" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [send             er=3.1.1]
>
ERROR vagrant: There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-g             roup --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnow             nHostsFile=/dev/null -i 'C:/Users/s.molinari/.ssh/id_rsa' --exclude .vagrant/ /d/webdev/VM Dev Boxes/Tes             t Box DFW Rackspace/ root@162.209.96.206:/vagrant
Error: Warning: Permanently added '162.209.96.206' (ECDSA) to the list of known hosts.
rsync: change_dir "/d/webdev/VM Dev Boxes/Test Box DFW Rackspace" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [send             er=3.1.1]

ERROR vagrant: C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/rsync/helper             .rb:149:in `rsync_single'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/rsync/synced_folder.rb:48:i             n `block in enable'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/rsync/synced_folder.rb:47:i             n `each'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/rsync/synced_folder.rb:47:i             n `enable'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:92:in              `block in call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:89:in              `each'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:89:in              `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in `cal             l'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/Users/s.molinari/.vagrant.d/gems/gems/vagrant-rackspace-0.1.10/lib/vagrant-rackspace/action/connect_r             ackspace.rb:40:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in final             ize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:i             n `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels             ) in run'
 INFO interface: error: There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-g             roup --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnow             nHostsFile=/dev/null -i 'C:/Users/s.molinari/.ssh/id_rsa' --exclude .vagrant/ /d/webdev/VM Dev Boxes/Tes             t Box DFW Rackspace/ root@162.209.96.206:/vagrant
Error: Warning: Permanently added '162.209.96.206' (ECDSA) to the list of known hosts.
rsync: change_dir "/d/webdev/VM Dev Boxes/Test Box DFW Rackspace" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [send             er=3.1.1]

There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-g             roup --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnow             nHostsFile=/dev/null -i 'C:/Users/s.molinari/.ssh/id_rsa' --exclude .vagrant/ /d/webdev/VM Dev Boxes/Tes             t Box DFW Rackspace/ root@162.209.96.206:/vagrant
Error: Warning: Permanently added '162.209.96.206' (ECDSA) to the list of known hosts.
rsync: change_dir "/d/webdev/VM Dev Boxes/Test Box DFW Rackspace" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [send             er=3.1.1]
 INFO interface: Machine: error-exit ["Vagrant::Errors::RSyncError", "There was an error when attempting              to rsync a synced folder.\nPlease inspect the error message below for more info.\n\nHost path: /d/webde             v/VM Dev Boxes/Test Box DFW Rackspace/\nGuest path: /vagrant\nCommand: rsync --verbose --archive --delet             e -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 22              -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Users/s.molina             ri/.ssh/id_rsa' --exclude .vagrant/ /d/webdev/VM Dev Boxes/Test Box DFW Rackspace/ root@162.209.96.206:/             vagrant\nError: Warning: Permanently added '162.209.96.206' (ECDSA) to the list of known hosts.\r\nrsync             : change_dir \"/d/webdev/VM Dev Boxes/Test Box DFW Rackspace\" failed: No such file or directory (2)\nrs             ync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender             =3.1.1]\n"]
```
Any help on this would be greatly appreciated.

I think I need to also add, this Vagrant setup was made by Puphpet. Not sure I should have asked for help there or here. If I am wrong here, please let me know.

Scott

**Comment by smolinari** [comment]
Hah! Nevermind. I found the solution actually. 

https://undebugable.wordpress.com/2015/11/06/vagrant-cygwin-error-on-rsync-folder/

Scott
