### ISSUE TITLE
Setting hostname fails for Lucid

### ISSUE THREAD

**Issue by davidmnoriega** [mitchellh/vagrant#6811]
Yes, I know Ubuntu Lucid(10.04) is EOL, but still need to run tests and have run across an issue in vagrant 1.8.1 where `vagrant up` fails at the Setting hostname step. It looks like this commit(c7186236f1ae30b6f4824b5aa2c56574c2fd7e5c) introduced the problem I'm seeing, where it tries to `cat /proc/1/comm` which doesn't exist in lucid and fails.

```
==> lucid: Setting hostname...
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
 INFO guest: Autodetecting host type for [#<Vagrant::Machine: lucid (HashiCorp::VagrantVMwarefusion::Provider)>]
DEBUG guest: Trying: atomic
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: grep 'ostree=' /proc/cmdline (sudo=false)
DEBUG ssh: Exit status: 1
DEBUG guest: Trying: mint
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: cat /etc/issue | grep 'Linux Mint' (sudo=false)
DEBUG ssh: Exit status: 1
DEBUG guest: Trying: fedora
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: grep 'Fedora release' /etc/redhat-release (sudo=false)
DEBUG ssh: stderr: grep: 
DEBUG ssh: stderr: /etc/redhat-release
DEBUG ssh: stderr: : No such file or directory
DEBUG ssh: stderr: 

DEBUG ssh: Exit status: 2
DEBUG guest: Trying: pld
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: cat /etc/pld-release (sudo=false)
DEBUG ssh: stderr: cat: 
DEBUG ssh: stderr: /etc/pld-release
DEBUG ssh: stderr: : No such file or directory
DEBUG ssh: stderr: 

DEBUG ssh: Exit status: 1
DEBUG guest: Trying: ubuntu
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: [ -x /usr/bin/lsb_release ] && /usr/bin/lsb_release -i 2>/dev/null | grep Ubuntu (sudo=false)
DEBUG ssh: stdout: Distributor ID:	Ubuntu

DEBUG ssh: Exit status: 0
 INFO guest: Detected: ubuntu!
DEBUG guest: Searching for cap: change_host_name
DEBUG guest: Checking in: ubuntu
DEBUG guest: Found cap: change_host_name in ubuntu
 INFO guest: Execute capability: change_host_name [#<Vagrant::Machine: lucid (HashiCorp::VagrantVMwarefusion::Provider)>, "lucid.local"] (ubuntu)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: hostname -f (sudo=true)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: stdout: vagrant.localdomain

DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: cat /proc/1/comm (sudo=false)
DEBUG ssh: stderr: cat: 
DEBUG ssh: stderr: /proc/1/comm
DEBUG ssh: stderr: : No such file or directory
DEBUG ssh: stderr: 

DEBUG ssh: Exit status: 1
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory

 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::HandleForwardedPortCollisions:0x000001029e1210>
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory

 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory

 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000001032ab530>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory

 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory

 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000001031b8858>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Calling recover: VMware Middleware: Import
 INFO subprocess: Starting process: ["/Applications/VMware Fusion.app/Contents/Library/vmrun", "list"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: Total running VMs: 4
/Users/davidmnoriega/repo/ig/deploy/ldap/.vagrant/machines/trusty/vmware_fusion/f4cb57de-cb4f-4acf-9538-22258e95406b/ubuntu-14.04-amd64.vmx
/Users/davidmnoriega/repo/ig/deploy/ldap/.vagrant/machines/precise/vmware_fusion/977458e1-918e-4ac9-9e47-906cb007b86b/ubuntu-12.04-amd64.vmx
/Users/davidmnoriega/repo/ig/deploy/ldap/.vagrant/machines/lucid/vmware_fusion/22fe4f52-4791-4790-85e9-0f2cf975c9e2/ubuntu-10.04-amd64.vmx
/Users/davidmnoriega/repo/ig/deploy/ldap/.vagrant/machines/ldap/vmware_fusion/6a3039a7-6bc8-4460-a047-91ba94ee754b/ubuntu-14.04-amd64.vmx
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG vmware: VM state requested. Current state: running
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory

 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory

 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000001009ef790>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-049416135bbd2aa18b50954c04e3e3f2
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 4 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x000001068e5830>
 INFO warden: Calling IN action: HashiCorp Background Check: End
 INFO logger: Cleaning up background activation thread...
 INFO warden: Calling OUT action: HashiCorp Background Check: End
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VagrantError: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory
>
ERROR vagrant: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory

ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:236:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/guests/ubuntu/cap/change_host_name.rb:36:in `init_package'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/guests/ubuntu/cap/change_host_name.rb:46:in `systemd?'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/guests/ubuntu/cap/change_host_name.rb:10:in `update_etc_hostname'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/guests/debian/cap/change_host_name.rb:19:in `change!'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/guests/debian/cap/change_host_name.rb:6:in `change_host_name'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/guests/ubuntu/cap/change_host_name.rb:6:in `change_host_name'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/capability_host.rb:111:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/capability_host.rb:111:in `capability'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/guest.rb:43:in `capability'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/set_hostname.rb:21:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:726:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:953:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:1025:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/action/update_all.rb:27:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-cachier-1.2.1/lib/vagrant-cachier/action/install_buckets.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-cachier-1.2.1/lib/vagrant-cachier/action/configure_bucket_root.rb:20:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:71:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:1055:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_check_outdated.rb:78:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:1347:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:273:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:143:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:1134:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:502:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:1347:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:99:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:273:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/davidmnoriega/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.5/lib/vagrant-vmware-fusion/action_farm.rb:160:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
/opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
 INFO interface: error: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /proc/1/comm

Stdout from the command:



Stderr from the command:

cat: /proc/1/comm: No such file or directory

 INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantError", "The following SSH command responded with a non-zero exit status.\nVagrant assumes that this means the command failed!\n\ncat /proc/1/comm\n\nStdout from the command:\n\n\n\nStderr from the command:\n\ncat: /proc/1/comm: No such file or directory\n"]
```

I tested with both virtualbox and vmware-fusion providers using the bento/ubuntu-10.04 box, vagrant 1.8.1 on Mac OS X 10.11.2.

**Comment by knox1000** [comment]
Ran into this issue with 1.8.0 and 1.8.1 (Windows7) as well.  Downgrading to 1.7.4 let me provision a Lucid VM though.

**Comment by davidmnoriega** [comment]
Yes, downgrading to 1.7.4 works.

**Comment by yankos** [comment]
Have a similar problem with Ubuntu 14.04 as guest and Windows 10 on host

**Comment by dwa012** [comment]
Same issue here with Ubuntu 14.04 guest and OSX 10.11.1 host.

**Comment by tersmitten** [comment]
We have to same problem on 10.04.

**Comment by ggolin** [comment]
+1 on 1.8.1 with 15.10 host.

**Comment by liuct** [comment]
same issue on ubuntu 12.04.
so i need to downgrade it to  1.7.4 ?

**Comment by yankos** [comment]
@liuct i think yes, downgrade to 1.7.4 help for me

**Comment by liuct** [comment]
@tersmitten  i have tried, i can launch the VMs from  list in the user interface 
of VM VirtualBox, Maybe a workaground.

**Comment by tersmitten** [comment]
Ubuntu 12.04 work fine for me, latest version of vagrant
