### ISSUE TITLE
Vagrant can't communicate with VBoxManage

### ISSUE THREAD

**Issue by Dreezn** [mitchellh/vagrant#6939]
Hello,

I received a new and fast pc and on this new pc (win7) I get the error messages as #5040 and #5309

I experience this issue with all versions of vagrant, from 1.7.1 to 1.8.1

So I added some debug prints to the io.rb file in C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.1\lib\vagrant\util:

```
require "vagrant/util/platform"

module Vagrant
  module Util
    class IO
      # The chunk size for reading from subprocess IO.
      READ_CHUNK_SIZE = 4096

      # Reads data from an IO object while it can, returning the data it reads.
      # When it encounters a case when it can't read anymore, it returns the
      # data.
      #
      # @return [String]
      def self.read_until_block(io)
        data = ""
        test = Integer(0)

        while true
          begin
            if Platform.windows?
              # Windows doesn't support non-blocking reads on
              # file descriptors or pipes so we have to get
              # a bit more creative.

              # Check if data is actually ready on this IO device.
              # We have to do this since `readpartial` will actually block
              # until data is available, which can cause blocking forever
              # in some cases.

              results = ::IO.select([io], nil, nil, 0.1)
              break if !results || results[0].empty?
              print "check\n"
              # Read!
              data << io.readpartial(READ_CHUNK_SIZE).encode("UTF-8", Encoding.default_external)
              print "check2 "
              print data
              print "\n"
            else
              # Do a simple non-blocking read on the IO object
              data << io.read_nonblock(READ_CHUNK_SIZE)
            end
          rescue Exception => e
            # The catch-all rescue here is to support multiple Ruby versions,
            # since we use some Ruby 1.9 specific exceptions.

            breakable = false
            if e.is_a?(EOFError)
              # An `EOFError` means this IO object is done!
              print "check3 "
              print data
              print " reached EOF\n"
              breakable = true
            elsif defined?(::IO::WaitReadable) && e.is_a?(::IO::WaitReadable)
              # IO::WaitReadable is only available on Ruby 1.9+

              # An IO::WaitReadable means there may be more IO but this
              # IO object is not ready to be read from yet. No problem,
              # we read as much as we can, so we break.
              print "Got IO WaitReadable\n"
              breakable = true
            elsif e.is_a?(Errno::EAGAIN)
              # Otherwise, we just look for the EAGAIN error which should be
              # all that IO::WaitReadable does in Ruby 1.9.
              print "Got EAGAIN\n"
              breakable = true
            end

            # Break out if we're supposed to. Otherwise re-raise the error
            # because it is a real problem.
            break if breakable
            print "No known error cases; raising the real problem\n"
            raise
          end
        end

        data
      end

    end
  end
end
```

For a simple vagrant up, we get the version error:

```
λ vagrant up --provision
check
check3  reached EOF
check
check3  reached EOF
check
check3  reached EOF
check
check3  reached EOF
C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/config.rb:83:in `block in missing_interpolation_argument_handler': missing interpolation argument :vboxmanage in "Vagrant detected that VirtualBox appears installed on your system,\nbut calls to detect the version are returning empty. This is often\nindicative of installation issues with VirtualBox. Please verify\nthat VirtualBox is properly installed. As a final verification,\nplease run the following command manually and verify a version is\noutputted:\n\n%{vboxmanage} --version" ({:_key=>:virtualbox_version_empty, :_namespace=>"vagrant.errors"} given) (I18n::MissingInterpolationArgument)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:29:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:29:in `block in interpolate_hash'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:21:in `gsub'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:21:in `interpolate_hash'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:17:in `interpolate'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/backend/base.rb:153:in `interpolate'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/backend/base.rb:41:in `translate'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:157:in `block in translate'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:153:in `catch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:153:in `translate'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/errors.rb:103:in `translate_error'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/errors.rb:72:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/driver/meta.rb:155:in `exception'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/driver/meta.rb:155:in `raise'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/driver/meta.rb:155:in `block in read_version'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/retryable.rb:17:in `retryable'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/driver/meta.rb:140:in `read_version'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/driver/meta.rb:38:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/provider.rb:11:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/provider.rb:11:in `usable?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:378:in `block in default_provider'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:377:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:377:in `default_provider'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/command.rb:165:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/command.rb:192:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/command.rb:174:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/up/command.rb:74:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:275:in `tap'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:275:in `block in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:274:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:274:in `batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/up/command.rb:58:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/bin/vagrant:174:in `<main>'
```

If we hard code the version of vbox in meta.rb, we get the error where the name can't be found, with the extra output we get:

```
Bringing machine 'default' up with 'virtualbox' provider...
check
check3  reached EOF
check
check3  reached EOF
check
check3  reached EOF
check
check3  reached EOF
==> default: Importing base box 'puphpet/debian75-x64'...
check
check3  reached EOF
check
check2 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

check
check3 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
 reached EOF
check
check3  reached EOF
check
check3  reached EOF
ERROR warden: Error occurred: Vagrant was unable to determine the recommended name for your
VirtualBox VM. This is usually an issue with VirtualBox. The output
from VirtualBox is shown below, which may contain an error to fix.
The best way to fix this issue is usually to uninstall VirtualBox,
restart your computer, then reinstall VirtualBox.

VirtualBox output:

```
So it appears that the stream does not get all data but instead receives an EOF too early somehow. 

Any idea what I can do to solve this? I cannot setup even the simplest vagrant config now.

For the record: executing the commands manually with VBoxManage works fine. In the output of the name error we see the first part of the output of VBoxManage, but the rest is skipped because of an EOF error.

Any help would be much appreciated!

_Edit: updated for clarity_

**Comment by JotBePunkt** [comment]
Got the same error with Vagrant 1.8.1 and VirtualBox 5.0.14r105127

**Comment by lmendoza92** [comment]
I had to run the terminal as administrator and it worked

**Comment by sethvargo** [comment]
@Dreezn @JotBePunkt are you running cmd/powershell as admin?

**Comment by Dreezn** [comment]
It appears I had a similar oversight.
I was using [CMDER](https://github.com/cmderdev/cmder).
When seeing @lmendoza92 's comment, it occurred to me i never ran vagrant in a standard windows cmd.
And sure enough it works.

Apparently the problem lies with CMDER.
Maybe this doesn't solve @JotBePunkt 's problem, though...

**Comment by JotBePunkt** [comment]
yes, I was using cmder too, and using cmd solve the problem

**Comment by lmendoza92** [comment]
@JotBePunkt Yeah bro, it's very strange.. Vagrant + Cmder works on my desktop computer but my labtop has that issue. Nothing to do..

**Comment by 0x1mason** [comment]
Yeppers, same problem here.
