### ISSUE TITLE
vagrant crashes when halting a machine

### ISSUE THREAD

**Issue by radoslawcz** [mitchellh/vagrant#6992]
When trying to halt a running machine

```
$ vagrant global-status
id       name     provider   state    directory
------------------------------------------------------------------------------------------------------------
6aa0822  logstash virtualbox poweroff C:/ProgramData/chocolatey/lib/Cygwin/tools/cygwin/home/Radek/logi
10d350b  elastic  virtualbox running  C:/ProgramData/chocolatey/lib/Cygwin/tools/cygwin/home/Radek/logi

```

vagrant crashes with

```
$ vagrant halt 10d350b
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/kernel_v2/config/vm.rb:236:in `network': wrong number of arguments (0 for 1) (ArgumentError)
        from C:/ProgramData/chocolatey/lib/Cygwin/tools/cygwin/home/Radek/logi/Vagrantfile:14:in `block (2 levels) in <top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/loader.rb:37:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/loader.rb:37:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:113:in `block (2 levels) in load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:107:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:107:in `block in load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:104:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:104:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:153:in `machine_config'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:45:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:663:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:147:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:201:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:183:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/halt/command.rb:30:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

```
```

**Comment by radoslawcz** [comment]
I restarted my laptop and the machine still shows as "running"... how to halt it?

**Comment by sethvargo** [comment]
Hi @radoslawcz 

This is a bug because you should never see a stack trace. The error you're getting seems similar to https://github.com/mitchellh/vagrant/issues/6834.

**Comment by kamigerami** [comment]
@sethvargo @radoslawcz take a look at the PR #6920 to see if it fixes these issues

**Comment by noplanman** [comment]
@radoslawcz Have you tried `vagrant global-status --prune`?
That should clear the status cache and fetch the up-to-date VM states.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
