### ISSUE TITLE
Error upgrade 1.7.4 to 1.8.1 OSX mac

### ISSUE THREAD

**Issue by prhost** [mitchellh/vagrant#7022]
```
/Users/username/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:13:in `require': incompatible library version - /Users/username/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext/parser.bundle (fatal)
	from /Users/username/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:13:in `<module:Ext>'
	from /Users/username/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:12:in `<module:JSON>'
	from /Users/username/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:9:in `<top (required)>'
	from /Users/username/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:58:in `require'
	from /Users/username/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:58:in `<module:JSON>'
	from /Users/username/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:54:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:55:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:55:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `<main>'
```

**Comment by sethvargo** [comment]
Hi @prhost 

This looks like an error coming from a plugin that you had installed. Can you please try removing the `~/.vagrant.d` directory and see if the problem persists?

**Comment by prhost** [comment]
The problem was with plugin, removed the vagrant-digitalocean plugin (0.7.10) and worked. Thank you (:
