### ISSUE TITLE
"vagrant plugin install vagrant-libvirt" on Ubuntu 14.04 must display a user-friendly message if libvirt is not installed

### ISSUE THREAD

**Issue by vhosakot** [mitchellh/vagrant#7039]
I downloaded Vagrant 1.8.1 for Ubuntu 14.04 and see the following errors when I run "vagrant plugin install vagrant-libvirt" if libvirt is not installed.  Below are the steps I ran.

```
$ wget https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
$ sudo dpkg -i vagrant_1.8.1_x86_64.deb 
```

"vagrant plugin install vagrant-libvirt" throws the following error that is tough to understand:

```
**$ vagrant plugin install vagrant-libvirt**
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    /opt/vagrant/embedded/bin/ruby -r ./siteconf20160215-2646-e5ybv0.rb extconf.rb
creating Makefile
make "DESTDIR=" clean
sh: 1: make: not found
make "DESTDIR="
sh: 1: make: not found
make failed, exit code 127
Gem files will remain installed in /home/me/.vagrant.d/gems/gems/json-1.8.3 for inspection.
Results logged to /home/me/.vagrant.d/gems/extensions/x86_64-linux/2.2.0/json-1.8.3/gem_make.out

/home/me/.vagrant.d/gems/extensions/x86_64-linux/2.2.0/json-1.8.3/gem_make.out has the following:

**$ cat /home/me/.vagrant.d/gems/extensions/x86_64-linux/2.2.0/json-1.8.3/gem_make.out**
/opt/vagrant/embedded/bin/ruby -r ./siteconf20160215-2646-e5ybv0.rb extconf.rb
creating Makefile
make "DESTDIR=" clean
sh: 1: make: not found
make "DESTDIR="
sh: 1: make: not found
make failed, exit code 127
```

**Then, I ran the following command.**

```
$ sudo apt-get -y install qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
```

"vagrant plugin install vagrant-libvirt" still threw the following error that is tough to understand:

```
**$ vagrant plugin install vagrant-libvirt**
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:
An error occurred while installing ruby-libvirt (0.6.0), and Bundler cannot continue.
Make sure that `gem install ruby-libvirt -v '0.6.0'` succeeds before bundling.
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    /opt/vagrant/embedded/bin/ruby -r ./siteconf20160215-12758-13yz600.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:73:in <main>libvirt library not found in default locations (RuntimeError)
extconf failed, exit code 1
Gem files will remain installed in /home/me/.vagrant.d/gems/gems/ruby-libvirt-0.6.0 for inspection.
Results logged to /home/me/.vagrant.d/gems/extensions/x86_64-linux/2.2.0/ruby-libvirt-0.6.0/gem_make.out

This time, /home/me/.vagrant.d/gems/extensions/x86_64-linux/2.2.0/json-1.8.3/gem_make.out has the following:

**$ cat /home/me/.vagrant.d/gems/extensions/x86_64-linux/2.2.0/ruby-libvirt-0.6.0/gem_make.out**
/opt/vagrant/embedded/bin/ruby -r ./siteconf20160215-12758-13yz600.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:73:in <main>libvirt library not found in default locations (RuntimeError)
extconf failed, exit code 1
```

**Then, I ran the following command.**

```
$ sudo apt-get -y install libvirt-dev
```

"vagrant plugin install vagrant-libvirt" finally worked this time!

```
**$ vagrant plugin install vagrant-libvirt**
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Installed the plugin 'vagrant-libvirt (0.0.32)'!
```

**If libvirt is not installed, It would be great if Vagrant displays a user-friendly message like:**

```
libvirt is missing. Please install libvirt before installing the vagrant-libvirt Vagrant plugin.

On Ubuntu 14.04, run:

sudo apt-get -y install libvirt-dev qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
```

**Comment by sethvargo** [comment]
Hi @vhosakot 

Thank you for opening an issue, and I definitely understand how frustrating this can be. Unfortunately vagrant-libvirt is a third-party plugin and we cannot catch all errors from plugins. It is the plugin author's responsibility to properly list all plugin requirements. I'm sorry this cause you trouble, but unfortunately this is the plugin author's responsibility, not Vagrant core. I would recommend opening an issue on that plugin. Thanks! :smile:

**Comment by vhosakot** [comment]
Can't Vagrant check if the "libvirt-dev" package is installed or not before allowing the vagrant-libvirt plugin to be installed ?  On Ubuntu, can't Vagrant issue one of the following commands to check if the "libvirt-dev" package exists or not when installing the vagrant-libvirt plugin. If the libvirt-dev package is not installed, Vagrant could throw a user-friendly error and exit.

`dpkg --get-selections | grep libvirt-dev`

or

`dpkg -l | grep libvirt-dev`

or

`apt --installed list | grep libvirt-dev`

**Comment by sethvargo** [comment]
Hi @vhosakot 

Unfortunately it's not sustainable for Vagrant to know the requirements for every plugin. Additionally, the commands for each operating system are different and these requirements can change between versions. This is why it's best left to the plugin authors to list the requirements in the installation documentation.

**Comment by chaim1221** [comment]
Found this page on Google looking for help. Thanks @vhosakot for the answer.

"Every plugin?" You mean like the plugin that people use to use Vagrant with KVM? [...]

**Comment by devtosystems** [comment]
I'm not founded `zlib` for Debian 8 jessie uk repositories.

And problem continues.

* Compile qemu with `./configure`

```bash
The following packages have unmet dependencies:
 libvirt-bin : Depends: libvirt-daemon-system (>= 1.2.9-9+deb8u3) but it is not going to be installed
               Depends: libvirt-clients (>= 1.2.9-9+deb8u3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I try to install vagrant-libvirt plugin and this error appears:

```bash
$ vagrant plugin install vagrant-libvirt

Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby -r ./siteconf20161216-23024-ybwlm0.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

**Comment by Baroti** [comment]
Error "libvirt library not found in default locations" can be solved by specifying the library location as in this example:
**CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt" vagrant plugin install vagrant-libvirt**

Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Fetching: fog-libvirt-0.5.0.gem (100%)
Fetching: vagrant-libvirt-0.0.43.gem (100%)
Installed the plugin 'vagrant-libvirt (0.0.43)'!

**ls -la /usr/include/libvirt**

-rw-r--r--  1 root root   3975 Apr  5 06:22 libvirt-common.h
-rw-r--r--  1 root root 146956 Apr  5 06:22 libvirt-domain.h
-rw-r--r--  1 root root  10402 Apr  5 06:22 libvirt-domain-snapshot.h
-rw-r--r--  1 root root   6594 Apr  5 06:22 libvirt-event.h
-rw-r--r--  1 root root   1725 Apr  5 06:22 libvirt.h
-rw-r--r--  1 root root  28065 Apr  5 06:22 libvirt-host.h
-rw-r--r--  1 root root   4571 Apr  5 06:22 libvirt-interface.h
-rw-r--r--  1 root root   1867 Apr  5 06:22 libvirt-lxc.h
-rw-r--r--  1 root root  12506 Apr  5 06:22 libvirt-network.h
-rw-r--r--  1 root root   5538 Apr  5 06:22 libvirt-nodedev.h
-rw-r--r--  1 root root   3508 Apr  5 06:22 libvirt-nwfilter.h
-rw-r--r--  1 root root   4101 Apr  5 06:22 libvirt-qemu.h
-rw-r--r--  1 root root   4963 Apr  5 06:22 libvirt-secret.h
-rw-r--r--  1 root root  17277 Apr  5 06:22 libvirt-storage.h
-rw-r--r--  1 root root   4938 Apr  5 06:22 libvirt-stream.h
-rw-r--r--  1 root root  16545 Apr  5 06:22 virterror.h

**Comment by Wenzel** [comment]
Hi,

I tried to use  the `CONFIGURE_ARGS` trick, but it failed with this message:
~~~
extconf.rb:70:in `<main>': Must specify both --with-libvirt-include and --with-libvirt-lib, or neither (RuntimeError)
~~~

So I had to add a second configure parameter to the command line
~~~
CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Fetching: fog-libvirt-0.5.0.gem (100%)
Fetching: vagrant-libvirt-0.0.43.gem (100%)
Installed the plugin 'vagrant-libvirt (0.0.43)'!
~~~

**Comment by Longkho** [comment]
follow the step listed by Wenzel and I am able to get packer/vagrant to create VM under qemu  
for both linux/windows. Many Thanks!!!

**Comment by ericpulvino** [comment]
Wenzel's answer worked for me too, thank you!

**Comment by alexellis** [comment]
Tried everything in this thread with no luck. Even the last answer from @Wenzel doesn't work on Ubuntu 16.04.x and this is not a good experience for Linux developers wanting to use Vagrant.

As this seems to be a common issue, is there a way we can improve the documentation? Where is the best place to start with that? cc @acornies @nicholasjackson

**Comment by alexellis** [comment]
My latest error during installation - https://gist.github.com/alexellis/046fa757113105ac1871644620756aed

**Comment by syndbg** [comment]
With Ubuntu 18.04 bionic

The issue is

```
▶ vagrant plugin install vagrant-libvirt                                                                                                                                                                            
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...                                                                                                                                             
Building native extensions.  This could take a while...                                                                                                                                                             
Bundler, the underlying system Vagrant uses to install plugins,                                                                                                                                                     
reported an error. The error is shown below. These errors are usually                                                                                                                                               
caused by misconfigured plugin installations or transient network                                                                                                                                                   
issues. The error from Bundler is:                                                                                                                                                                                  
                                                                                                                                                                                                                    
ERROR: Failed to build gem native extension.                                                                                                                                                                        
                                
    current directory: /home/syndbg/.vagrant.d/gems/2.4.4/gems/ruby-libvirt-0.7.1/ext/libvirt
/tmp/.mount_vagranQOodGV/usr/bin/ruby2.4 -r ./siteconf20181123-16356-10l2vsb.rb extconf.rb
*** extconf.rb failed ***                                                               
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may                  
need configuration options.
                                                                                              
Provided configuration options:
        --with-opt-dir     
        --without-opt-dir
        --with-opt-include                                                                                   
        --without-opt-include=${opt-dir}/include                                                                  
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog                                                                                                                                                                                           
        --without-make-prog                                                                                                  
        --srcdir=.                                                     
        --curdir                                       
        --ruby=/tmp/.mount_vagranQOodGV/usr/bin/$(RUBY_BASE_NAME)2.4
        --with-libvirt-include             
        --without-libvirt-include               
        --with-libvirt-lib
        --without-libvirt-lib                                                                                                                                                                                     
        --with-libvirt-config
        --without-libvirt-config
        --with-pkg-config
        --without-pkg-config                                                                                                                                                                                      
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)
     
To see why this extension failed to compile, please check the mkmf.log which can be found here:
                                                                                                                                                                                                                   
  /home/syndbg/.vagrant.d/gems/2.4.4/extensions/x86_64-linux/2.4.0/ruby-libvirt-0.7.1/mkmf.log
                             
extconf failed, exit code 1
                                                                                                                                                                                                                   
Gem files will remain installed in /home/syndbg/.vagrant.d/gems/2.4.4/gems/ruby-libvirt-0.7.1 for inspection.
Results logged to /home/syndbg/.vagrant.d/gems/2.4.4/extensions/x86_64-linux/2.4.0/ruby-libvirt-0.7.1/gem_make.out
```

The following is enough to make it sufficient to be installable *but still not work* - `apt install -y libvirt-dev`.

Now if we check carefully via `dpkg --listfiles libvirt-dev` where the SO files and the headers are, we can provide

```
CONFIGURE_ARGS='with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' vagrant plugin install vagrant-libvirt
```

But this still does not work.

The final piece is to use `ld.gold` instead of `ld`.

```
> rm /usr/bin/ld
> ln -fs /usr/bin/ld.gold /usr/bin/ld
``

And finally it works

```
▶ CONFIGURE_ARGS='with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Fetching: fog-libvirt-0.5.0.gem (100%)
Fetching: vagrant-libvirt-0.0.45.gem (100%)
Installed the plugin 'vagrant-libvirt (0.0.45)'!
```

**Comment by syndbg** [comment]
However it's still not perfect

```
▶ bundle exec kitchen create                                                                                                    
-----> Starting Kitchen (v1.23.2)                                                                                         
-----> Creating <default-pve>...                                                                            
       /tmp/.mount_vagranpVWNOC/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/lib/x86_64-linux-gnu/libgnutls.so.30: symbol asn1_der_decoding2 version LIBTASN1_0_3 not defined in fil
e libtasn1.so.6 with link time reference - /home/syndbg/.vagrant.d/gems/2.4.4/gems/ruby-libvirt-0.7.1/lib/_libvirt.so (LoadError)
        from /tmp/.mount_vagranpVWNOC/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'     
        from /home/syndbg/.vagrant.d/gems/2.4.4/gems/ruby-libvirt-0.7.1/lib/libvirt.rb:11:in `<top (required)>'   
        from /tmp/.mount_vagranpVWNOC/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'                             
        from /tmp/.mount_vagranpVWNOC/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'                             
        from /home/syndbg/.vagrant.d/gems/2.4.4/gems/fog-libvirt-0.5.0/lib/fog/libvirt.rb:4:in `<top (required)>'    
        from /tmp/.mount_vagranpVWNOC/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'                    
        from /tmp/.mount_vagranpVWNOC/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'         
        from /home/syndbg/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/driver.rb:1:in `<top (required)>'
        from /tmp/.mount_vagranpVWNOC/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                                                                        
        from /tmp/.mount_vagranpVWNOC/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'                      
        from /home/syndbg/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/provider.rb:29:in `driver'
        from /home/syndbg/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/provider.rb:101:in `state'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/machine.rb:526:in `state'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/machine.rb:146:in `initialize'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/vagrantfile.rb:81:in `new'    
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/vagrantfile.rb:81:in `machine'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/environment.rb:716:in `machine'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/plugin/v2/command.rb:186:in `each'                                                                                              
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/plugins/commands/up/command.rb:87:in `execute'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/cli.rb:54:in `execute'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/lib/vagrant/environment.rb:291:in `cli'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/gems/vagrant-2.2.0/bin/vagrant:164:in `<top (required)>'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/bin/vagrant:23:in `load'
        from /tmp/.mount_vagranpVWNOC/usr/gembundle/bin/vagrant:23:in `<main>'
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --provider libvirt ----
```

**Comment by syndbg** [comment]
People, I've managed to fix this  by providing a manually built package.

Fix Mandatory fix is to bump embedded ruby to 2.5.3.

Relevant PR: https://github.com/hashicorp/vagrant-installers/pull/145

**Comment by chrisroberts** [comment]
@syndbg hi there. While I did find that the appimage version of Vagrant has difficulty locating the correct paths for libvirt, installing the deb package worked fine installing the building the vagrant-libvirt plugin.

**Comment by imejri** [comment]
w

**Comment by MarkGibbons** [comment]
Was able to reproduce the error.
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/891 seems relevant.  The install works when the config options are specified.  Trying to figure out how to fit those options into the cookbook.

**Comment by barbudone** [comment]
This is also documented in: [https://github.com/vagrant-libvirt/vagrant-libvirt#possible-problems-with-plugin-installation-on-linux](url), so in my case (F28), i just have to run :

`CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' GEM_HOME=~/.vagrant.d/gems GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems PATH=/opt/vagrant/embedded/bin:$PATH vagrant plugin install vagrant-libvirt`
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching: formatador-0.2.5.gem (100%)
Fetching: excon-0.64.0.gem (100%)
Fetching: fog-core-1.43.0.gem (100%)
Fetching: fog-json-1.2.0.gem (100%)
Fetching: mini_portile2-2.4.0.gem (100%)
Fetching: nokogiri-1.10.3.gem (100%)
Building native extensions.  This could take a while...
Fetching: fog-xml-0.1.3.gem (100%)
Fetching: ruby-libvirt-0.7.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: fog-libvirt-0.6.0.gem (100%)
Fetching: vagrant-libvirt-0.0.45.gem (100%)
Installed the plugin 'vagrant-libvirt (0.0.45)'!
[root@localhost vault]# vagrant plugin list
vagrant-libvirt (0.0.45, global)

**Comment by nileshzend** [comment]
Issue resolved after this package
 
# yum install libvirt-devel
