### ISSUE TITLE
"vagrant ssh" and "vagrant reload" must display user-friendly message if user is not root

### ISSUE THREAD

**Issue by vhosakot** [mitchellh/vagrant#7042]
I'm using Vagrant 1.8.1 on Ubuntu 14.04.

If the user is not root or if the user does not have the right permissions, "vagrant ssh" and "vagrant reload" must display a user-friendly message instead of the following errors that are tough to understand.

```
**$ vagrant reload**
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:309:in `initialize': Permission denied @ rb_sysopen - /home/me/.vagrant.d/data/machine-index/index (Errno::EACCES)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:309:in `open'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:309:in `open'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:309:in `unlocked_save'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:227:in `block (2 levels) in set'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:323:in `block in with_index_lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:321:in `open'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:321:in `with_index_lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:192:in `block in set'
    from /opt/vagrant/embedded/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:191:in `set'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:511:in `state'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:144:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `machine'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:663:in `machine'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:210:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:210:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:209:in `map'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:209:in `with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/reload/command.rb:37:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

```
**$ vagrant ssh**
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:309:in `initialize': Permission denied @ rb_sysopen - /home/me/.vagrant.d/data/machine-index/index (Errno::EACCES)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:309:in `open'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:309:in `open'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:309:in `unlocked_save'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:227:in `block (2 levels) in set'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:323:in `block in with_index_lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:321:in `open'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:321:in `with_index_lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:192:in `block in set'
    from /opt/vagrant/embedded/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine_index.rb:191:in `set'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:511:in `state'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:144:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `machine'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:663:in `machine'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:210:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:210:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:209:in `map'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:209:in `with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/ssh/command.rb:41:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

```
**$ vagrant --version**
Vagrant 1.8.1
```

**Comment by sethvargo** [comment]
Hi @vhosakot 

This error is most commonly caused when someone runs `sudo vagrant COMMAND` which changes the permissions on the `.vagrant.d` directory.

**Comment by vhosakot** [comment]
Can't Vagrant display a user-friendly message instead of these errors that are tough to understand ?

**Comment by briancain** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
