### ISSUE TITLE
  // , Bad Box Names Break The $ vagrant box list Subcommand

### ISSUE THREAD

**Issue by v6** [mitchellh/vagrant#7118]
// , I'm at that intermediate stage where I'm ignorant enough to break things, but knowledgeable enough to know what broke.
### Vagrant version

```
$ vagrant --version
Vagrant 1.8.1
```
### Host operating system

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.3
BuildVersion:   15D21
```
### Guest operating system

`Puppetlabs CentOS 6.4 x86_64, VBox 4.2.10`
### Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
  config.vm.network "forwarded_port", guest: 8080, host: 7071
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1024"
  end
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "default.pp"
    puppet.module_path = "modules"
    puppet.hiera_config_path = "hiera.yaml"
  end
end
```
### Debug output

Something ain't right here...

```
$ vagrant box list
centos/7                                                              (virtualbox, 1509.01)
hashicorp/boot2docker                                                 (virtualbox, 1.7.8)
hashicorp/precise32                                                   (virtualbox, 1.0.0)
http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box (virtualbox, 0)
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/box/command/list.rb:55:in `block in list_boxes': undefined method `directory' for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/box/command/list.rb:47:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/box/command/list.rb:47:in `list_boxes'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/box/command/list.rb:30:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/box/command/root.rb:61:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

It made a box _named_ after what should have been the _config.vm.box_url_. 

I tried to remove the offending box.

No dice. 

```
$ vagrant box remove 'http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_remove.rb:81:in `block in call': undefined method `in_use?' for nil:NilClass (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_remove.rb:75:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_remove.rb:75:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/box/command/remove.rb:52:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/box/command/root.rb:61:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. Do NOT paste the debug
output in the issue, just paste the link to the Gist.
### Expected behavior

The boxes should have displayed, or the the `vagrant box` subcommand should have warned about an improperly named box.
### Actual behavior

`vagrant box` had a fatal error, did not display its full output, and did not allow deletion of the Vagrant Box with the offending name.
### Steps to reproduce

1.Yes, I know, I made a rather bone-headed mistake. 

I used a Vagrantfile that had a long HTTP link labeled `config.vm.box = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"`, when it should have been `config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"`
1. I quickly corrected this in the Vagrantfile. 
2. Vagrant happily vagranted along, however, until one day when I attempted to use `$ vagrant box list`. 
3. I immediately... OK, I mean a long time later, I finally thought to check `~/.vagrant.d/boxes`. 

```
$ cd ~/.vagrant.d/boxes
$ ls
centos-VAGRANTSLASH-7
hashicorp-VAGRANTSLASH-boot2docker
hashicorp-VAGRANTSLASH-precise32
http-VAGRANTCOLON--VAGRANTSLASH--VAGRANTSLASH-puppet-vagrant-boxes.puppetlabs.com-VAGRANTSLASH-centos-64-x64-vbox4210.box
packer_messenger_server_virtualbox
puppetlabs-VAGRANTSLASH-centos-6.6-32-puppet
puppetlabs-VAGRANTSLASH-centos-7.0-64-puppet-enterprise
puppetlabs-VAGRANTSLASH-centos-7.2-64-puppet
ubuntu-VAGRANTSLASH-trusty64
vStone-VAGRANTSLASH-centos-7.x-puppet.3.x
```

That has to be the longest, silliest name for a Vagrant box I have seen in a long time.
### Workaround

Removing the long folder fixed the problem.

```
$ rm -r http-VAGRANTCOLON--VAGRANTSLASH--VAGRANTSLASH-puppet-vagrant-boxes.puppetlabs.com-VAGRANTSLASH-centos-64-x64-vbox4210.box/
NBASANES-M-DC9Y:boxes nbasanes$ vagrant box list
centos/7                                   (virtualbox, 1509.01)
hashicorp/boot2docker                      (virtualbox, 1.7.8)
hashicorp/precise32                        (virtualbox, 1.0.0)
packer_messenger_server_virtualbox         (virtualbox, 0)
puppetlabs/centos-6.6-32-puppet            (virtualbox, 1.0.1)
puppetlabs/centos-6.6-32-puppet            (virtualbox, 1.0.2)
puppetlabs/centos-7.0-64-puppet-enterprise (virtualbox, 1.0.2)
puppetlabs/centos-7.2-64-puppet            (virtualbox, 1.0.0)
ubuntu/trusty64                            (virtualbox, 20160201.0.0)
vStone/centos-7.x-puppet.3.x               (virtualbox, 5.0.0.1)
```
### References

I found the box that broke this here: http://www.vagrantbox.es/

Are there any other GitHub issues (open or closed) that should be linked here?
These seem vaguely related to checking box names:
- https://github.com/mitchellh/vagrant/issues/1722
- https://github.com/mitchellh/vagrant/pull/5514
- https://github.com/mitchellh/vagrant/search?q=bad+box+names&type=Issues&utf8=%E2%9C%93

**Comment by briancain** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

For more information, I've added a warning that is displayed now to the user if they accidentally use a URL for the box name.

Cheers!
