### ISSUE TITLE
`vagrant reload` causes RuntimeError in scp.rb: 'await_response_state'

### ISSUE THREAD

**Issue by hovissimo** [mitchellh/vagrant#7183]
I'm having the same issue as #6319

Host is Windows 10 Home

See https://gist.github.com/hovissimo/bc367f10b5f432f06bff for error report.

```
$vagrant plugin list
vagrant-share (1.1.5, system)
```

```
$vagrant -v
Vagrant 1.8.1
```

```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.provision :shell, path: "vagrant/provision_common.sh"
  config.vm.network "private_network", type: "dhcp"
  #config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.define "dev" do |dev|
    dev.vm.box = "ubuntu/trusty64"
    dev.vm.provision :shell, path: "vagrant/provision_dev.sh"
    dev.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end

  config.ssh.forward_agent = true
end
```

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Comment by hovissimo** [comment]
Yeah, my Vagrantfile is largely unchanged from what I posted here, and I haven't had this error or thought about this in forever.  Thanks for cleaning up the old ticket.

**Comment by ryancwalsh** [comment]
Unfortunately I'm getting this error now (using Laravel Homestead).

Everything was working fine for me for months or years, but I turned my Windows PC off last night, came in to boot it up today and run `vagrant up` as usual, and suddenly I'm getting this:

```
 vboxHomestead: Guest Additions Version: 6.0.0 r127566
    vboxHomestead: VirtualBox Version: 6.1
==> vboxHomestead: Setting hostname...
==> vboxHomestead: Configuring and enabling network interfaces...
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-scp-1.2.1/lib/net/scp.rb:398:in `await_response_state': Agent pid 3478 (RuntimeError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-scp-1.2.1/lib/net/scp.rb:386:in `await_response'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-scp-1.2.1/lib/net/scp/upload.rb:25:in `upload_start_state'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/channel.rb:323:in `process'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:250:in `block in ev_preprocess'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:540:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:540:in `each_channel'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:250:in `ev_preprocess'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/event_loop.rb:101:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/event_loop.rb:101:in `ev_preprocess'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/event_loop.rb:29:in `process'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:228:in `process'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:181:in `block in loop'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:181:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:181:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/channel.rb:272:in `wait'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-scp-1.2.1/lib/net/scp.rb:284:in `upload!'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:327:in `block (2 levels) in upload'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:333:in `block in upload'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:742:in `block in scp_connect'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:382:in `connect'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:740:in `scp_connect'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:303:in `upload'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/guests/debian/cap/configure_networks.rb:182:in `block in upload_tmp_file'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/tempfile.rb:295:in `open'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/guests/debian/cap/configure_networks.rb:177:in `upload_tmp_file'
```
