### ISSUE TITLE
Vagrant up error on OSX El Capitan (similar to #2940)

### ISSUE THREAD

**Issue by cappelaere** [mitchellh/vagrant#7186]
Did try to re-install vagrant and unset  DYLD_LIBRARY_PATH.
Not sure what to do at this point?
Thanks.
Pat.

```shell
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty32' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
/opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient.rb:2:in `require': dlopen(/opt/vagrant/embedded/lib/ruby/2.2.0/universal-darwin12.0/zlib.bundle, 9): Library not loaded: @rpath/libz.dylib (LoadError)
  Referenced from: /opt/vagrant/embedded/lib/ruby/2.2.0/universal-darwin12.0/zlib.bundle
  Reason: Incompatible library version: zlib.bundle requires version 1.0.0 or later, but libz.dylib provides version 0.0.0 - /opt/vagrant/embedded/lib/ruby/2.2.0/universal-darwin12.0/zlib.bundle
	from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient.rb:2:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/rest_client.rb:2:in `require'
	from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/rest_client.rb:2:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/login/client.rb:1:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/login/client.rb:1:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/login/middleware/add_authentication.rb:4:in `require_relative'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/login/middleware/add_authentication.rb:4:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/login/plugin.rb:21:in `require_relative'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/login/plugin.rb:21:in `block in <class:Plugin>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:42:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:42:in `block (2 levels) in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:41:in `tap'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:41:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:40:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:40:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:473:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_add.rb:67:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_add.rb:67:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:82:in `handle_box'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by cappelaere** [comment]
Found the culprit... old library in the path... but I do not understand how it got picked up.  Weird.

**Comment by sethvargo** [comment]
Hi @cappelaere 

Thank you for opening an issue. That's definitely weird. Can you please share how you installed/upgraded Vagrant? Have you altered the vendored Ruby in any way or do you export global DYLD_LIBRARY_PATH for other software compilation? Might be an issue for mitchellh/vagrant-installers, but without a repro case, it might be hard to fix :frowning:

**Comment by cappelaere** [comment]
Hi Seith,
I installed vagrant from the site download button onto the Mac.
I have not customized my vendor Ruby (nor worked with ruby in a long while)
I had unset my DYLD_LIBRARY_PATH

I did a locate libz.dylib
and found the “bad” library in some weird directory and removed it.
Not sure how it got pulled in though…. Grrr!
Thanks,
Pat.

Pat Cappelaere
pat@cappelaere.com

Cell: 410 340 4868
Skype: patrice_cappelaere
gmail: cappelaere@gmail.com

**Comment by sethvargo** [comment]
Hey @cappelaere 

Thank you for your reply. I'm not really sure how it got their either, but without a widespread report or a repro case, I think this is an isolated incident. I'm going to close this issue (it's already indexed by the Google), so if more people start experiencing this, we can spend time digging. Thanks! :smile:
