### ISSUE TITLE
`provider': wrong number of arguments (0 for 1) (ArgumentError)

### ISSUE THREAD

**Issue by hus787** [mitchellh/vagrant#7199]
### Vagrant version

1.8.1
### Host operating system

System Version: OS X 10.11.3 
Kernel Version: Darwin 15.3.0
Model Name: MacBook Air
### Guest operating system

"hashicorp/precise64"
### Vagrantfile

``` ruby
# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

# Require 'yaml' module
require 'yaml'

# Read details of containers to be created from YAML file
# Be sure to edit 'containers.yml' to provide container details
containers = YAML.load_file('Vagrant/containers.yml')
envvars_dev = YAML.load_file('Vagrant/envvar_dev.yml')
envvars_test = YAML.load_file('Vagrant/envvar_test.yml')

# Create and configure the Docker container(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Perform one-time configuration of Docker provider to specify
  # location of Vagrantfile for host VM; comment out this section
  # to use default boot2docker box
  config.vm.provider "docker" do |docker|
    docker.vagrant_vagrantfile = "Vagrant/Vagrantfile"
  end

  # Iterate through the entries in the YAML file
  containers.each do |container|
    config.vm.define container["name"] do |cntnr|

      # Configure the Docker provider for Vagrant
      cntnr.vm.provider "docker" do |dockerdep|

        # Specify the Docker image to use, pull value from YAML file
        dockerdep.image = container["image"]

        # Specify port mappings, pull value from YAML file
        # If omitted, no ports are mapped!
        dockerdep.ports = container["ports"]

        # Specify a friendly name for the Docker container, pull from YAML file
        dockerdep.name = container["name"]
      end
    end
  end
  config.vm.define "backend" do |cntnr|
    cntnr.vm.synced_folder ".", "/go/smarpshare/backend"
    cntnr.vm.synced_folder "../frontend", "/go/smarpshare/frontend"

    # Configure the Docker provider for Vagrant
    cntnr.vm.provider "docker" do |docker|
      docker.image = 'golang'
      # Specify port mappings, pull value from YAML file
      # If omitted, no ports are mapped!
      docker.ports = ['8001:8001']
      # Specify a friendly name for the Docker container, pull from YAML file
      docker.name = 'docker-backend'
      envvars_dev.each do |envvar|    
        docker.env[envvar["key"]] = envvar["value"]
      end
      # Iterate through the entries in the YAML file
      # populate the env vars
      containers.each do |container|    
        docker.link "#{container["name"]}:#{container["name"]}"
      end
      docker.stop_timeout = 5
      docker.cmd = ["sh", "./smarpshare/backend/Vagrant/local.sh"]
    end
  end

  # For testing
  config.vm.define "beTest" do |cntnr|
    cntnr.vm.synced_folder ".", "/go/smarpshare/backend"
    cntnr.vm.provider "docker" do |docker|
      docker.image = 'golang'
      docker.name = 'docker-backend-tester'
      envvars_test.each do |envvar|    
        docker.env[envvar["key"]] = envvar["value"]
      end
      containers.each do |container|    
        docker.link "#{container["name"]}:#{container["name"]}"
      end
      docker.stop_timeout = 5
      docker.cmd = ["sh", "./smarpshare/backend/Vagrant/test.sh"]
    end
  end
end
```

Vagrant/Vagrantfile:

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Create and configure the VM(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Assign a friendly name to this host VM
  config.vm.hostname = "docker-host"

  # Skip checking for an updated Vagrant box
  config.vm.box_check_update = false

  # Always use Vagrant's default insecure key
  config.ssh.insert_key = false

  # Spin up a "host box" for use with the Docker provider
  # and then provision it with Docker
  config.vm.box = "hashicorp/precise64"
  config.vm.provision "docker"
  config.vm.network "forwarded_port", guest: 28765, host: 28765
  config.vm.network "forwarded_port", guest: 8001, host: 8001
  # Disable synced folders (prevents an NFS error on "vagrant up")
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider.customize ['modifyvm', :id, '--memory', 4096]
end

```
### Debug output

https://gist.github.com/hus787/8f4be97948f65e8fd7bdb57e2e38239c
### Expected behavior

Get the vagrant up. Same happened in with most of the other commands.
### Actual behavior

```
$ vagrant up
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/kernel_v2/config/vm.rb:271:in `provider': wrong number of arguments (0 for 1) (ArgumentError)
    from /Users/hussainparsaiyan/development/smarpshare/backend/Vagrant/Vagrantfile:28:in `block in <top (required)>'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/loader.rb:37:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/loader.rb:37:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:113:in `block (2 levels) in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:107:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:107:in `block in load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:104:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:104:in `load'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:28:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:740:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:740:in `vagrantfile'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:325:in `default_provider'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/docker/provider.rb:98:in `block in host_vm'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/docker/provider.rb:84:in `host_vm'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/docker/provider.rb:159:in `state'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:501:in `state'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:144:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `machine'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:663:in `machine'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:210:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:210:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:209:in `map'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:209:in `with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/status/command.rb:20:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

**Comment by chrisroberts** [comment]
Hi. The error is occurring due to this invalid line in your Vagrantfile:

```ruby
config.vm.provider.customize ['modifyvm', :id, '--memory', 4096]
```

Cheers!

**Comment by moatazelmasry2** [comment]
@chrisroberts  what is the correct way then? This is written exactly like this in the vagrant documentation....
