### ISSUE TITLE
AWS: The synced folder type 'nfs' is reporting as unusable

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#7430]
Vagrant 1.8.1 on OS X 10.11.2 with this [Vagrantfile](https://github.com/EA31337/FX-MT-VM/blob/e7c5cc5f64f29c2befa056e6807a68b331a4f203/Vagrantfile).

I've configured NFS folder as below:

    config.vm.synced_folder ".", "/vagrant", id: "core", nfs: true

Then when I run:

    PROVIDER=aws PRIVATE_KEY=my_key.pem vagrant up --provider=aws

I've got the error:

```
Bringing machine 'mt-aws' up with 'aws' provider...
The synced folder type 'nfs' is reporting as unusable for
your current setup. Please verify you have all the proper
prerequisites for using this shared folder type and try again.
```

I've already added:

    override.nfs.functional = false

for AWS provider as suggested in #1437.

Debug:

```
INFO warden: Calling OUT action: #<VagrantPlugins::Triggers::Action::Trigger:0x000001028e4178>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::SyncedFolderUnusable: The synced folder type 'nfs' is reporting as unusable for
your current setup. Please verify you have all the proper
prerequisites for using this shared folder type and try again.>
ERROR vagrant: The synced folder type 'nfs' is reporting as unusable for
your current setup. Please verify you have all the proper
prerequisites for using this shared folder type and try again.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/mixin_synced_folders.rb:144:in `block in synced_folders'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/mixin_synced_folders.rb:125:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/mixin_synced_folders.rb:125:in `synced_folders'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/synced_folders.rb:27:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/kenorb/.vagrant.d/gems/gems/vagrant-bindfs-0.4.7/lib/vagrant-bindfs/bind.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/kenorb/.vagrant.d/gems/gems/vagrant-proxyconf-1.5.2/lib/vagrant-proxyconf/action/only_once.rb:21:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/kenorb/.vagrant.d/gems/gems/vagrant-cachier-1.2.1/lib/vagrant-cachier/action/install_buckets.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/kenorb/.vagrant.d/gems/gems/vagrant-bindfs-0.4.7/lib/vagrant-bindfs/bind.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/kenorb/.vagrant.d/gems/gems/vagrant-cachier-1.2.1/lib/vagrant-cachier/action/configure_bucket_root.rb:20:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
...
```

Related: #1437, #5618, #6968

I've also tried to specify security group which allows port 2049 (TCP&UDP), but it didn't help. Running debug log, doesn't help much. And the above error message is not self-explanatory.

**Comment by sethvargo** [comment]
Hi @kenorb 

There are a number of requirements to use NFS. Both the host and guest must support it, and the guest must have nfsd installed. I'm betting the AMI you are using does not have nfsd pre-installed or it's using an incompatible version of nfsd. I think this is a bug in the vagrant-aws provider - would you mind opening a bug over there please?
