### ISSUE TITLE
Debian NFS networking using private network DHCP fails

### ISSUE THREAD

**Issue by foxx** [mitchellh/vagrant#7433]
```
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Enable NFS for OS X hosts, offers huge speed improvements
  config.vm.synced_folder ".", "/opt/code", type: "nfs"
  config.vm.network "private_network", type: "dhcp"
```

```
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.
```

```
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000101cfbcf8>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::NFSNoGuestIP: No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.>
ERROR vagrant: No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:131:in `rescue in read_dynamic_machine_ip'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:116:in `read_dynamic_machine_ip'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:44:in `add_ips_to_env!'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:29:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:49:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/env_set.rb:19:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/box_check_outdated.rb:78:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/match_mac_address.rb:19:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/import.rb:74:in `import'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/import.rb:13:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/customize.rb:40:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/machine.rb:225:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/machine.rb:200:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/environment.rb:561:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/machine.rb:186:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/machine.rb:186:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.
No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.
 INFO interface: Machine: error-exit ["Vagrant::Errors::NFSNoGuestIP", "No guest IP was given to the Vagrant core NFS helper. This is an\ninternal error that should be reported as a bug."]
```

**Comment by sethvargo** [comment]
Hi @foxx

Can you try assigning a private ip instead of using dhcp?

**Comment by foxx** [comment]
Static IP seems to work fine, although not a viable solution for us as different developers have different internal network configs that may overlap.

Using `trusty64` also seems to work with DHCP, so the issue would appear to be isolated to `xenial64`.

**Comment by foxx** [comment]
I also can't test with VMWare Fusion because there isn't a maintained or working `xenial64` image for it :/

**Comment by sethvargo** [comment]
@foxx try bento

I'm betting is a strange networking issue. I'll look into it.

**Comment by sethvargo** [comment]
Okay, I spent a few hours this morning trying to figure this out. I'm able to reproduce the issue, but I'm really leaning towards this being an upstream box issue. I can also confirm the issue does not reproduce on older ubuntu versions, nor does it reproduce on the `bento/ubuntu-16.04` box.

A little background - when you specify a private network as DHCP, we rely on vbox to assign the IP. After the machine boots, the IP is a property of the guest. For example. here is the output of the guest properties for `ubuntu/trusty64`:

```
VBoxManage guestproperty enumerate 0fc65240-307e-4b57-a32c-e27e7efe2df2
Name: /VirtualBox/GuestInfo/OS/Product, value: Linux, timestamp: 1466354493047348000, flags:
Name: /VirtualBox/GuestInfo/Net/0/V4/IP, value: 10.0.2.15, timestamp: 1466354493053854000, flags:
Name: /VirtualBox/GuestInfo/Net/0/MAC, value: 0800278B9ED0, timestamp: 1466354493055238000, flags:
Name: /VirtualBox/GuestInfo/OS/ServicePack, value: , timestamp: 1466354493047806000, flags:
Name: /VirtualBox/HostInfo/VBoxVerExt, value: 5.0.22, timestamp: 1466354481198167000, flags: TRANSIENT, RDONLYGUEST
Name: /VirtualBox/GuestInfo/Net/1/Status, value: Up, timestamp: 1466354503059277000, flags:
Name: /VirtualBox/GuestInfo/Net/1/V4/Broadcast, value: 172.28.128.255, timestamp: 1466354503058628000, flags:
Name: /VirtualBox/GuestInfo/Net/0/V4/Netmask, value: 255.255.255.0, timestamp: 1466354493055167000, flags:
Name: /VirtualBox/GuestInfo/Net/1/V4/Netmask, value: 255.255.255.0, timestamp: 1466354503058866000, flags:
Name: /VirtualBox/GuestInfo/Net/1/MAC, value: 08002766468F, timestamp: 1466354503059068000, flags:
Name: /VirtualBox/GuestInfo/OS/Version, value: #133-Ubuntu SMP Tue May 24 18:32:09 UTC 2016, timestamp: 1466354493047644000, flags:
Name: /VirtualBox/GuestAdd/VersionExt, value: 4.3.36_Ubuntu, timestamp: 1466354493049438000, flags:
Name: /VirtualBox/GuestAdd/Revision, value: 105129, timestamp: 1466354493049641000, flags:
Name: /VirtualBox/HostGuest/SysprepExec, value: , timestamp: 1466354481197705000, flags: TRANSIENT, RDONLYGUEST
Name: /VirtualBox/GuestInfo/OS/LoggedInUsers, value: 0, timestamp: 1466354493051263000, flags: TRANSIENT, TRANSRESET
Name: /VirtualBox/GuestInfo/Net/0/Status, value: Up, timestamp: 1466354493055297000, flags:
Name: /VirtualBox/HostGuest/SysprepArgs, value: , timestamp: 1466354481197750000, flags: TRANSIENT, RDONLYGUEST
Name: /VirtualBox/GuestAdd/Version, value: 4.3.36, timestamp: 1466354493049357000, flags:
Name: /VirtualBox/HostInfo/VBoxRev, value: 108108, timestamp: 1466354481198221000, flags: TRANSIENT, RDONLYGUEST
Name: /VirtualBox/GuestInfo/Net/0/V4/Broadcast, value: 10.0.2.255, timestamp: 1466354493054016000, flags:
Name: /VirtualBox/HostInfo/VBoxVer, value: 5.0.22, timestamp: 1466354481198123000, flags: TRANSIENT, RDONLYGUEST
Name: /VirtualBox/GuestInfo/Net/1/V4/IP, value: 172.28.128.3, timestamp: 1466354503058324000, flags:
Name: /VirtualBox/GuestInfo/Net/Count, value: 2, timestamp: 1466354533073374000, flags:
Name: /VirtualBox/GuestInfo/OS/Release, value: 3.13.0-87-generic, timestamp: 1466354493047461000, flags:
Name: /VirtualBox/GuestInfo/OS/NoLoggedInUsers, value: true, timestamp: 1466354493051332000, flags: TRANSIENT, TRANSRESET
```

Vagrant [reads the IP address from those properties](https://github.com/mitchellh/vagrant/blob/22c24d619cfa5b718599978b21ee92233e525e08/plugins/providers/virtualbox/driver/version_5_0.rb#L446).

Now compare that to the output of `ubuntu/xenial64`:

```
VBoxManage guestproperty enumerate a3915381-0c59-40a8-81b3-9bcfa38ea2d3
Name: /VirtualBox/HostInfo/GUI/LanguageID, value: en_US, timestamp: 1466353680850614000, flags:
Name: /VirtualBox/HostInfo/VBoxVerExt, value: 5.0.20, timestamp: 1466353050313004000, flags: TRANSIENT, RDONLYGUEST
Name: /VirtualBox/HostGuest/SysprepExec, value: , timestamp: 1466353050312616000, flags: TRANSIENT, RDONLYGUEST
Name: /VirtualBox/HostGuest/SysprepArgs, value: , timestamp: 1466353050312662000, flags: TRANSIENT, RDONLYGUEST
Name: /VirtualBox/HostInfo/VBoxRev, value: 106931, timestamp: 1466353050313028000, flags: TRANSIENT, RDONLYGUEST
Name: /VirtualBox/HostInfo/VBoxVer, value: 5.0.20, timestamp: 1466353050312976000, flags: TRANSIENT, RDONLYGUEST
```

Notice how there are no assigned network entires? If you SSH into the box, you'll have an IP, but that box is not properly registering itself with virtualbox (likely it does not have the proper vbox guest additions installed). Unfortunately there's nothing Vagrant can do here - if vbox is not reporting the assigned DHCP address, Vagrant can't mount the NFS folders.

I want to point out a few things:

1. This is not a bug in Vagrant. I understand it's not an ideal situation, but please understand that there is nothing Vagrant can do in this scenario. We might be able to provide a more informative error message, but we cannot magically create IP addresses when the guest fails to report.

2. This is not a regression. This is a bug in a new version of an operating system that is not yet well-behaved on virtualbox. There have been many bugs in vbox core related to xenial, and that's the nature of new OSes in a rapidly moving environment. Even though canonical calls 16.04 "stable", that doesn't mean the community around it is stable. If you want stability and consistency in your environments, I don't recommend always riding the latest release; you're always going to encounter issues like this.

3. Many of the virtualbox bugs have been fixed, but this partial box is also just very broken. I identified a number of other issues in my testing; if you continue to use `ubuntu/xenial64`, you're going to have a bad day. As I said above, I would highly recommend using the boxes under the `bento` namespace. They are well-built, open source (https://github.com/chef/bento), and battle-tested.

Please let me know if you have any questions.

**Comment by foxx** [comment]
Thanks for the detailed reply. I didn't realise the Bento repo also had pre-build repos, I thought it was only a set of templates for compiling your own. Assuming Bento solves all these problems, and I'll be testing it tomorrow, then it might be worth updating the docs stating that Bento is now the preferred source for boxes, although that's a separate issue.

**Comment by sethvargo** [comment]
@foxx it's already in the wiki: https://github.com/mitchellh/vagrant/wiki/Available-Vagrant-Boxes#official-boxes

**Comment by foxx** [comment]
This is pretty much the first time I've ever seen this wiki, didn't even know it existed. I've always used the docs from Vagrant [website](https://www.vagrantup.com/docs/), which is what comes up when you search google for "vagrant docs". Furthermore, there should really only be one central repository for documentation, if the website is outdated then it should redirect to the wiki.
