### ISSUE TITLE
The sharing proxy exited with a non-zero exit status! This represents an erroneous exit and likely a bug. Please report this issue.

### ISSUE THREAD

**Issue by walkingtroughunknownlands** [mitchellh/vagrant#7768]
I see this problem is discussed here and there, but nowhere it's directly said is this expected kind of behaviour of vagrant.
So, once again Is vagrant suppossed to work despite firewall blocking "higher" port numbers?
As  https://www.hashicorp.com/blog/feature-preview-vagrant-1-5-share.html states:

> Once the share is created, a relatively obscure URL is outputted. This URL will route directly to your Vagrant environment; it doesn't matter if you or accessing party is behind a firewall or NAT

So or I do not understand how to use vagrant ( yeah, I do take that into consideration ) or vagrant page is overoptimistic about what vagrant is really capable of ( more euphemistic way of saying it has lies written on it ). The third possibility is that my understanding of english sucks, and that sentence does not suggest vagrant will work despite firewall blocking almost every possible port connections that are not of _common_ trafic type.

So If proxy really _IS_ something that can prevent vagrant from functioning please state that directly on vagrant web page to prevent mass confussion of the users.
### Vagrant version

Vagrant 1.8.5
straight outta debian 32 bit package vagrantup.com site downloaded about 24 hours ago.
### Host operating system

(In)famous Debian GNU/Linux version 8 a.k.a. Jessy, 32 bit, virtualbox  taken from debian contrib
repository ( as in procedure described at: https://wiki.debian.org/VirtualBox#Debian_8_.22Jessie.22 ) 
### Guest operating system

https://atlas.hashicorp.com/debian/boxes/jessie64
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.


  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/jessie64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080


  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #  # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end

```
### Expected behavior

Sharing my precious little vagrant box trough vagrant infrastructure from computer inside some really paranoid network to the people of the world!
### Actual behavior

What actually happened?

```
vagrant share
==> default: Detecting network information for machine...
    default: Local machine address: 127.0.0.1
    default:  
    default: Note: With the local address (127.0.0.1), Vagrant Share can only
    default: share any ports you have forwarded. Assign an IP or address to your
    default: machine to expose all TCP ports. Consult the documentation
    default: for your provider ('virtualbox') for more information.
    default:  
    default: Local HTTP port: 8080
    default: Local HTTPS port: disabled
    default: Port: 2222
    default: Port: 8080
==> default: Checking authentication and authorization...
==> default: Creating Vagrant Share session...
    default: Share will be at: elite-haxor-1337
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
```

From `vagrant share--debug` ((...hundreds of lines ommited...))

```
==> default: Creating Vagrant Share session...
 INFO api: /api/v1/shares
DEBUG api: API payload: {"share":{"http_port":8080,"https_port":null,"ports":[2222,8080]}}
DEBUG api: Response: {"custom_domain":false,"expired":false,"has_private_key":false,"name":"wild-pronghorn-2195","http_port":8080,"https_port":null,"ssh_port":null,"ssh_username":null,"ports":[2222,8080],"expired_at":null,"created_at":"2016-08-30T18:17:28.755Z","private_key_password":true,"token":null,"use_key_once":true,"domain":"vagrantshare.com","full_domain":"wild-pronghorn-2195.vagrantshare.com","mux_insecure":false,"mux_client_addr":"register.vagrantshare.com:8001","mux_server_addr":"register.vagrantshare.com:8000"}
 INFO interface: detail: Share will be at: wild-pronghorn-2195
 INFO interface: detail:     default: Share will be at: wild-pronghorn-2195
    default: Share will be at: wild-pronghorn-2195
 INFO interface: Machine: share-name ["wild-pronghorn-2195", {:target=>:default}]
 INFO helper: Executing proxy: ["-share", "-name", "wild-pronghorn-2195", "-target", "127.0.0.1", "-server", "register.vagrantshare.com:8000", "-port", "8080", "-port", "2222", "-port", "8080"]
 INFO subprocess: Starting process: ["/opt/vagrant/embedded/gems/gems/vagrant-share-1.1.5/localbin/proxy_linux_386", "-share", "-name", "wild-pronghorn-2195", "-target", "127.0.0.1", "-server", "register.vagrantshare.com:8000", "-port", "8080", "-port", "2222", "-port", "8080"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: proxy:1472588546,log,[INFO] Restricting ports to: [8080 2222 8080]
proxy:1472588546,log,[DEBUG] proxy: Connecting to mux server at register.vagrantshare.com:8000
DEBUG helper: Proxy message: ["log", "[INFO] Restricting ports to: [8080 2222 8080]"]
DEBUG helper: Proxy message: ["log", "[DEBUG] proxy: Connecting to mux server at register.vagrantshare.com:8000"]
DEBUG subprocess: stdout: proxy:1472588694,log,[ERR] proxy: Failed to start sharing: Failed to connect to mux server: dial tcp 52.72.124.216:8000: connection timed out
DEBUG helper: Proxy message: ["log", "[ERR] proxy: Failed to start sharing: Failed to connect to mux server: dial tcp 52.72.124.216:8000: connection timed out"]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31852
DEBUG subprocess: Exit status: 1
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x9a156cc>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::Share::Errors::ProxyExit: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.>
ERROR vagrant: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.5/lib/vagrant-share/activate.rb:1401:in `block in execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:229:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
/opt/vagrant/embedded/gems/gems/vagrant-share-1.1.5/lib/vagrant-share/activate.rb:1178:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/cli.rb:42:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:302:in `cli'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:174:in `<main>'
 INFO interface: error: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
 INFO interface: Machine: error-exit ["VagrantPlugins::Share::Errors::ProxyExit", "The sharing proxy exited with a non-zero exit status! This represents\nan erroneous exit and likely a bug. Please report this issue."]
```

I especially reccomend your attention to those lines:

```
DEBUG helper: Proxy message: ["log", "[INFO] Restricting ports to: [8080 2222 8080]"]
DEBUG helper: Proxy message: ["log", "[DEBUG] proxy: Connecting to mux server at register.vagrantshare.com:8000"]
DEBUG subprocess: stdout: proxy:1472588694,log,[ERR] proxy: Failed to start sharing: Failed to connect to mux server: dial tcp 52.72.124.216:8000: connection timed out
DEBUG helper: Proxy message: ["log", "[ERR] proxy: Failed to start sharing: Failed to connect to mux server: dial tcp 52.72.124.216:8000: connection timed out"]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31852
DEBUG subprocess: Exit status: 1
```

It says to report issue. So I am reporting.
### Steps to reproduce
1. Be inside supper dupper paranoid network that blocks everything that is not common office/school/university type traffic ( it means it blocks initialising ( non http I assume ) connectons at 4 digit port numbers for sure  )
2. Try to "vargant share" your box
3. Et voilà!
### References
- GH-3275
- GH-5129
- GH-3309
- GH-4848

**Comment by walkingtroughunknownlands** [comment]
If it is firewall/proxy/whatever issue maybe it's worth mentioning in documentation? Just a suggestion.

**Comment by walkingtroughunknownlands** [comment]
I checked ( with wireshark ) connections to that share server at port 8000. There are tcp SYN packets outgoing from my computer, but **nothing** comes from server in return. Zero. Null. Void. Like that server do not exist.

**Comment by timbroder** [comment]
I'm experiencing this too. From home

```
goroutine 108 [IO wait]:
net.runtime_pollWait(0xc22720, 0x72, 0x0)
	/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease260794574/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc2102457d0, 0x72, 0xc10f60, 0x23)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc2102457d0, 0x23, 0xc10f60)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc210245770, 0xc21053e000, 0x8000, 0x8000, 0x0, ...)
	/usr/local/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc21025a5c8, 0xc21053e000, 0x8000, 0x8000, 0x8000, ...)
	/usr/local/go/src/pkg/net/net.go:122 +0xc5
io.Copy(0xc1c7e8, 0xc210254190, 0xc12a50, 0xc21025a5c8, 0x0, ...)
	/usr/local/go/src/pkg/io/io.go:352 +0x1c8
github.com/armon/go-socks5.proxy(0x3321a0, 0x6, 0xc1c7e8, 0xc210254190, 0xc12a50, ...)
	/Users/pearkes/code/golang/src/github.com/armon/go-socks5/request.go:306 +0x5e
created by github.com/armon/go-socks5.(*Server).handleConnect
	/Users/pearkes/code/golang/src/github.com/armon/go-socks5/request.go:159 +0xa34

 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000103334010>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::Share::Errors::ProxyExit: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.>
ERROR vagrant: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.5/lib/vagrant-share/activate.rb:1401:in `block in execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/plugin/v2/command.rb:229:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
/opt/vagrant/embedded/gems/gems/vagrant-share-1.1.5/lib/vagrant-share/activate.rb:1178:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/cli.rb:42:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/environment.rb:302:in `cli'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/bin/vagrant:174:in `<main>'
 INFO interface: error: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
```

Going to try upgrading vagrant now to see if it helps

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Comment by timbroder** [comment]
@chrisroberts what was the resolution? I am still experiencing this

**Comment by chrisroberts** [comment]
@timbroder Would you confirm the error is still occurring using the latest Vagrant release? And if so, can you provide a gist of the `--debug` output. Thanks!

**Comment by timbroder** [comment]
@chrisroberts sure will upgrade today. Can you point me to the PR that fixed this?

**Comment by chrisroberts** [comment]
@timbroder No specific PR. A new version of vagrant-share is installed in the latest release.

**Comment by mossiv** [comment]
Getting this issue on the latest version. No firewall and going through the documentation. Any suggestions?
