### ISSUE TITLE
exec command in Vagrantfile in Windows 7 x64 with Git-Bash.exe

### ISSUE THREAD

**Issue by grossmane** [mitchellh/vagrant#7770]
### Vagrant version
Vagrant 1.8.5

### Host operating system
Windows 7 64Bit Enterprise

### Guest operating system
CentOS

### Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

required_plugins = %w( vagrant-vbguest vagrant-hostmanager nugrant)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
....

end
```

### Debug output
```
$ vagrant up
C:/Daten/Projekte/Tools/vagrant-1.8.5/embedded/gems/gems/bundler-1.12.5/lib/bundler.rb:18:in `replace': Invalid argument - ruby_setenv(ACLOCAL_PATH) (Errno::EINVAL)
        from C:/Daten/Projekte/Tools/vagrant-1.8.5/embedded/gems/gems/bundler-1.12.5/lib/bundler.rb:18:in `<module:Bundler>'
        from C:/Daten/Projekte/Tools/vagrant-1.8.5/embedded/gems/gems/bundler-1.12.5/lib/bundler.rb:15:in `<top (required)>'
        from C:/Daten/Projekte/Tools/vagrant-1.8.5/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Daten/Projekte/Tools/vagrant-1.8.5/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Daten/Projekte/Tools/vagrant-1.8.5/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:7:in `<top (required)>'
        from C:/Daten/Projekte/Tools/vagrant-1.8.5/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/pre-rubygems.rb:19:in `require_relative'
        from C:/Daten/Projekte/Tools/vagrant-1.8.5/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/pre-rubygems.rb:19:in `<main>'
Bringing machine 'default' up with 'virtualbox' provider...

... normal startup process at here
```

### Expected behavior
The ruby failure shouldn't be display.

### Actual behavior
See DEBUG Output

### Steps to reproduce
1. Create a Vagrantfile see above.
2. Start Git-Bash.exe on Windows 7 64 Bit
3. Try "vagrant up"

**Comment by chrisroberts** [comment]
Does this error happen if you remove the plugin installation code from the Vagrantfile?

**Comment by grossmane** [comment]
no, without the plugin installation i get no error. the error comes from the "exec" command.

**Comment by chrisroberts** [comment]
Hi! The underlying issue here is the plugin installation happening from the `Vagrantfile` is modifying state by spawning subprocesses while the original process is still setting up. Plugins should be loaded directly via the `vagrant plugin install` command, and not invoked from the `Vagrantfile`. 

Cheers!

**Comment by eli007s** [comment]
you can try this. after you update/install the plugins restart the vagrant command so it spawns a new thread letting safely exit the current one

`exec "vagrant #{ARGV.join(' ')}"`
