### ISSUE TITLE
ansible_local provisioner stopped woring in Windows 8.1

### ISSUE THREAD

**Issue by Constantin07** [mitchellh/vagrant#7782]
### Vagrant version

Vagrant 1.8.5
### Host operating system

Windows 8.1
### Guest operating system

Official Ubuntu Server 14.04 LTS
ubuntu/trusty64
### Vagrantfile

``` ruby
...
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.sudo = true
    ansible.verbose = "vv"
    ansible.inventory_path = "inventory"
    ansible.limit = "all"
  end
...
```
### Debug output

```
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: ansible-galaxy info --help && ansible-playbook --help (sudo=false)
DEBUG ssh: stderr: ERROR! Unexpected Exception: No module named markupsafe

DEBUG ssh: stdout: the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 79, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 31, in <module>
    from jinja2 import Environment
  File "/usr/local/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe

DEBUG ssh: Exit status: 250
ERROR warden: Error occurred: The Ansible software could not be found! Please verify
that Ansible is correctly installed on your guest system.

If you haven't installed Ansible yet, please install Ansible
on your Vagrant basebox, or enable the automated setup with the
`install` option of this provisioner. Please check
https://docs.vagrantup.com/v2/provisioning/ansible_local.html
for more information.
```
### Expected behavior

The ansible_local provisioner should work fine. 
### Actual behavior

It fails with below error:

```
==> default: Cleaning up...
==> default: Running provisioner: ansible_local...
The Ansible software could not be found! Please verify
that Ansible is correctly installed on your guest system.

If you haven't installed Ansible yet, please install Ansible
on your Vagrant basebox, or enable the automated setup with the
`install` option of this provisioner. Please check
https://docs.vagrantup.com/v2/provisioning/ansible_local.html
for more information.
Provisioning of environment completed.
```
### Steps to reproduce
1. Include in Vagrantfile a provision section with 'ansible_local'
2. Run "vagrant provision <vm-name>"

**Comment by gildegoma** [comment]
Closing as this was certainly due to an upstream bug (problem with the Ansible installation on the guest system). See for instance https://github.com/ansible/ansible/issues/13570.
