### ISSUE TITLE
`vagrant share` fails with `read_nonblock': An established connection was aborted by the software in your host machine. (Errno::ECONNABORTED)

### ISSUE THREAD

**Issue by mnpenner** [mitchellh/vagrant#7832]
### Vagrant version

Vagrant 1.8.5
### Host operating system

Windows 10
### Guest operating system

Ubuntu 14.04.5 LTS
### Vagrantfile

``` ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.synced_folder '.', '/vagrant', disabled: true # let phpstorm handle uploads; prevent vagrant from nuking your local files

  config.vm.network :forwarded_port, guest: 35729, host: 35729 # livereload
  config.vm.network :forwarded_port, guest: 3306, host: 3306 # mariadb
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 8081, host: 8081 # webpack-dev-server

  config.vm.network :public_network, bridge: "Killer E2200 Gigabit Ethernet Controller" 

  config.vm.hostname = 'mysite.dev'

  config.vm.provider :virtualbox do |vb|
    vb.gui = false # change to `true` if you get "Error: Connection timeout." while booting
    vb.memory = 4096 # warning: this is higher than what our production server has
    vb.cpus = 2

    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

end

```
### Debug output

``` bash
vagrant share --debug > share.txt 2>&1
```

> https://gist.github.com/mnpenner/f3288a90e7f77162e845023ad6a4b799
### Expected behavior

Shouldn't error out. 
### Actual behavior

Errors out.
### Steps to reproduce
1. Run `vagrant share`
### References

Are there any other GitHub issues (open or closed) that should be linked here?

Couldn't find any for keywords "share" or "ECONNABORTED"

**Comment by chrisroberts** [comment]
Hi @mnpenner! Can you confirm if you are still encountering this issue with the latest Vagrant release? Thanks!

**Comment by mnpenner** [comment]
I should have some time to upgrade and test tomorrow morning; I will report back then. Thanks for replying!

**Comment by mnpenner** [comment]
Just installed Vagrant 1.9.1. Still getting the same problem:

```
> vagrant share
==> default: Detecting network information for machine...
    default: Local machine address: 127.0.0.1
    default:
    default: Note: With the local address (127.0.0.1), Vagrant Share can only
    default: share any ports you have forwarded. Assign an IP or address to your
    default: machine to expose all TCP ports. Consult the documentation
    default: for your provider ('virtualbox') for more information.
    default:
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock': An established connection was aborted by the software in your host machine. (Errno::ECONNABORTED)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/http.rb:1384:in `request'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/rest-client-2.0.0-x86-mingw32/lib/restclient/request.rb:499:in `net_http_do_request'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/rest-client-2.0.0-x86-mingw32/lib/restclient/request.rb:772:in `block in transmit'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/http.rb:853:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/rest-client-2.0.0-x86-mingw32/lib/restclient/request.rb:766:in `transmit'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/rest-client-2.0.0-x86-mingw32/lib/restclient/request.rb:215:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/rest-client-2.0.0-x86-mingw32/lib/restclient/request.rb:52:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-share-1.1.6/lib/vagrant-share/activate.rb:535:in `block (2 levels) in http_url?'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-share-1.1.6/lib/vagrant-share/activate.rb:534:in `block in http_url?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/retryable.rb:17:in `retryable'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-share-1.1.6/lib/vagrant-share/activate.rb:533:in `http_url?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-share-1.1.6/lib/vagrant-share/activate.rb:342:in `block (2 levels) in detect_forwarded_ports'
```

**Comment by willmurphyscode** [comment]
I am experiencing the same issue, using vagrant 1.9.1 on Windows 10. I have two vagrant boxes, one exhibits this problem and one doesn't.

Works as expected: `config.vm.box = "hashicorp/precise64`
Errors out on `vagrant share` but otherwise works ok: `config.vm.box = "leopard/rwtrusty64"`

The main difference between the two boxes is Ubuntu version. The working one is precise 12.04 and the broken one is trusty 14.04. The broken box also has some rails stuff installed, while the working one does not.

**Comment by icaroscherma** [comment]
Replacing the 3 files works for me... seems that is related to a possible insecure key in ssh... =x

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Comment by PauZoffoli** [comment]
i'm having this problem
