### ISSUE TITLE
Embedded OpenSSL requires SSL_CERT_FILE to be set on Linux

### ISSUE THREAD

**Issue by randomvariable** [mitchellh/vagrant#8067]
Embedded OpenSSL requires SSL_CERT_FILE to be set on Linux

### Vagrant version
Vagrant 1.9

### Host operating system
```
NAME=Fedora
VERSION="24 (Workstation Edition)"
ID=fedora
VERSION_ID=24
```

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
https://gist.github.com/randomvariable/051d8514b6d9d5bdfa9c6e673f73d26e

### Expected behavior
What should have happened?
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Fetching: formatador-0.2.5.gem (100%)
Fetching: excon-0.54.0.gem (100%)
Fetching: fog-core-1.43.0.gem (100%)
Fetching: fog-xml-0.1.2.gem (100%)
Fetching: fog-json-1.0.2.gem (100%)
Fetching: fog-libvirt-0.3.0.gem (100%)
Fetching: vagrant-libvirt-0.0.36.gem (100%)
Installed the plugin 'vagrant-libvirt (0.0.36)'!
```

### Actual behavior
What actually happened?
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'fog-core' (>= 0) among 45 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/opt/vagrant/embedded/gems', execute `gem env` for more information
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1311:in `block in activate_dependencies'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:297:in `block in activate_solution'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:294:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:294:in `activate_solution'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:249:in `internal_install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:104:in `install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:72:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/action/install_gem.rb:37:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:32:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:31:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:31:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/environment.rb:308:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/bin/vagrant:123:in `<main>'
```

### Steps to reproduce
1. `vagrant plugin install fog-core` or `vagrant plugin install vagrant-libvirt`

### References
Broken since #8011 . Localised to `bundler.rb` in  commit [818f7acb7b01e93c862cff90e7713866fee18865](https://github.com/mitchellh/vagrant/commit/818f7acb7b01e93c862cff90e7713866fee18865)

**Comment by randomvariable** [comment]
Actually, getting SSL errors when not in root environment, so it's related to https://github.com/mitchellh/vagrant/issues/7780

**Comment by nervo** [comment]
Could https://github.com/vagrant-landrush/landrush/issues/292 be related to this ?

**Comment by randomvariable** [comment]
OK. This is resolved. SSL_CERT_FILE environment variable must be present. Had SSL_CERTFILE instead, for reasons [best left unexplained](https://www.github.com/PowerShell/PowerShell).

**Comment by randomvariable** [comment]
Actually, I'm reopening this. The only reason SSL_CERT_FILE would have been set up on my system, even for the root user is a consequence of having installed nix. This isn't set up by default.

**Comment by randomvariable** [comment]
Strace at https://gist.github.com/randomvariable/c199277533356d0b7a6b40e6dcfa70f0

**Comment by randomvariable** [comment]
Not convinced that SSL_CERT_FILE's non-presence is the only issue, as I can repeatedly produce the original error above without Rubygems being contacted. Needs a bit more work to figure out the conditions under which it fails.

**Comment by chrisroberts** [comment]
@randomvariable see #8068 which may be related

**Comment by ruzickap** [comment]
I'm having the same problem on Fedora 25.

**Comment by chrisroberts** [comment]
@randomvariable are you seeing native extensions not being built with #8068 applied (using vagrant version 1.9.1) ?

**Comment by randomvariable** [comment]
vagrant-libvirt succeeds, but gherkin does not with:
```
Ignoring gherkin-2.12.2 because its extensions are not built.  Try: gem pristine gherkin --version 2.12.2
```
This is as a dependency of https://github.com/scalefactory/vagrant-cucumber/blob/master/vagrant-cucumber.gemspec

**Comment by randomvariable** [comment]
The gemspec that gets written out seems strange. It gets treated as a binary file by diff and git. The `^@`s seem to be invalid utf-8 characters. Trying to get the character encoding reports ASCII (using `file -bi`.

``` ruby
# -*- encoding: utf-8 -*-
# stub: gherkin 2.12.2 ruby lib
# stub: ext/gherkin_lexer_ar/extconf.rb^@ext/gherkin_lexer_bg/extconf.rb^@ext/gherkin_lexer_bm/extconf.rb^@ext/gherkin_lexer_ca/extconf.rb^@ext/gherkin_lexer_cs/extconf.rb^@ext/gherkin_lexer_cy_gb/extconf.rb^@ext/gherkin_lexer_da/extconf.rb^@ext/gherkin_lexer_de/extconf.rb^@ext/gherkin_lexer_el/extconf.rb^@ext/gherkin_lexer_en/extconf.rb^@ext/gherkin_lexer_en_au/extconf.rb^@ext/gherkin_lexer_en_lol/extconf.rb^@ext/gherkin_lexer_en_old/extconf.rb^@ext/gherkin_lexer_en_pirate/extconf.rb^@ext/gherkin_lexer_en_scouse/extconf.rb^@ext/gherkin_lexer_en_tx/extconf.rb^@ext/gherkin_lexer_eo/extconf.rb^@ext/gherkin_lexer_es/extconf.rb^@ext/gherkin_lexer_et/extconf.rb^@ext/gherkin_lexer_fa/extconf.rb^@ext/gherkin_lexer_fi/extconf.rb^@ext/gherkin_lexer_fr/extconf.rb^@ext/gherkin_lexer_gl/extconf.rb^@ext/gherkin_lexer_he/extconf.rb^@ext/gherkin_lexer_hi/extconf.rb^@ext/gherkin_lexer_hr/extconf.rb^@ext/gherkin_lexer_hu/extconf.rb^@ext/gherkin_lexer_id/extconf.rb^@ext/gherkin_lexer_is/extconf.rb^@ext/gherkin_lexer_it/extconf.rb^@ext/gherkin_lexer_ja/extconf.rb^@ext/gherkin_lexer_kn/extconf.rb^@ext/gherkin_lexer_ko/extconf.rb^@ext/gherkin_lexer_lt/extconf.rb^@ext/gherkin_lexer_lu/extconf.rb^@ext/gherkin_lexer_lv/extconf.rb^@ext/gherkin_lexer_nl/extconf.rb^@ext/gherkin_lexer_no/extconf.rb^@ext/gherkin_lexer_pa/extconf.rb^@ext/gherkin_lexer_pl/extconf.rb^@ext/gherkin_lexer_pt/extconf.rb^@ext/gherkin_lexer_ro/extconf.rb^@ext/gherkin_lexer_ru/extconf.rb^@ext/gherkin_lexer_sk/extconf.rb^@ext/gherkin_lexer_sr_cyrl/extconf.rb^@ext/gherkin_lexer_sr_latn/extconf.rb^@ext/gherkin_lexer_sv/extconf.rb^@ext/gherkin_lexer_th/extconf.rb^@ext/gherkin_lexer_tl/extconf.rb^@ext/gherkin_lexer_tr/extconf.rb^@ext/gherkin_lexer_tt/extconf.rb^@ext/gherkin_lexer_uk/extconf.rb^@ext/gherkin_lexer_uz/extconf.rb^@ext/gherkin_lexer_vi/extconf.rb^@ext/gherkin_lexer_zh_cn/extconf.rb^@ext/gherkin_lexer_zh_tw/extconf.rb

Gem::Specification.new do |s|
  s.name = "gherkin"
  s.version = "2.12.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Mike Sassak", "Gregory Hnatiuk", "Aslak Helles\u{f8}y"]
  s.date = "2013-10-12"
  s.description = "A fast Gherkin lexer/parser based on the Ragel State Machine Compiler."
  s.email = "cukes@googlegroups.com"
  s.extensions = ["ext/gherkin_lexer_ar/extconf.rb", "ext/gherkin_lexer_bg/extconf.rb", "ext/gherkin_lexer_bm/extconf.rb", "ext/gherkin_lexer_ca/extconf.rb", "ext/gherkin_lexer_cs/extconf.rb", "ext/gherkin_lexer_cy_gb/extconf.rb", "ext/gherkin_lexer_da/extconf.rb", "ext/gherkin_lexer_de/extconf.rb", "ext/gherkin_lexer_el/extconf.rb", "ext/gherkin_lexer_en/extconf.rb", "ext/gherkin_lexer_en_au/extconf.rb", "ext/gherkin_lexer_en_lol/extconf.rb", "ext/gherkin_lexer_en_old/extconf.rb", "ext/gherkin_lexer_en_pirate/extconf.rb", "ext/gherkin_lexer_en_scouse/extconf.rb", "ext/gherkin_lexer_en_tx/extconf.rb", "ext/gherkin_lexer_eo/extconf.rb", "ext/gherkin_lexer_es/extconf.rb", "ext/gherkin_lexer_et/extconf.rb", "ext/gherkin_lexer_fa/extconf.rb", "ext/gherkin_lexer_fi/extconf.rb", "ext/gherkin_lexer_fr/extconf.rb", "ext/gherkin_lexer_gl/extconf.rb", "ext/gherkin_lexer_he/extconf.rb", "ext/gherkin_lexer_hi/extconf.rb", "ext/gherkin_lexer_hr/extconf.rb", "ext/gherkin_lexer_hu/extconf.rb", "ext/gherkin_lexer_id/extconf.rb", "ext/gherkin_lexer_is/extconf.rb", "ext/gherkin_lexer_it/extconf.rb", "ext/gherkin_lexer_ja/extconf.rb", "ext/gherkin_lexer_kn/extconf.rb", "ext/gherkin_lexer_ko/extconf.rb", "ext/gherkin_lexer_lt/extconf.rb", "ext/gherkin_lexer_lu/extconf.rb", "ext/gherkin_lexer_lv/extconf.rb", "ext/gherkin_lexer_nl/extconf.rb", "ext/gherkin_lexer_no/extconf.rb", "ext/gherkin_lexer_pa/extconf.rb", "ext/gherkin_lexer_pl/extconf.rb", "ext/gherkin_lexer_pt/extconf.rb", "ext/gherkin_lexer_ro/extconf.rb", "ext/gherkin_lexer_ru/extconf.rb", "ext/gherkin_lexer_sk/extconf.rb", "ext/gherkin_lexer_sr_cyrl/extconf.rb", "ext/gherkin_lexer_sr_latn/extconf.rb", "ext/gherkin_lexer_sv/extconf.rb", "ext/gherkin_lexer_th/extconf.rb", "ext/gherkin_lexer_tl/extconf.rb", "ext/gherkin_lexer_tr/extconf.rb", "ext/gherkin_lexer_tt/extconf.rb", "ext/gherkin_lexer_uk/extconf.rb", "ext/gherkin_lexer_uz/extconf.rb", "ext/gherkin_lexer_vi/extconf.rb", "ext/gherkin_lexer_zh_cn/extconf.rb", "ext/gherkin_lexer_zh_tw/extconf.rb"]
  s.files = ["ext/gherkin_lexer_ar/extconf.rb", "ext/gherkin_lexer_bg/extconf.rb", "ext/gherkin_lexer_bm/extconf.rb", "ext/gherkin_lexer_ca/extconf.rb", "ext/gherkin_lexer_cs/extconf.rb", "ext/gherkin_lexer_cy_gb/extconf.rb", "ext/gherkin_lexer_da/extconf.rb", "ext/gherkin_lexer_de/extconf.rb", "ext/gherkin_lexer_el/extconf.rb", "ext/gherkin_lexer_en/extconf.rb", "ext/gherkin_lexer_en_au/extconf.rb", "ext/gherkin_lexer_en_lol/extconf.rb", "ext/gherkin_lexer_en_old/extconf.rb", "ext/gherkin_lexer_en_pirate/extconf.rb", "ext/gherkin_lexer_en_scouse/extconf.rb", "ext/gherkin_lexer_en_tx/extconf.rb", "ext/gherkin_lexer_eo/extconf.rb", "ext/gherkin_lexer_es/extconf.rb", "ext/gherkin_lexer_et/extconf.rb", "ext/gherkin_lexer_fa/extconf.rb", "ext/gherkin_lexer_fi/extconf.rb", "ext/gherkin_lexer_fr/extconf.rb", "ext/gherkin_lexer_gl/extconf.rb", "ext/gherkin_lexer_he/extconf.rb", "ext/gherkin_lexer_hi/extconf.rb", "ext/gherkin_lexer_hr/extconf.rb", "ext/gherkin_lexer_hu/extconf.rb", "ext/gherkin_lexer_id/extconf.rb", "ext/gherkin_lexer_is/extconf.rb", "ext/gherkin_lexer_it/extconf.rb", "ext/gherkin_lexer_ja/extconf.rb", "ext/gherkin_lexer_kn/extconf.rb", "ext/gherkin_lexer_ko/extconf.rb", "ext/gherkin_lexer_lt/extconf.rb", "ext/gherkin_lexer_lu/extconf.rb", "ext/gherkin_lexer_lv/extconf.rb", "ext/gherkin_lexer_nl/extconf.rb", "ext/gherkin_lexer_no/extconf.rb", "ext/gherkin_lexer_pa/extconf.rb", "ext/gherkin_lexer_pl/extconf.rb", "ext/gherkin_lexer_pt/extconf.rb", "ext/gherkin_lexer_ro/extconf.rb", "ext/gherkin_lexer_ru/extconf.rb", "ext/gherkin_lexer_sk/extconf.rb", "ext/gherkin_lexer_sr_cyrl/extconf.rb", "ext/gherkin_lexer_sr_latn/extconf.rb", "ext/gherkin_lexer_sv/extconf.rb", "ext/gherkin_lexer_th/extconf.rb", "ext/gherkin_lexer_tl/extconf.rb", "ext/gherkin_lexer_tr/extconf.rb", "ext/gherkin_lexer_tt/extconf.rb", "ext/gherkin_lexer_uk/extconf.rb", "ext/gherkin_lexer_uz/extconf.rb", "ext/gherkin_lexer_vi/extconf.rb", "ext/gherkin_lexer_zh_cn/extconf.rb", "ext/gherkin_lexer_zh_tw/extconf.rb"]
  s.homepage = "http://github.com/cucumber/gherkin"
  s.licenses = ["MIT"]
  s.rdoc_options = ["--charset=UTF-8"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "gherkin-2.12.2"

  s.installed_by_version = "2.4.5.1" if s.respond_to? :installed_by_version

  if s.respond_to? :specification_version then
    s.specification_version = 4
```

**Comment by chrisroberts** [comment]
@randomvariable Thanks for the extra information. I'm getting a fedora instance spun up so I can get a local repro.

**Comment by JPvRiel** [comment]
To add a related example, this doesn't seem to work consistently for `Vagrant 1.9.1` on Linux

```
$ export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt`
$ curl -LI https://www.google.co.za -o /dev/null -w '%{http_code}\n' -s
200
$ vagrant box outdated
Checking if box 'centos/7' is up to date...
There was a problem while downloading the metadata for your box
to check for updates. This is not an error, since it is usually due
to temporary network problems. This is just a warning. The problem
encountered was:

SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html
...
$ vagrant box outdated --cacert /etc/ssl/certs/ca-certificates.crt
Checking if box 'centos/7' is up to date...
A newer version of the box 'centos/7' is available! You currently
have version '1610.01'. The latest is version '1611.01'. Run
`vagrant box update` to update.
```

So if curl can obey and use `/etc/ssl/certs/ca-certificates.crt`, why doesn't vagrant?

So at least we have the override of --cacert, but `SSL_CERT_FILE` is a more consistent / common way to work-around the embedded CA mess in most things ruby.

**Comment by kikitux** [comment]
Hello

Current version of Vagrant honor SSL_CERT_FILE

Please update and test.

reopen if still an issue

Thanks
