### ISSUE TITLE
VM hangs while sending keep-alive packets endlessly

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#8118]
Vagrant version: 1.9.1 ([`Vagrantfile`](https://github.com/EA31337/FX-MT-VM/blob/7780d196ab8aa10e78fb1d4f123a73376f88595e/Vagrantfile)), host OS: macOS, guess: Ubuntu

After I've added `config.ssh.keep_alive`, vagrant seems it hang on `vagrant up`.

See the log:

```
$ vagrant up
Bringing machine 'MT-virtualbox-default' up with 'virtualbox' provider...
==> MT-virtualbox-default: Importing base box 'ubuntu/wily64'...
==> MT-virtualbox-default: Matching MAC address for NAT networking...
==> MT-virtualbox-default: Checking if box 'ubuntu/wily64' is up to date...
==> MT-virtualbox-default: Setting the name of the VM: mt-tester.local
==> MT-virtualbox-default: Clearing any previously set forwarded ports...
==> MT-virtualbox-default: Clearing any previously set network interfaces...
==> MT-virtualbox-default: Preparing network interfaces based on configuration...
    MT-virtualbox-default: Adapter 1: nat
    MT-virtualbox-default: Adapter 2: hostonly
==> MT-virtualbox-default: Forwarding ports...
    MT-virtualbox-default: 22 (guest) => 2222 (host) (adapter 1)
==> MT-virtualbox-default: Running 'pre-boot' VM customizations...
==> MT-virtualbox-default: Booting VM...
==> MT-virtualbox-default: Waiting for machine to boot. This may take a few minutes...
    MT-virtualbox-default: SSH address: 127.0.0.1:2222
    MT-virtualbox-default: SSH username: vagrant
    MT-virtualbox-default: SSH auth method: private key
    MT-virtualbox-default: Warning: Remote connection disconnect. Retrying...
    MT-virtualbox-default: 
    MT-virtualbox-default: Vagrant insecure key detected. Vagrant will automatically replace
    MT-virtualbox-default: this with a newly generated keypair for better security.
    MT-virtualbox-default: 
    MT-virtualbox-default: Inserting generated public key within guest...
    MT-virtualbox-default: Removing insecure key from the guest if it's present...
    MT-virtualbox-default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> MT-virtualbox-default: Machine booted and ready!
[MT-virtualbox-default] GuestAdditions versions on your host (5.1.10) and guest (5.0.14) do not match.
(NOTE: HANG HERE)
^C==> MT-virtualbox-default: Waiting for cleanup before exiting...

load: 1.57  cmd: ruby 39462 waiting 5.17u 1.13s
load: 2.36  cmd: ruby 39462 waiting 5.18u 1.14s

(NOTE: ANOTHER HANG HERE)

	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/communicators/ssh/communicator.rb:604:in `block in shell_execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/communicators/ssh/communicator.rb:604:in `loop'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/communicators/ssh/communicator.rb:605:in `block (2 levels) in shell_execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/communicators/ssh/communicator.rb:605:in `sleep'

	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/communicators/ssh/communicator.rb:604:in `block in shell_execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/communicators/ssh/communicator.rb:604:in `loop'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/communicators/ssh/communicator.rb:605:in `block (2 levels) in shell_execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/communicators/ssh/communicator.rb:605:in `sleep'
^C==> MT-virtualbox-default: Exiting immediately, without cleanup!
```

In another terminal while ruby is hanging:

```
$ echo 'call (void)rb_backtrace()' | lldb -p $(pgrep -f ruby)
(lldb) process attach --pid 39462
Process 39462 stopped
* thread #1: tid = 0x182698c, 0x00007fff9c9e5c8a libsystem_kernel.dylib`__psynch_cvwait + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fff9c9e5c8a libsystem_kernel.dylib`__psynch_cvwait + 10
libsystem_kernel.dylib`__psynch_cvwait:
->  0x7fff9c9e5c8a <+10>: jae    0x7fff9c9e5c94            ; <+20>
    0x7fff9c9e5c8c <+12>: movq   %rax, %rdi
    0x7fff9c9e5c8f <+15>: jmp    0x7fff9c9ded6f            ; cerror_nocancel
    0x7fff9c9e5c94 <+20>: retq   
Executable module set to "/opt/vagrant/embedded/bin/ruby".
Architecture set to: x86_64h-apple-macosx.
(lldb) call (void)rb_backtrace()
```

Relevant code in `plugins/communicators/ssh/communicator.rb`:

          if @machine.config.ssh.keep_alive
            # Begin sending keep-alive packets while we wait for the script
            # to complete. This avoids connections closing on long-running
            # scripts.
            keep_alive = Thread.new do
              loop do
                sleep 5
                @logger.debug("Sending SSH keep-alive...")
                connection.send_global_request("keep-alive@openssh.com")
              end
            end
          end

**Comment by chrisroberts** [comment]
@kenorb Thanks for opening a new issue and including so much detail :+1:

**Comment by davejagoda** [comment]
Confirming this issue still exists as of 2019-10-13. Key details:
`apt-get install` and the vagrant-aws provider are both prerequisites.
Setting `config.ssh.pty = false` avoids the issue. A more dramatic workaround is to reboot the newly provisioned machine as the final step of the automated provisioning.

**Comment by LeTink** [comment]
Closed or not, I'm seeing this, too, using `vagrant 2.2.6` Virtualbox 5.2.36on `ubuntu 18.04` with `Virtualbox 5.2.36`.

Provisioning a `RHEL 7.7` instance I get stuck on setting hostname or bringing up network interfaces with `config.ssh.pty = true` set ... if I comment that out the provision works till I try to do a `git clone ssh://...` which then fails because of the missing tty ...
