### ISSUE TITLE
No live threads left

### ISSUE THREAD

**Issue by iDVB** [mitchellh/vagrant#8125]
### Vagrant version
Vagrant 1.9.1

### Host operating system
macOS Sierra (10.12.1)

### Guest operating system
ALL/ANY

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
end
```

### Debug output
[Error Msg](https://gist.github.com/iDVB/ddf1376c89aebd9f19e655d08b8db1b3)

### Expected behavior
VM should have installed and launched

### Actual behavior
Error `join': No live threads left. Deadlock?

### Steps to reproduce
1.   vagrant init hashicorp/precise64
2.  vagrant up

**Comment by james-pearce-aerian** [comment]
I'm having a similar issue details below

Vagrant version - Vagrant 1.9.1

Host operating system - OS X El Capitan (10.11.6)

Guest operating system - ALL/ANY

Error - No live threads left. Deadlock?

**Comment by chrisroberts** [comment]
@james-pearce-aerian can you provide a gist of `vagrant up --debug` output? Thanks!

**Comment by james-pearce-aerian** [comment]
@chrisroberts here you go

https://gist.github.com/james-pearce-aerian/a5b9df3571ca550bcc9e053080433bfd

**Comment by jbw976** [comment]
I am able to reproduce this on Vagrant 1.9.1 for Mac OS X El Capitan 10.11.4, when attempting to vagrant up the env provided in https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/vagrant.

Full debug output can be found here, let me know if I can gather any more information:
https://gist.github.com/jbw976/cfc5b7997cb106724d16db5df65f65c2

**Comment by danbenson** [comment]
Getting the same on Vagrant 1.9.1, MacOS Sierra 10.12.2 on vagrant up.

**Comment by danbenson** [comment]
[debug.txt](https://github.com/mitchellh/vagrant/files/674848/debug.txt)

**Comment by ddavtian** [comment]
Same here

**Comment by sbleon** [comment]
I had this problem as well, but I found a workaround. TL;DR: uninstall and reinstall vagrant.

Here's the full sequence of what I did.

1. Upgraded to macOS Sierra. 
2. vagrant tried to install Virtualbox on `vagrant up`, even though I already had it and it was working.
3. I reinstalled vagrant.
4. I got the "No live threads left" error.
5. I uninstalled vagrant (using the uninstall script on the installer image).
6. I reinstall vagrant.
7. All is well.

**Comment by maniarab** [comment]
I had the same issue with the following version combinations:
OS: OS X El Capitan (10.11.6)
Vagrant: 1.9.1
Virtualbox: 5.0.30
Ruby: 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]

![image](https://cloud.githubusercontent.com/assets/8727756/21731111/a9d1bed4-d407-11e6-9c97-4ed83b992831.png)

What ended up working for me was the following combination:
OS: OS X El Capitan (10.11.6)
**Vagrant: 1.8.5**
**Virtualbox: 5.0.20**
Ruby: 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]

Not exactly sure why we're having this issue with the latest versions of Vagrant & Virtualbox.  I'd love to hear what others think and also if my combination works on their machine.

**Comment by bitozoid** [comment]
Does not work on linux:
- vagrant 1.9.1
- virtualbox 5.1.10
- ruby 2.1.0

Works downgrading vagrant to 1.8.7.

**Comment by chrisroberts** [comment]
I am still working on getting a local repro of this so I can track down the problem. Thank you everyone for the information provided. Anyone else encountering this error, please post your host OS and version, Vagrant version and Ruby version if not running from the official Vagrant installer.

@sbleon What version of Vagrant were you upgrading from when the issue presented?

**Comment by m4ce** [comment]
Having the same issue..

OS: OSX Sierra
Vagrant: 1.9.1
Virtual Box: 5.0.30 r112061
Ruby: 2.2.6

**Comment by mikepsinn** [comment]
Getting this on 
OS: Windows 10
Vagrant: 1.9.1
Virtualbox: 5.1.14

**Comment by skelethan** [comment]
Same issue.  Tried uninstall / re-install & no success.  Up next, downgrading to 1.8.5 (last working version)

OS: Win 10
Vagrant: 1.9.1
VB: 5.1.2
Guest: CentOS

Debug output
https://gist.github.com/skelethan/fff84a49b2fd7d20f1b6ad603cfa9f96

**Comment by giovino** [comment]
I had same issue as described above.

OS: OS X (10.11.6)
Vagrant 1.9.1
VB: 5.1.14
Guest: hashicorp/precise64

Note: previous to getting this error I did the following:
 * Upgraded: VirtualBox 5.1.13 to 5.1.14
 * Upgraded: Vagrant  1.8.6 to 1.9.1

To the best of my knowledge Vagrant 1.8.6 was working as expected but hadn't used it in a few months. 

I was able to resolve the problem by  using the uninstall.tool in the Vagrant installer and then reinstalled Vagrant. Issue is now resolved.

**Comment by gitttt** [comment]
Same issue here on Win7:

- vagrant 1.9.1
- Virtualbox 5.1.14

**Comment by Jimadine** [comment]
The problem continues in vagrant 1.9.2 (Win 7, VirtualBox 5.1.14).  Tried the uninstall/reinstall trick but it didn't help.

**Comment by xiaods** [comment]
Tried the uninstall/reinstall trick but it didn't help. The problem continues in vagrant 1.9.3 (Macos, VirtualBox 5.1.14).

**Comment by xiaods** [comment]
```bash

$ vagrant up
Validating Plugins...
Validating User Config...
Validating Installer Checksum...
Using DC/OS Installer: installers/dcos/dcos_generate_config-1.8.8.sh
Using DC/OS Config: etc/config-1.8.yaml
Validating Machine Config...
Configuring VirtualBox Host-Only Network...
Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'a1' up with 'virtualbox' provider...
Bringing machine 'p1' up with 'virtualbox' provider...
Bringing machine 'boot' up with 'virtualbox' provider...
/opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/batch_action.rb:126:in `join': No live threads left. Deadlock? (fatal)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/batch_action.rb:126:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/batch_action.rb:65:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/batch_action.rb:65:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:287:in `block (2 levels) in batch'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:282:in `tap'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:282:in `block in batch'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:281:in `synchronize'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:281:in `batch'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/up/command.rb:88:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:308:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/bin/vagrant:127:in `<main>'

```

**Comment by xiaods** [comment]
we need clear /opt/vagrant and /usr/local/bin/vagrant, then vagrant works like a charm. please take a note.

**Comment by amaal23588** [comment]
This is a generic error, you may try to execute ngrok as executable first before trying from vagrant share

**Comment by wsj1028** [comment]
I have also encountered your problems. Who can point out the specific problems? My configuration is as follows？

OS: macOS  (10.13.6)
Vagrant 2.2.6
VB:  6.0.14 r133895 (Qt5.6.3)
Guest: centos7
Ruby:2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]

➜  centos_air vagrant share wl1 --http 8080
Vagrant Share now defaults to using the `ngrok` driver.
The `classic` driver has been deprecated.

For more information about the `ngrok` driver, please
refer to the documentation:

  https://www.vagrantup.com/docs/share/

==> wl1: Detecting network information for machine...
The Vagrant environment you're attempting to share appears to
not be running. Please verify that it is running and try again.
➜  centos_air vagrant up wl1
Bringing machine 'wl1' up with 'virtualbox' provider...
==> wl1: Clearing any previously set forwarded ports...
==> wl1: Clearing any previously set network interfaces...
==> wl1: Preparing network interfaces based on configuration...
    wl1: Adapter 1: nat
    wl1: Adapter 2: bridged
==> wl1: Forwarding ports...
    wl1: 80 (guest) => 8080 (host) (adapter 1)
    wl1: 22 (guest) => 2222 (host) (adapter 1)
==> wl1: Running 'pre-boot' VM customizations...
==> wl1: Booting VM...
==> wl1: Waiting for machine to boot. This may take a few minutes...
    wl1: SSH address: 127.0.0.1:2222
    wl1: SSH username: vagrant
    wl1: SSH auth method: private key
==> wl1: Machine booted and ready!
[wl1] GuestAdditions 6.0.14 running --- OK.
==> wl1: Checking for guest additions in VM...
==> wl1: Setting hostname...
==> wl1: Configuring and enabling network interfaces...
==> wl1: Rsyncing folder: /Users/wsj/tools/centos_air/ => /vagrant
==> wl1: Mounting shared folders...
    wl1: /home/vagrant/tools => /Users/wsj/tools/centos7/tools
==> wl1: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> wl1: flag to force provisioning. Provisioners marked to run always will still run.
➜  centos_air vagrant share wl1 --http 8080
Vagrant Share now defaults to using the `ngrok` driver.
The `classic` driver has been deprecated.

For more information about the `ngrok` driver, please
refer to the documentation:

  https://www.vagrantup.com/docs/share/

==> wl1: Detecting network information for machine...
    wl1: Local machine address: 127.0.0.1
    wl1:
    wl1: Note: With the local address (127.0.0.1), Vagrant Share can only
    wl1: share any ports you have forwarded. Assign an IP or address to your
    wl1: machine to expose all TCP ports. Consult the documentation
    wl1: for your provider ('virtualbox') for more information.
    wl1:
    wl1: Local HTTP port: 8080
    wl1: Local HTTPS port: disabled
    wl1: Port: 2222
    wl1: Port: 8080
==> wl1: Creating Vagrant Share session...
/Users/wsj/.vagrant.d/gems/2.4.9/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2409:in `join': No live threads left. Deadlock? (fatal)
2 threads, 2 sleeps current:0x0000000103fda160 main thread:0x0000000100700900
* #<Thread:0x00000001028670d8 sleep_forever>
   rb_thread_t:0x0000000100700900 native:0x00007fff8d4ee380 int:0
   /Users/wsj/.vagrant.d/gems/2.4.9/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2409:in `join'
   /Users/wsj/.vagrant.d/gems/2.4.9/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2409:in `start_share'
   /Users/wsj/.vagrant.d/gems/2.4.9/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2967:in `execute'
   /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
   /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
   /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:182:in `<main>'
* #<Thread:0x00000001025e2678@/Users/wsj/.vagrant.d/gems/2.4.9/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2506 sleep_forever>
   rb_thread_t:0x0000000104723420 native:0x0000700003560000 int:0
    depended by: tb_thread_id:0x0000000100700900
   /Users/wsj/.vagrant.d/gems/2.4.9/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2507:in `pop'
   /Users/wsj/.vagrant.d/gems/2.4.9/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2507:in `block in start_connect_info_watcher'
	from /Users/wsj/.vagrant.d/gems/2.4.9/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2409:in `start_share'
	from /Users/wsj/.vagrant.d/gems/2.4.9/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2967:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:182:in `<main>'
