### ISSUE TITLE
securerandom error with virtualbox packaging process vagrant v1.9.0

### ISSUE THREAD

**Issue by rburkholder** [mitchellh/vagrant#8159]
### Vagrant version
Vagrant 1.9.0

### Host operating system
$ uname -a
Linux z800 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02) x86_64 GNU/Linux

### Debug output
```
/usr/share/rubygems-integration/all/gems/vagrant-1.9.0/plugins/commands/package/command.rb:59:in `package_base': uninitialized constant VagrantPlugins::CommandPackage::Command::SecureRandom (NameError)
Did you mean?  SecureRandom
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/plugins/commands/package/command.rb:42:in `execute'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/cli.rb:42:in `execute'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/environment.rb:274:in `cli'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/bin/vagrant:118:in `<top (required)>'
        from /usr/bin/vagrant:22:in `load'
        from /usr/bin/vagrant:22:in `<main>'
```

### Expected behavior
should have built a package.box file

### Actual behavior
above error

### Steps to reproduce
```bash
vagrant package --base ${VIRTUALBOXNAME} 
```

### fix:
insert the string 
```ruby
require 'securerandom'
```
at beginning of:

plugins/commands/package/command.rb

**Comment by chrisroberts** [comment]
Fixed via #8160
