### ISSUE TITLE
Vagrant must check ruby and gcc packages on CentOS when installing plugins

### ISSUE THREAD

**Issue by vhosakot** [mitchellh/vagrant#8377]
### Vagrant version
```
# vagrant -v
Vagrant 1.8.7
```

### Host operating system
CentOS 7.3.

### Expected behavior
Vagrant must display a user-friendly error if the ruby and gcc packages are missing in CentOS (like `Please install ruby and gcc`) instead of the long error in the output.

### Actual behavior
`vagrant plugin install vagrant-env` displays the following long error if ruby and gcc packages are missing in CentOS.

```
# vagrant plugin install vagrant-env
Installing the 'vagrant-env' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.18), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.18'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby -r ./siteconf20170316-11991-fvej3e.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
	from extconf.rb:16:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /root/.vagrant.d/gems/gems/ffi-1.9.18 for inspection.
Results logged to /root/.vagrant.d/gems/extensions/x86_64-linux/2.2.0/ffi-1.9.18/gem_make.out
```
### Steps to reproduce
1. Make sure ruby and gcc are not installed on CentOS:
`yum list installed | grep 'ruby-devel\|gcc'`
2. Install any vagrant plugin:
`vagrant plugin install vagrant-env`

### Workaround:
The error is resolved after installing ruby-devel and gcc on CentOS (`yum -y install ruby-devel gcc`)

**Comment by vhosakot** [comment]
The error is resolved after installing ruby-devel and gcc on CentOS (yum -y install ruby-devel gcc)

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
