### ISSUE TITLE
WinRM issue after moving to 1.9.3

### ISSUE THREAD

**Issue by MariuszHxGNMIN** [mitchellh/vagrant#8403]
### Vagrant version
1.9.3

### Host operating system
Windows 10.

### Guest operating system
Windows 2016
### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
vmname = "ALAMAKOTA"
Vagrant.configure("2") do |config|
  config.vm.box = "SQL-Server-2016"
  config.vm.hostname = "ALAMAKOTA"

  ## Hyper-v Setup
  config.vm.provider "hyperv" do |vb|
    vb.vmname = vmname
    vb.cpus = 2
    vb.memory = 2048
    vb.maxmemory = 8196
  end

  ## Provision
  config.vm.provision :shell, path: "Provision/01-ALAMAKOTA.ps1"
end
```

### Debug output

Error comes up with WinRM after Hostname change operation:

```
DEBUG winrmshell: [WinRM] polling for pipeline state. message: #<WinRM::PSRP::Message:0x4d0d060 @data="\xEF\xBB\xBF<Obj RefId=\"0\"><MS><Version N=\"protocolversion\">2.3</Version><Version N=\"PSVersion\">2.0</Version><Version N=\"SerializationVersion\">1.1.0.1</Version></MS></Obj>", @destination=1, @type=65538, @pipeline_id="00000000-0000-0000-0000-000000000000", @runspace_pool_id="00000000-0000-0000-0000-000000000000">
DEBUG winrmshell: [WinRM] polling for pipeline state. message: #<WinRM::PSRP::Message:0x4d0c280 @data="\xEF\xBB\xBF<Obj RefId=\"0\"><MS><Obj N=\"ApplicationPrivateData\" RefId=\"1\"><TN RefId=\"0\"><T>System.Management.Automation.PSPrimitiveDictionary</T><T>System.Collections.Hashtable</T><T>System.Object</T></TN><DCT><En><S N=\"Key\">BreakAll</S><B N=\"Value\">false</B></En><En><S N=\"Key\">DebugStop</S><B N=\"Value\">false</B></En><En><S N=\"Key\">UnhandledBreakpointMode</S><I32 N=\"Value\">1</I32></En><En><S N=\"Key\">PSVersionTable</S><Obj N=\"Value\" RefId=\"2\"><TNRef RefId=\"0\" /><DCT><En><S N=\"Key\">PSVersion</S><Version N=\"Value\">5.1.14393.206</Version></En><En><S N=\"Key\">PSEdition</S><S N=\"Value\">Desktop</S></En><En><S N=\"Key\">PSCompatibleVersions</S><Obj N=\"Value\" RefId=\"3\"><TN RefId=\"1\"><T>System.Version[]</T><T>System.Array</T><T>System.Object</T></TN><LST><Version>1.0</Version><Version>2.0</Version><Version>3.0</Version><Version>4.0</Version><Version>5.0</Version><Version>5.1.14393.206</Version></LST></Obj></En><En><S N=\"Key\">CLRVersion</S><Version N=\"Value\">4.0.30319.42000</Version></En><En><S N=\"Key\">BuildVersion</S><Version N=\"Value\">10.0.14393.206</Version></En><En><S N=\"Key\">WSManStackVersion</S><Version N=\"Value\">3.0</Version></En><En><S N=\"Key\">PSRemotingProtocolVersion</S><Version N=\"Value\">2.3</Version></En><En><S N=\"Key\">SerializationVersion</S><Version N=\"Value\">1.1.0.1</Version></En></DCT></Obj></En><En><S N=\"Key\">DebugMode</S><I32 N=\"Value\">1</I32></En><En><S N=\"Key\">DebugBreakpointCount</S><I32 N=\"Value\">0</I32></En></DCT></Obj></MS></Obj>", @destination=1, @type=135177, @pipeline_id="00000000-0000-0000-0000-000000000000", @runspace_pool_id="00000000-0000-0000-0000-000000000000">
DEBUG winrmshell: [WinRM] Waiting for output...
DEBUG winrmshell: [WinRM] Processing output
DEBUG winrmshell: [WinRM] polling for pipeline state. message: #<WinRM::PSRP::Message:0x4c22478 @data="\xEF\xBB\xBF<Obj RefId=\"0\"><MS><I32 N=\"RunspaceState\">2</I32></MS></Obj>", @destination=1, @type=135173, @pipeline_id="00000000-0000-0000-0000-000000000000", @runspace_pool_id="00000000-0000-0000-0000-000000000000">
DEBUG winrmshell: [WinRM] remote shell created with shell_id: CD7142DE-079F-4F21-9AF5-E484B9829723
DEBUG winrmshell: [WinRM] Command created for if ([System.Net.Dns]::GetHostName() -eq 'miint') { exit 0 } exit 1
if (!$?) { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } } with id: C90DB6F8-DAFD-48F5-AC7F-855F44AFF263
DEBUG winrmshell: [WinRM] creating command_id: C90DB6F8-DAFD-48F5-AC7F-855F44AFF263 on shell_id CD7142DE-079F-4F21-9AF5-E484B9829723
DEBUG winrmshell: [WinRM] Waiting for output...
DEBUG winrmshell: [WinRM] Processing output
DEBUG winrmshell: [WinRM] cleaning up command_id: C90DB6F8-DAFD-48F5-AC7F-855F44AFF263 on shell_id CD7142DE-079F-4F21-9AF5-E484B9829723
DEBUG winrmshell: Output: #<WinRM::Output:0x4b731d0 @data=[], @exitcode=1>
DEBUG winrm: powershell executing:
            $computer = Get-WmiObject -Class Win32_ComputerSystem
            $retval = $computer.rename("miint").returnvalue
            if ($retval -eq 0) {
              shutdown /r /t 5 /f /d p:4:1 /c "Vagrant Rename Computer"
            }
            exit $retval

DEBUG winrmshell: [WinRM] opening remote shell on http://10.0.5.8:5985/wsman
DEBUG winrmshell: [WinRM] Waiting for output...
DEBUG winrmshell: [WinRM] Processing output
DEBUG winrmshell: [WinRM] polling for pipeline state. message: #<WinRM::PSRP::Message:0x4ac20c8 @data="\xEF\xBB\xBF<Obj RefId=\"0\"><MS><Version N=\"protocolversion\">2.3</Version><Version N=\"PSVersion\">2.0</Version><Version N=\"SerializationVersion\">1.1.0.1</Version></MS></Obj>", @destination=1, @type=65538, @pipeline_id="00000000-0000-0000-0000-000000000000", @runspace_pool_id="00000000-0000-0000-0000-000000000000">
DEBUG winrmshell: [WinRM] polling for pipeline state. message: #<WinRM::PSRP::Message:0x4ac1180 @data="\xEF\xBB\xBF<Obj RefId=\"0\"><MS><Obj N=\"ApplicationPrivateData\" RefId=\"1\"><TN RefId=\"0\"><T>System.Management.Automation.PSPrimitiveDictionary</T><T>System.Collections.Hashtable</T><T>System.Object</T></TN><DCT><En><S N=\"Key\">BreakAll</S><B N=\"Value\">false</B></En><En><S N=\"Key\">DebugStop</S><B N=\"Value\">false</B></En><En><S N=\"Key\">UnhandledBreakpointMode</S><I32 N=\"Value\">1</I32></En><En><S N=\"Key\">PSVersionTable</S><Obj N=\"Value\" RefId=\"2\"><TNRef RefId=\"0\" /><DCT><En><S N=\"Key\">PSVersion</S><Version N=\"Value\">5.1.14393.206</Version></En><En><S N=\"Key\">PSEdition</S><S N=\"Value\">Desktop</S></En><En><S N=\"Key\">PSCompatibleVersions</S><Obj N=\"Value\" RefId=\"3\"><TN RefId=\"1\"><T>System.Version[]</T><T>System.Array</T><T>System.Object</T></TN><LST><Version>1.0</Version><Version>2.0</Version><Version>3.0</Version><Version>4.0</Version><Version>5.0</Version><Version>5.1.14393.206</Version></LST></Obj></En><En><S N=\"Key\">CLRVersion</S><Version N=\"Value\">4.0.30319.42000</Version></En><En><S N=\"Key\">BuildVersion</S><Version N=\"Value\">10.0.14393.206</Version></En><En><S N=\"Key\">WSManStackVersion</S><Version N=\"Value\">3.0</Version></En><En><S N=\"Key\">PSRemotingProtocolVersion</S><Version N=\"Value\">2.3</Version></En><En><S N=\"Key\">SerializationVersion</S><Version N=\"Value\">1.1.0.1</Version></En></DCT></Obj></En><En><S N=\"Key\">DebugMode</S><I32 N=\"Value\">1</I32></En><En><S N=\"Key\">DebugBreakpointCount</S><I32 N=\"Value\">0</I32></En></DCT></Obj></MS></Obj>", @destination=1, @type=135177, @pipeline_id="00000000-0000-0000-0000-000000000000", @runspace_pool_id="00000000-0000-0000-0000-000000000000">
DEBUG winrmshell: [WinRM] Waiting for output...
DEBUG winrmshell: [WinRM] Processing output
DEBUG winrmshell: [WinRM] polling for pipeline state. message: #<WinRM::PSRP::Message:0x401a4c8 @data="\xEF\xBB\xBF<Obj RefId=\"0\"><MS><I32 N=\"RunspaceState\">2</I32></MS></Obj>", @destination=1, @type=135173, @pipeline_id="00000000-0000-0000-0000-000000000000", @runspace_pool_id="00000000-0000-0000-0000-000000000000">
DEBUG winrmshell: [WinRM] remote shell created with shell_id: B1C2D23A-E33A-4E1D-BE90-B7BA76AA352C
DEBUG winrmshell: [WinRM] Command created for             $computer = Get-WmiObject -Class Win32_ComputerSystem
            $retval = $computer.rename("miint").returnvalue
            if ($retval -eq 0) {
              shutdown /r /t 5 /f /d p:4:1 /c "Vagrant Rename Computer"
            }
            exit $retval

if (!$?) { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } } with id: 0EEB34F5-8116-4CB5-B61B-B5A020E0DE77
DEBUG winrmshell: [WinRM] creating command_id: 0EEB34F5-8116-4CB5-B61B-B5A020E0DE77 on shell_id B1C2D23A-E33A-4E1D-BE90-B7BA76AA352C
DEBUG winrmshell: [WinRM] Waiting for output...
DEBUG winrmshell: [WinRM] Processing output
DEBUG winrmshell: [WinRM] Waiting for output...
DEBUG winrmshell: [WinRM] Processing output
DEBUG winrmshell: [WinRM] cleaning up command_id: 0EEB34F5-8116-4CB5-B61B-B5A020E0DE77 on shell_id B1C2D23A-E33A-4E1D-BE90-B7BA76AA352C
DEBUG winrmshell: Output: #<WinRM::Output:0x3d9c680 @data=[], @exitcode=0>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::SetHostname:0x4b62910>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::SyncedFolders:0x4b99468>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::WaitForCommunicator:0x4b99480>
 INFO warden: Calling OUT action: #<VagrantPlugins::HyperV::Action::WaitForIPAddress:0x4bc0018>
 INFO warden: Calling OUT action: #<VagrantPlugins::HyperV::Action::StartInstance:0x4bc0030>
 INFO warden: Calling OUT action: #<VagrantPlugins::HyperV::Action::NetSetMac:0x4bc0060>
 INFO warden: Calling OUT action: #<VagrantPlugins::HyperV::Action::NetSetVLan:0x4bc0090>
 INFO provision: Writing provisioning sentinel so we don't provision again
 INFO interface: info: Running provisioner: shell...
 INFO interface: info: ==> default: Running provisioner: shell...
 INFO environment: Running hook: provisioner_run
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: provisioner_run #<Method: Vagrant::Action::Builtin::Provision#run_provisioner>
 INFO warden: Calling IN action: #<Proc:0x4b3b820@C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: hyperv
 INFO machine: Calling action: read_state on provider Hyper-V (e36c99c4-3f8e-4ed5-9522-e394a46fdf14)
 INFO interface: Machine: action ["read_state", "start", {:target=>:default}]
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: machine_action_read_state #<Vagrant::Action::Builder:0x4aead78>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x4ae8b28>
 INFO warden: Calling IN action: #<VagrantPlugins::HyperV::Action::ReadState:0x4ae8b10>
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoProfile", "-ExecutionPolicy", "Bypass", "&('C:\\Program Files (x86)\\Vagrant\\embedded\\gems\\gems\\vagrant-1.9.3\\plugins\\providers\\hyperv\\scripts\\get_vm_status.ps1')", "-VmId", "'e36c99c4-3f8e-4ed5-9522-e394a46fdf14'", "-ErrorAction", "Stop"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: ===Begin-Output===
{
    "state":  "Running",
    "status":  "Operating normally"
}
===End-Output===
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO warden: Calling OUT action: #<VagrantPlugins::HyperV::Action::ReadState:0x4ae8b10>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x4ae8b28>
 INFO interface: Machine: action ["read_state", "end", {:target=>:default}]
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoProfile", "-ExecutionPolicy", "Bypass", "&('C:\\Program Files (x86)\\Vagrant\\embedded\\gems\\gems\\vagrant-1.9.3\\plugins\\providers\\hyperv\\scripts\\get_network_config.ps1')", "-VmId", "'e36c99c4-3f8e-4ed5-9522-e394a46fdf14'", "-ErrorAction", "Stop"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: ===Begin-Output===
{
    "ip":  ""
}
===End-Output===
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31994
DEBUG subprocess: Exit status: 0
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x4ecca50>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x4d62a70>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x4a6c580>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-98b8138fe17c455380afd15a7b9a3904
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x4bf3c00>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::CommunicatorWinRM::Errors::WinRMNotReady: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.>
ERROR vagrant: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
ERROR vagrant: C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/communicators/winrm/helper.rb:36:in `winrm_address'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/communicators/winrm/helper.rb:21:in `winrm_info'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/communicators/winrm/communicator.rb:186:in `create_shell'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/communicators/winrm/communicator.rb:126:in `shell'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/communicators/winrm/communicator.rb:107:in `block in ready?'
C:/Program Files (x86)/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
C:/Program Files (x86)/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
C:/Program Files (x86)/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
C:/Program Files (x86)/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
C:/Program Files (x86)/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/communicators/winrm/communicator.rb:106:in `ready?'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/machine.rb:260:in `guest'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/provisioners/shell/provisioner.rb:100:in `provision_winrm'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/provisioners/shell/provisioner.rb:22:in `provision'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/provision.rb:138:in `run_provisioner'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:95:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:479:in `hook'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/provision.rb:126:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/provision.rb:126:in `block in call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/provision.rb:103:in `each'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/provision.rb:103:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/providers/hyperv/action/import.rb:156:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/providers/hyperv/action/check_enabled.rb:18:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/machine.rb:225:in `action_raw'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/machine.rb:200:in `block in action'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:567:in `lock'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/machine.rb:186:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/machine.rb:186:in `action'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/logging-2.2.0/lib/logging/diagnostic_context.rb:474:in `call'
C:/Program Files (x86)/Vagrant/embedded/gems/gems/logging-2.2.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
 INFO interface: error: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
 INFO interface: Machine: error-exit ["VagrantPlugins::CommunicatorWinRM::Errors::WinRMNotReady", "The box is not able to report an address for WinRM to connect to yet.\nWinRM cannot access this Vagrant environment. Please wait for the\nVagrant environment to be running and try again."]
```

### Expected behavior
Run WinRM provision script

### Actual behavior
The box is not able to report an address for WinRM to connect to yet.\nWinRM cannot access this Vagrant environment. Please wait for the\nVagrant environment to be running and try again."

### Steps to reproduce
On windows guest change hostname via config.vm.hostname configuration and then try to run ps script

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
