### ISSUE TITLE
Can't Run Windows Image on Mac Due to vagrant-windows Plugin Issues

### ISSUE THREAD

**Issue by jamiejackson** [mitchellh/vagrant#8477]
macOS Sierra 10.12.4 (16E195)

```
$ vagrant --version
Vagrant 1.9.3

$ vagrant init opentable/win-7-professional-amd64-nocm
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

$ vagrant up
vagrant-windows missing, please install the vagrant-windows plugin!
Run this command in your terminal:
vagrant plugin install vagrant-windows

$ vagrant plugin install vagrant-windows
Installing the 'vagrant-windows' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies nokogiri (~> 1.5.0) and nokogiri (= 1.6.7.1)
  Activated nokogiri-1.6.7.1
  which does not match conflicting dependency (~> 1.5.0)

  Conflicting dependency chains:
    vagrant-share (> 0), 1.1.7 activated, depends on
    vagrant (>= 1.9.2), 1.9.3 activated, depends on
    nokogiri (= 1.6.7.1), 1.6.7.1 activated

  versus:
    vagrant-windows (> 0), 1.6.0 activated, depends on
    winrm (~> 1.1.1), 1.1.1 activated, depends on
    nokogiri (~> 1.5.0)
```

This was after I upgraded to 1.9.3, because I was getting the following in 1.9.1:

```
$ vagrant plugin install vagrant-windows
Installing the 'vagrant-windows' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate nori-1.1.5, already activated nori-2.6.0 (Gem::LoadError)
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:323:in `block in activate_solution'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `activate_solution'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:248:in `internal_install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:98:in `install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/action/install_gem.rb:37:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:32:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
```

**Comment by jamiejackson** [comment]
This might be a dupe of https://github.com/mitchellh/vagrant/issues/8313. I'm reading through that.

**Comment by jamiejackson** [comment]
I'm trying to prove the #8313 theory--that old Windows images (which rely on the vagrant-windows plugin)--are to blame, but another issue, #8478, is preventing it.

**Comment by chrisroberts** [comment]
The vagrant-windows plugin is deprecated and not required in newer versions of Vagrant as windows support is included. The plugin will not install on newer versions of Vagrant as the dependency constraints of the vagrant-windows plugin cannot be satisfied. 

Cheers!
