### ISSUE TITLE
vagrant-azure files to install

### ISSUE THREAD

**Issue by purplefeetguy** [mitchellh/vagrant#8547]
While this may be a "duplicate" of vagrant plugin issus 150, I do not see a resolution. If I reinstall, as suggested, it still doesn't work. I tried reopening and it opened for 2 hours and was closed again with no information or response, so I am trying to open it here. Any suggestions will be appreciated.

This is a fresh OS install of ubunt 16.04.2 LTS

purplefeetguy@pflnuc04:~$ vagrant --version
Vagrant 1.9.4
purplefeetguy@pflnuc04:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
purplefeetguy@pflnuc04:~$ ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
purplefeetguy@pflnuc04:~$ vagrant plugin install vagrant-azure
Installing the 'vagrant-azure' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-2.99.3, already activated mime-types-3.1 (Gem::LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/bundler.rb:388:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/bundler.rb:385:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/bundler.rb:385:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/bundler.rb:288:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/bundler.rb:106:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/action/install_gem.rb:29:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/bin/vagrant:127:in `<main>'
purplefeetguy@pflnuc04:~$

**Comment by purplefeetguy** [comment]
my bad....I should read more....please ignore...
