### ISSUE TITLE
Parallels VM modified by "vagrant up", resulting in failure

### ISSUE THREAD

**Issue by janssen** [mitchellh/vagrant#8799]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.9.7

### Host operating system
MacOS Sierra

### Guest operating system
Ubuntu Desktop 16.04 LTS

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "test"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

### Expected behavior
Working Vagrant image.

### Actual behavior
```
[monarch:/tmp/xx] wjanssen% vagrant box list
[0;33mThere are no installed boxes! Use `vagrant box add` to add some.[0m
[monarch:/tmp/xx] wjanssen% vagrant box add --name=test /tmp/custom.box
[1m==> box: Box file was not detected as metadata. Adding it directly...[0m
[1m==> box: Adding box 'test' (v0) for provider: [0m
[0m    box: Unpacking necessary files from: file:///tmp/custom.box[0m
[K[0m[1;32m==> box: Successfully added box 'test' (v0) for 'parallels'![0m
[monarch:/tmp/xx] wjanssen% ls -F ~/.vagrant.d/boxes/test/0/parallels
metadata.json	tester.pvm/
[monarch:/tmp/xx] wjanssen% ls -F ~/.vagrant.d/boxes/test/0/parallels/tester.pvm/
Snapshots.xml				VmInfo.pvi				parallels.log
Ubuntu Linux 16.04 Desktop-0.hdd/	config.pvs*				statistic.log
Ubuntu Linux 16.04 Desktop.app/		config.pvs.backup*			vm.lock
[monarch:/tmp/xx] wjanssen% vagrant init test
[0mA `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.[0m
[monarch:/tmp/xx] wjanssen% ls -F ~/.vagrant.d/boxes/test/0/parallels
metadata.json	tester.pvm/
[monarch:/tmp/xx] wjanssen% ls -F ~/.vagrant.d/boxes/test/0/parallels/tester.pvm/
Snapshots.xml				VmInfo.pvi				parallels.log
Ubuntu Linux 16.04 Desktop-0.hdd/	config.pvs*				statistic.log
Ubuntu Linux 16.04 Desktop.app/		config.pvs.backup*			vm.lock
[monarch:/tmp/xx] wjanssen% vagrant up
[0mBringing machine 'default' up with 'parallels' provider...[0m
[1m==> default: Registering VM image from the base box 'test'...[0m
/Users/wjanssen/.vagrant.d/gems/2.3.4/gems/vagrant-parallels-1.7.5/lib/vagrant-parallels/action/box_register.rb:54:in `initialize': No such file or directory @ rb_sysopen - /Users/wjanssen/.vagrant.d/boxes/test/0/parallels/tester.pvm/config.pvs (Errno::ENOENT)
	from /Users/wjanssen/.vagrant.d/gems/2.3.4/gems/vagrant-parallels-1.7.5/lib/vagrant-parallels/action/box_register.rb:54:in `open'
	from /Users/wjanssen/.vagrant.d/gems/2.3.4/gems/vagrant-parallels-1.7.5/lib/vagrant-parallels/action/box_register.rb:54:in `box_id'
	from /Users/wjanssen/.vagrant.d/gems/2.3.4/gems/vagrant-parallels-1.7.5/lib/vagrant-parallels/action/box_register.rb:113:in `register_box'
	from /Users/wjanssen/.vagrant.d/gems/2.3.4/gems/vagrant-parallels-1.7.5/lib/vagrant-parallels/action/box_register.rb:27:in `block (2 levels) in call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/environment.rb:631:in `lock'
	from /Users/wjanssen/.vagrant.d/gems/2.3.4/gems/vagrant-parallels-1.7.5/lib/vagrant-parallels/action/box_register.rb:26:in `block in call'
	from /Users/wjanssen/.vagrant.d/gems/2.3.4/gems/vagrant-parallels-1.7.5/lib/vagrant-parallels/action/box_register.rb:24:in `synchronize'
	from /Users/wjanssen/.vagrant.d/gems/2.3.4/gems/vagrant-parallels-1.7.5/lib/vagrant-parallels/action/box_register.rb:24:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/wjanssen/.vagrant.d/gems/2.3.4/gems/vagrant-parallels-1.7.5/lib/vagrant-parallels/action/customize.rb:39:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/machine.rb:227:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/machine.rb:202:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/environment.rb:631:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/machine.rb:188:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/machine.rb:188:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
[monarch:/tmp/xx] wjanssen% ls -F ~/.vagrant.d/boxes/test/0/parallels
box_lease_count		metadata.json		tester (3).pvm/
[monarch:/tmp/xx] wjanssen%
```

### Steps to reproduce
Um, try to create a parallels vagrant box?

### References
Don't know.

**Comment by kikitux** [comment]
@legal90 any ideas?

**Comment by kikitux** [comment]
@janssen  can you try with Vagrant 1.9.6?

**Comment by janssen** [comment]
Will do.

**Comment by briancain** [comment]
@janssen - I recommend re-opening this issue against the [vagrant-parallels](https://github.com/Parallels/vagrant-parallels) repo, thanks!

**Comment by janssen** [comment]
@briancain -- yes, https://github.com/Parallels/vagrant-parallels/issues/303.
