### ISSUE TITLE
vagrant up --provider=libvirt  Error : cannot exeute binary file  /usr/local/bin/qemu-img: permission issus (Libvirt::Error)

### ISSUE THREAD

**Issue by liufeng11** [mitchellh/vagrant#8944]
### Vagrant version
Vagrant 1.9.8

### Host operating system
ubuntu16.04

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
end




### Expected behavior
vagrant up  --provider=libvirt  start the VM successfully

### Actual behavior
==> default: Remove stale volume...
==> default: Domain is not created. Please run `vagrant up` first.
root@liufeng-Lenovo-Product:/home/liufeng/rkt# vagrant up --provider=libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
/root/.vagrant.d/gems/2.3.4/gems/fog-libvirt-0.4.0/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml': Call to virStorageVolCreateXML failed: 内部错误：子进程（/usr/local/bin/qemu-img create -f qcow2 -b /var/lib/libvirt/images/ubuntu-VAGRANTSLASH-xenial64_vagrant_box_image_20170822.0.0.img -o backing_fmt=qcow2 /var/lib/libvirt/images/rkt_default.img 10485760K）意外 退出状态 126: libvirt:  错误 : 无法执行二进制文件 /usr/local/bin/qemu-img: 权限不够 (Libvirt::Error)
	from /root/.vagrant.d/gems/2.3.4/gems/fog-libvirt-0.4.0/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume'
	from /root/.vagrant.d/gems/2.3.4/gems/fog-libvirt-0.4.0/lib/fog/libvirt/models/compute/volume.rb:40:in `save'
	from /root/.vagrant.d/gems/2.3.4/gems/fog-core-1.43.0/lib/fog/core/collection.rb:51:in `create'
	from /root/.vagrant.d/gems/2.3.4/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/create_domain_volume.rb:73:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/warden.rb:34:in `call'
	from /root/.vagrant.d/gems/2.3.4/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/handle_box_image.rb:113:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/warden.rb:34:in `call'
	from /root/.vagrant.d/gems/2.3.4/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/handle_storage_pool.rb:52:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/warden.rb:34:in `call'
	from /root/.vagrant.d/gems/2.3.4/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/warden.rb:34:in `call'
	from /root/.vagrant.d/gems/2.3.4/gems/vagrant-rekey-ssh-0.1.9/lib/vagrant-rekey-ssh/actions/ssh_info.rb:47:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/machine.rb:227:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/machine.rb:202:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/environment.rb:631:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/machine.rb:188:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/machine.rb:188:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'


### Steps to reproduce
1.# vagrant init ubuntu/xenial64
2. # vagrant up --provider=libvirt

**Comment by briancain** [comment]
👋 Hi there @liufeng11 - This seems to be a bug with the [libvirt](https://github.com/vagrant-libvirt/vagrant-libvirt) provider. I recommend opening an issue with them...thanks!

**Comment by liufeng11** [comment]
Ok, thanks
